/**
 * Exercise seed catalog — part 3 (arms, core, cardio + Educador seated extras).
 */

import type { SeedExercise } from "./exercise-seed-catalog";

function ex(partial: SeedExercise): SeedExercise {
  return partial;
}

const PLYO = [
  "torn-acl",
  "patellar-tendinopathy",
  "knee-osteoarthritis",
  "plantar-fasciitis",
  "osteoporosis-osteopenia",
  "pregnancy-trimester-2",
  "pregnancy-trimester-3",
  "labyrinthitis",
  "hemiplegia-hemiparesis",
  "cerebral-palsy-mild-moderate",
  "visual-impairment",
];
const SPINE_FLEX_ROT = ["disc-herniation", "hernia", "spondylolisthesis"];
const SPINE_HYPER = ["spondylolisthesis", "spinal-stenosis", "disc-herniation"];
const WRIST_LOAD = [
  "carpal-tunnel-de-quervain",
  "tfcc-injury",
  "rheumatoid-arthritis",
];
const CORE_PRESSURE = ["diastasis-recti", "athletic-pubalgia"];
const ELBOW = ["epicondylitis", "elbow-ucl-injury", "olecranon-bursitis"];
const KNEE_LATERAL = [
  "collateral-ligament-injury",
  "torn-acl",
  "ankle-ligament-sprain",
];
const SHOULDER_OVERHEAD = [
  "rotator-cuff-injury",
  "subacromial-bursitis",
  "shoulder-instability",
];

export const EXERCISE_SEED_CATALOG_PART3: SeedExercise[] = [
  // --- Arms ---
  ex({
    slug: "floor-tricep-dip",
    title: "Mergulho no solo (tríceps dip no chão)",
    description:
      "Sentado no chão com mãos atrás do corpo, eleve o quadril e flexione os cotovelos. Amplitude curta.",
    targetMuscles: ["arms"],
    equipmentTags: ["bodyweight"],
    requiredCapabilityTags: ["lying", "seated", "low-impact"],
    intensityTags: ["low-intensity", "wrist-extension-load"],
    contraindicationTags: [...WRIST_LOAD, ...ELBOW],
    isPublished: true,
  }),
  ex({
    slug: "chair-dip",
    title: "Mergulho em cadeira/banco",
    description:
      "Mãos na beira da cadeira, desça o corpo flexionando os cotovelos e empurre para subir. Pés no chão.",
    targetMuscles: ["arms", "shoulders"],
    equipmentTags: ["chair", "bodyweight"],
    requiredCapabilityTags: ["seated", "standing", "low-impact"],
    intensityTags: ["medium-intensity", "wrist-extension-load"],
    contraindicationTags: [...WRIST_LOAD, ...ELBOW, "shoulder-instability"],
    isPublished: true,
  }),
  ex({
    slug: "overhead-tricep-extension",
    title: "Tríceps francês",
    description:
      "Segure garrafa ou elástico acima da cabeça e flexione só o cotovelo, levando o peso atrás da cabeça.",
    targetMuscles: ["arms"],
    equipmentTags: ["resistance-band", "bottle"],
    requiredCapabilityTags: ["standing", "seated", "low-impact"],
    intensityTags: ["low-intensity", "overhead-press"],
    contraindicationTags: [...ELBOW, ...SHOULDER_OVERHEAD],
    isPublished: true,
  }),
  ex({
    slug: "tricep-kickback",
    title: "Tríceps coice (kickback)",
    description:
      "Tronco inclinado, cotovelo fixo ao lado do corpo. Estenda o antebraço para trás com garrafa ou elástico.",
    targetMuscles: ["arms"],
    equipmentTags: ["resistance-band", "bottle"],
    requiredCapabilityTags: ["standing", "low-impact"],
    intensityTags: ["low-intensity"],
    contraindicationTags: [...ELBOW],
    isPublished: true,
  }),
  ex({
    slug: "tricep-pulley-band",
    title: "Tríceps pulley",
    description:
      "Ancore o elástico no alto e estenda os cotovelos para baixo, mantendo os braços junto ao tronco.",
    targetMuscles: ["arms"],
    equipmentTags: ["resistance-band"],
    requiredCapabilityTags: ["standing", "seated", "low-impact"],
    intensityTags: ["low-intensity"],
    contraindicationTags: [...ELBOW],
    isPublished: true,
  }),
  ex({
    slug: "biceps-curl",
    title: "Rosca direta",
    description:
      "Segure garrafas ou elástico e flexione os cotovelos levando as mãos aos ombros. Controle a descida.",
    targetMuscles: ["arms"],
    equipmentTags: ["resistance-band", "bottle"],
    requiredCapabilityTags: ["standing", "seated", "low-impact"],
    intensityTags: ["low-intensity", "prolonged-grip"],
    contraindicationTags: [...ELBOW, "rheumatoid-arthritis"],
    isPublished: true,
  }),
  ex({
    slug: "hammer-curl",
    title: "Rosca martelo",
    description:
      "Como a rosca direta, mas com as palmas voltadas uma para a outra (garrafas em posição neutra).",
    targetMuscles: ["arms"],
    equipmentTags: ["bottle"],
    requiredCapabilityTags: ["standing", "seated", "low-impact"],
    intensityTags: ["low-intensity", "prolonged-grip"],
    contraindicationTags: [...ELBOW],
    isPublished: true,
  }),
  ex({
    slug: "reverse-wrist-plank",
    title: "Flexão de pulso invertida no solo",
    description:
      "Apoio com dorso das mãos no solo (ou punhos neutros em suportes). Só para quem não tem dor no punho.",
    targetMuscles: ["arms"],
    equipmentTags: ["bodyweight"],
    requiredCapabilityTags: ["lying"],
    intensityTags: ["low-intensity", "wrist-extension-load"],
    contraindicationTags: [...WRIST_LOAD],
    isPublished: false,
  }),

  // --- Core ---
  ex({
    slug: "front-plank",
    title: "Prancha frontal isométrica",
    description:
      "Antebraços e pontas dos pés no solo, corpo alinhado. Segure poucos segundos. Joelho no solo se precisar.",
    targetMuscles: ["core"],
    equipmentTags: ["bodyweight"],
    requiredCapabilityTags: ["lying", "low-impact"],
    intensityTags: ["low-intensity", "forearm-plank-hard", "high-intra-abdominal-pressure"],
    contraindicationTags: [...CORE_PRESSURE, "olecranon-bursitis", "hypertension"],
    isPublished: true,
  }),
  ex({
    slug: "unstable-plank",
    title: "Prancha instável",
    description:
      "Prancha com antebraços sobre almofada firme. Priorize estabilidade, não tempo longo.",
    targetMuscles: ["core"],
    equipmentTags: ["cushion", "bodyweight"],
    requiredCapabilityTags: ["lying", "low-impact"],
    intensityTags: ["medium-intensity", "unstable-base", "high-intra-abdominal-pressure"],
    contraindicationTags: [...CORE_PRESSURE, "labyrinthitis"],
    isPublished: true,
  }),
  ex({
    slug: "side-plank",
    title: "Prancha lateral isométrica",
    description:
      "Apoie um antebraço e a lateral do pé. Quadril elevado. Troque de lado. Use joelho no solo para regressão.",
    targetMuscles: ["core"],
    equipmentTags: ["bodyweight"],
    requiredCapabilityTags: ["lying", "unilateral", "low-impact"],
    intensityTags: ["low-intensity", "forearm-plank-hard", "side-lying-pressure"],
    contraindicationTags: ["trochanteric-bursitis", "olecranon-bursitis", ...CORE_PRESSURE],
    isPublished: true,
  }),
  ex({
    slug: "side-plank-hip-dip",
    title: "Prancha lateral com mergulho de quadril",
    description:
      "Na prancha lateral, abaixe e eleve o quadril com controle sem perder o alinhamento.",
    targetMuscles: ["core"],
    equipmentTags: ["bodyweight"],
    requiredCapabilityTags: ["lying", "unilateral"],
    intensityTags: ["medium-intensity", "side-lying-pressure"],
    contraindicationTags: ["trochanteric-bursitis", ...CORE_PRESSURE],
    isPublished: true,
  }),
  ex({
    slug: "plank-shoulder-tap",
    title: "Prancha com toque nos ombros",
    description:
      "Em prancha alta, toque o ombro oposto com a mão alternando lados, sem girar o quadril.",
    targetMuscles: ["core", "shoulders"],
    equipmentTags: ["bodyweight"],
    requiredCapabilityTags: ["lying"],
    intensityTags: ["medium-intensity", "wrist-extension-load", "floor-push"],
    contraindicationTags: [...WRIST_LOAD, ...CORE_PRESSURE],
    isPublished: true,
  }),
  ex({
    slug: "commando-plank",
    title: "Prancha comando (sobe e desce)",
    description:
      "Alternee entre prancha de antebraços e prancha alta, um braço de cada vez.",
    targetMuscles: ["core", "arms"],
    equipmentTags: ["bodyweight"],
    requiredCapabilityTags: ["lying"],
    intensityTags: ["medium-intensity", "wrist-extension-load", "forearm-plank-hard"],
    contraindicationTags: [...WRIST_LOAD, ...ELBOW, ...CORE_PRESSURE],
    isPublished: true,
  }),
  ex({
    slug: "plank-jack",
    title: "Prancha com abdução de pernas (plank jacks)",
    description:
      "Em prancha, abra e feche as pernas com saltitos. Versão sem salto: deslize os pés.",
    targetMuscles: ["core", "legs"],
    equipmentTags: ["bodyweight"],
    requiredCapabilityTags: ["lying"],
    intensityTags: [
      "high-intensity",
      "explosive-adductors",
      "high-intra-abdominal-pressure",
      "lower-body-plyometrics",
    ],
    contraindicationTags: [...CORE_PRESSURE, "athletic-pubalgia", ...PLYO],
    isPublished: true,
  }),
  ex({
    slug: "plank-tuck-jump",
    title: "Prancha com salto agrupado",
    description:
      "Da prancha alta, salte os pés em direção às mãos e volte. Alto impacto.",
    targetMuscles: ["core", "legs", "full-body"],
    equipmentTags: ["bodyweight"],
    requiredCapabilityTags: ["lying"],
    intensityTags: ["high-intensity", "high-impact", "lower-body-plyometrics", "high-intra-abdominal-pressure"],
    contraindicationTags: [...PLYO, ...CORE_PRESSURE],
    isPublished: true,
  }),
  ex({
    slug: "reverse-plank",
    title: "Prancha reversa",
    description:
      "Sente-se, apoie as mãos atrás e eleve o quadril alinhando o corpo. Olhar neutro.",
    targetMuscles: ["core", "arms", "glutes"],
    equipmentTags: ["bodyweight"],
    requiredCapabilityTags: ["lying", "seated", "low-impact"],
    intensityTags: ["medium-intensity", "wrist-extension-load"],
    contraindicationTags: [...WRIST_LOAD, "shoulder-instability"],
    isPublished: true,
  }),
  ex({
    slug: "plank-row",
    title: "Prancha com remada",
    description:
      "Em prancha alta, puxe um elástico ancorado à frente até o tronco. Alternar lados.",
    targetMuscles: ["core", "back", "arms"],
    equipmentTags: ["resistance-band", "bodyweight"],
    requiredCapabilityTags: ["lying"],
    intensityTags: ["medium-intensity", "wrist-extension-load", "floor-push"],
    contraindicationTags: [...WRIST_LOAD, ...CORE_PRESSURE],
    isPublished: true,
  }),
  ex({
    slug: "crunch",
    title: "Abdominal supra (curto)",
    description:
      "Deite de costas e eleve só a cabeça e os ombros do solo. Sem puxar o pescoço.",
    targetMuscles: ["core"],
    equipmentTags: ["bodyweight"],
    requiredCapabilityTags: ["lying", "low-impact"],
    intensityTags: ["low-intensity"],
    contraindicationTags: ["disc-herniation", "pregnancy-trimester-2", "pregnancy-trimester-3"],
    isPublished: true,
  }),
  ex({
    slug: "weighted-crunch",
    title: "Abdominal supra com carga",
    description:
      "Mesmo supra com pacote leve no peito. Só se o movimento sem carga já estiver confortável.",
    targetMuscles: ["core"],
    equipmentTags: ["food-bag", "bodyweight"],
    requiredCapabilityTags: ["lying", "low-impact"],
    intensityTags: ["medium-intensity"],
    contraindicationTags: [...CORE_PRESSURE, "disc-herniation", "pregnancy-trimester-2", "pregnancy-trimester-3"],
    isPublished: true,
  }),
  ex({
    slug: "sit-up",
    title: "Abdominal remador (completo)",
    description:
      "Sente até o tronco vertical e desça com controle. Evite se houver dor lombar.",
    targetMuscles: ["core"],
    equipmentTags: ["bodyweight"],
    requiredCapabilityTags: ["lying"],
    intensityTags: ["medium-intensity", "spine-flexion-rotation"],
    contraindicationTags: [...SPINE_FLEX_ROT, ...CORE_PRESSURE, "pregnancy-trimester-2", "pregnancy-trimester-3"],
    isPublished: true,
  }),
  ex({
    slug: "leg-raise",
    title: "Abdominal infra (elevação de pernas)",
    description:
      "Deite de costas e eleve as pernas estendidas ou semi-flexionadas. Lombar colada ao solo.",
    targetMuscles: ["core"],
    equipmentTags: ["bodyweight"],
    requiredCapabilityTags: ["lying", "low-impact"],
    intensityTags: ["medium-intensity", "high-intra-abdominal-pressure", "deep-hip-flexion"],
    contraindicationTags: [...CORE_PRESSURE, "femoroacetabular-impingement", "disc-herniation"],
    isPublished: true,
  }),
  ex({
    slug: "bicycle-crunch",
    title: "Abdominal bicicleta",
    description:
      "Alterne cotovelo e joelho opostos em movimento de pedalada. Ritmo controlado.",
    targetMuscles: ["core"],
    equipmentTags: ["bodyweight"],
    requiredCapabilityTags: ["lying"],
    intensityTags: ["medium-intensity", "spine-flexion-rotation"],
    contraindicationTags: [...SPINE_FLEX_ROT, "pregnancy-trimester-2", "pregnancy-trimester-3"],
    isPublished: true,
  }),
  ex({
    slug: "v-up",
    title: "Abdominal canivete (V-up)",
    description:
      "Eleve tronco e pernas ao mesmo tempo tentando tocar os pés. Avançado — prefira versão unilateral se for iniciante.",
    targetMuscles: ["core"],
    equipmentTags: ["bodyweight"],
    requiredCapabilityTags: ["lying"],
    intensityTags: ["high-intensity", "high-intra-abdominal-pressure"],
    contraindicationTags: [...CORE_PRESSURE, ...SPINE_FLEX_ROT, "pregnancy-trimester-2", "pregnancy-trimester-3"],
    isPublished: true,
  }),
  ex({
    slug: "single-leg-v-up-load",
    title: "Abdominal canivete unilateral com carga",
    description:
      "Eleve uma perna e o tronco com uma garrafa. Alternar. Menos pressão que o canivete bilateral.",
    targetMuscles: ["core"],
    equipmentTags: ["bottle", "bodyweight"],
    requiredCapabilityTags: ["lying", "unilateral"],
    intensityTags: ["medium-intensity", "high-intra-abdominal-pressure"],
    contraindicationTags: [...CORE_PRESSURE, "pregnancy-trimester-2", "pregnancy-trimester-3"],
    isPublished: true,
  }),
  ex({
    slug: "butterfly-crunch",
    title: "Abdominal borboleta",
    description:
      "Solas dos pés juntas, joelhos abertos. Eleve os ombros do solo em um supra curto.",
    targetMuscles: ["core"],
    equipmentTags: ["bodyweight"],
    requiredCapabilityTags: ["lying", "low-impact"],
    intensityTags: ["low-intensity", "deep-hip-flexion"],
    contraindicationTags: ["piriformis-syndrome", "pregnancy-trimester-2", "pregnancy-trimester-3"],
    isPublished: true,
  }),
  ex({
    slug: "tuck-crunch",
    title: "Abdominal grupado (tuck crunches)",
    description:
      "Joelhos flexionados junto ao peito, eleve a cabeça e os ombros. Útil quando se evita extensão lombar.",
    targetMuscles: ["core"],
    equipmentTags: ["bodyweight"],
    requiredCapabilityTags: ["lying", "low-impact"],
    intensityTags: ["low-intensity"],
    contraindicationTags: ["pregnancy-trimester-2", "pregnancy-trimester-3"],
    isPublished: true,
  }),
  ex({
    slug: "rope-crunch",
    title: "Abdominal escalador (rope crunch)",
    description:
      "De joelhos, com elástico ancorado atrás/acima, flexione o tronco trazendo as mãos aos joelhos.",
    targetMuscles: ["core"],
    equipmentTags: ["resistance-band"],
    requiredCapabilityTags: ["lying", "seated", "low-impact"],
    intensityTags: ["medium-intensity", "spine-flexion-rotation"],
    contraindicationTags: [...SPINE_FLEX_ROT],
    isPublished: true,
  }),
  ex({
    slug: "band-crunch",
    title: "Abdominal resistido",
    description:
      "Elástico ancorado atrás da cabeça; flexione o tronco contra a resistência em amplitude curta.",
    targetMuscles: ["core"],
    equipmentTags: ["resistance-band"],
    requiredCapabilityTags: ["lying", "seated", "low-impact"],
    intensityTags: ["medium-intensity"],
    contraindicationTags: [...SPINE_FLEX_ROT, ...CORE_PRESSURE],
    isPublished: true,
  }),
  ex({
    slug: "sliding-pike",
    title: "Abdominal pike deslizante",
    description:
      "Em prancha com pés sobre toalha, deslize os pés em direção às mãos elevando o quadril.",
    targetMuscles: ["core", "shoulders"],
    equipmentTags: ["towel", "bodyweight"],
    requiredCapabilityTags: ["lying"],
    intensityTags: ["high-intensity", "wrist-extension-load", "high-intra-abdominal-pressure"],
    contraindicationTags: [...WRIST_LOAD, ...CORE_PRESSURE, ...SHOULDER_OVERHEAD],
    isPublished: true,
  }),
  ex({
    slug: "heel-touch",
    title: "Toque nos calcanhares",
    description:
      "Deite de costas com joelhos flexionados e alterne tocar os calcanhares com as mãos.",
    targetMuscles: ["core"],
    equipmentTags: ["bodyweight"],
    requiredCapabilityTags: ["lying", "low-impact"],
    intensityTags: ["low-intensity"],
    contraindicationTags: ["pregnancy-trimester-3"],
    isPublished: true,
  }),
  ex({
    slug: "russian-twist",
    title: "Giro russo (russian twist)",
    description:
      "Sentado, incline o tronco e gire o tronco de um lado para o outro. Pode segurar garrafa. Amplitude pequena.",
    targetMuscles: ["core"],
    equipmentTags: ["bodyweight", "bottle", "food-bag"],
    requiredCapabilityTags: ["seated", "lying"],
    intensityTags: ["medium-intensity", "spine-flexion-rotation"],
    contraindicationTags: [...SPINE_FLEX_ROT, "pregnancy-trimester-2", "pregnancy-trimester-3"],
    isPublished: true,
  }),
  ex({
    slug: "bird-dog",
    title: "Perdigueiro (bird-dog)",
    description:
      "Em quatro apoios, estenda o braço e a perna opostos. Faça em fases lentas se houver espasticidade ou dor.",
    targetMuscles: ["core", "back", "glutes"],
    equipmentTags: ["bodyweight"],
    requiredCapabilityTags: ["lying", "low-impact"],
    intensityTags: ["low-intensity", "wrist-extension-load"],
    contraindicationTags: [...WRIST_LOAD],
    isPublished: true,
  }),
  ex({
    slug: "hollow-body-hold",
    title: "Posição de canoa (hollow body hold)",
    description:
      "Deite de costas, lombar colada, braços e pernas levemente elevadas. Segure pouco tempo.",
    targetMuscles: ["core"],
    equipmentTags: ["bodyweight"],
    requiredCapabilityTags: ["lying", "low-impact"],
    intensityTags: ["medium-intensity", "high-intra-abdominal-pressure"],
    contraindicationTags: [...CORE_PRESSURE, "disc-herniation"],
    isPublished: true,
  }),
  ex({
    slug: "hollow-body-rock",
    title: "Balanço em canoa (hollow body rocks)",
    description:
      "Na posição de canoa, balance suavemente sem perder o contato da lombar.",
    targetMuscles: ["core"],
    equipmentTags: ["bodyweight"],
    requiredCapabilityTags: ["lying"],
    intensityTags: ["medium-intensity", "high-intra-abdominal-pressure", "spin"],
    contraindicationTags: [...CORE_PRESSURE, "labyrinthitis", "disc-herniation"],
    isPublished: true,
  }),
  ex({
    slug: "dead-bug",
    title: "Inseto morto (dead bug)",
    description:
      "Deite de costas e alterne estender braço e perna opostos mantendo a lombar no solo. Ideal para coluna neutra.",
    targetMuscles: ["core"],
    equipmentTags: ["bodyweight"],
    requiredCapabilityTags: ["lying", "low-impact"],
    intensityTags: ["low-intensity", "active-pause"],
    contraindicationTags: [],
    isPublished: true,
  }),
  ex({
    slug: "scissors",
    title: "Chute de tesoura",
    description:
      "Deite de costas e alterne as pernas em tesoura, lombar estável.",
    targetMuscles: ["core"],
    equipmentTags: ["bodyweight"],
    requiredCapabilityTags: ["lying"],
    intensityTags: ["medium-intensity", "explosive-adductors", "high-intra-abdominal-pressure"],
    contraindicationTags: [...CORE_PRESSURE, "athletic-pubalgia", "disc-herniation"],
    isPublished: true,
  }),
  ex({
    slug: "flutter-kicks",
    title: "Chute de nadador (flutter kicks)",
    description:
      "Pequenos chutes alternados com as pernas elevadas. Pare se a lombar descolar do solo.",
    targetMuscles: ["core"],
    equipmentTags: ["bodyweight"],
    requiredCapabilityTags: ["lying"],
    intensityTags: ["medium-intensity", "high-intra-abdominal-pressure"],
    contraindicationTags: [...CORE_PRESSURE, "disc-herniation"],
    isPublished: true,
  }),
  ex({
    slug: "windshield-wipers",
    title: "Limpador de para-brisa (windshield wipers)",
    description:
      "Pernas elevadas, mova-as de um lado para o outro como limpadores. Amplitude pequena.",
    targetMuscles: ["core"],
    equipmentTags: ["bodyweight"],
    requiredCapabilityTags: ["lying"],
    intensityTags: ["high-intensity", "spine-flexion-rotation"],
    contraindicationTags: [...SPINE_FLEX_ROT, ...CORE_PRESSURE],
    isPublished: true,
  }),
  ex({
    slug: "l-sit-floor",
    title: "L-sit no solo",
    description:
      "Sente com as mãos ao lado do quadril e tente elevar o corpo com as pernas estendidas. Avançado.",
    targetMuscles: ["core", "arms"],
    equipmentTags: ["bodyweight"],
    requiredCapabilityTags: ["seated"],
    intensityTags: ["high-intensity", "wrist-extension-load", "high-intra-abdominal-pressure"],
    contraindicationTags: [...WRIST_LOAD, ...CORE_PRESSURE],
    isPublished: false,
  }),
  ex({
    slug: "woodchop",
    title: "Rotação de tronco (lenhador)",
    description:
      "Com elástico ancorado alto ou baixo, puxe em diagonal cruzando o tronco. Quadril estável.",
    targetMuscles: ["core", "shoulders"],
    equipmentTags: ["resistance-band"],
    requiredCapabilityTags: ["standing", "seated", "low-impact"],
    intensityTags: ["medium-intensity", "spine-flexion-rotation"],
    contraindicationTags: [...SPINE_FLEX_ROT],
    isPublished: true,
  }),
  ex({
    slug: "pallof-press",
    title: "Press antirotação (Pallof press)",
    description:
      "Elástico ancorado ao lado; empurre as mãos à frente resistindo à rotação do tronco. Excelente para quem tem controle de tronco sentado.",
    targetMuscles: ["core"],
    equipmentTags: ["resistance-band", "chair"],
    requiredCapabilityTags: ["standing", "seated", "low-impact"],
    intensityTags: ["low-intensity", "active-pause"],
    contraindicationTags: [],
    isPublished: true,
  }),

  // --- Cardio / plyo / mobility ---
  ex({
    slug: "jumping-jack",
    title: "Polichinelo",
    description:
      "Abra e feche braços e pernas em saltos ritmados. Versão sem salto: passo lateral.",
    targetMuscles: ["full-body"],
    equipmentTags: ["bodyweight"],
    requiredCapabilityTags: ["standing"],
    intensityTags: ["medium-intensity", "high-impact", "lower-body-plyometrics", "spatial-travel"],
    contraindicationTags: [...PLYO],
    isPublished: true,
  }),
  ex({
    slug: "burpee",
    title: "Burpee",
    description:
      "Agache, leve as mãos ao chão, estenda as pernas, volte e suba. Pode eliminar o salto final.",
    targetMuscles: ["full-body"],
    equipmentTags: ["bodyweight"],
    requiredCapabilityTags: ["standing", "lying"],
    intensityTags: [
      "high-intensity",
      "high-impact",
      "lower-body-plyometrics",
      "deep-hip-flexion",
      "high-speed",
    ],
    contraindicationTags: [...PLYO, ...CORE_PRESSURE, "labyrinthitis"],
    isPublished: true,
  }),
  ex({
    slug: "sprawl",
    title: "Meio burpee (sprawl)",
    description:
      "Das mãos no chão, estenda e recolha as pernas sem o salto vertical final.",
    targetMuscles: ["full-body", "core"],
    equipmentTags: ["bodyweight"],
    requiredCapabilityTags: ["standing", "lying"],
    intensityTags: ["medium-intensity", "high-speed", "deep-hip-flexion"],
    contraindicationTags: [...PLYO, "labyrinthitis"],
    isPublished: true,
  }),
  ex({
    slug: "mountain-climber",
    title: "Escalador (mountain climber)",
    description:
      "Em prancha alta, alterne os joelhos em direção ao peito. Ritmo controlado.",
    targetMuscles: ["core", "legs", "full-body"],
    equipmentTags: ["bodyweight"],
    requiredCapabilityTags: ["lying"],
    intensityTags: [
      "high-intensity",
      "high-speed",
      "forefoot-impact",
      "wrist-extension-load",
      "high-intra-abdominal-pressure",
    ],
    contraindicationTags: [...WRIST_LOAD, "plantar-fasciitis", ...CORE_PRESSURE, ...PLYO],
    isPublished: true,
  }),
  ex({
    slug: "cross-mountain-climber",
    title: "Escalador cruzado",
    description:
      "Como o escalador, levando o joelho ao cotovelo oposto.",
    targetMuscles: ["core", "legs"],
    equipmentTags: ["bodyweight"],
    requiredCapabilityTags: ["lying"],
    intensityTags: ["high-intensity", "spine-flexion-rotation", "wrist-extension-load", "high-speed"],
    contraindicationTags: [...SPINE_FLEX_ROT, ...WRIST_LOAD, ...PLYO],
    isPublished: true,
  }),
  ex({
    slug: "sliding-mountain-climber",
    title: "Escalador deslizante",
    description:
      "Pés sobre toalha em piso liso; deslize um pé de cada vez em direção ao peito.",
    targetMuscles: ["core", "legs"],
    equipmentTags: ["towel", "bodyweight"],
    requiredCapabilityTags: ["lying", "low-impact"],
    intensityTags: ["medium-intensity", "wrist-extension-load"],
    contraindicationTags: [...WRIST_LOAD, ...CORE_PRESSURE],
    isPublished: true,
  }),
  ex({
    slug: "high-knees",
    title: "Corrida estacionária (high knees)",
    description:
      "Eleve os joelhos alternadamente no lugar. Pode ser marcha sem salto.",
    targetMuscles: ["legs", "full-body"],
    equipmentTags: ["bodyweight"],
    requiredCapabilityTags: ["standing"],
    intensityTags: ["medium-intensity", "forefoot-impact", "high-speed"],
    contraindicationTags: ["plantar-fasciitis", ...PLYO],
    isPublished: true,
  }),
  ex({
    slug: "butt-kicks",
    title: "Chutes traseiros (butt kicks)",
    description:
      "Leve os calcanhares aos glúteos alternadamente, no lugar.",
    targetMuscles: ["legs"],
    equipmentTags: ["bodyweight"],
    requiredCapabilityTags: ["standing"],
    intensityTags: ["medium-intensity", "forefoot-impact", "high-speed"],
    contraindicationTags: ["plantar-fasciitis", "chronic-muscle-strain", ...PLYO],
    isPublished: true,
  }),
  ex({
    slug: "skater-jump",
    title: "Patinação lateral (skater jumps)",
    description:
      "Salte lateralmente de um pé para o outro como na patinação. Aterrise macio.",
    targetMuscles: ["legs", "glutes"],
    equipmentTags: ["bodyweight"],
    requiredCapabilityTags: ["standing", "unilateral"],
    intensityTags: [
      "high-intensity",
      "lower-body-plyometrics",
      "knee-lateral-force",
      "spatial-travel",
      "distance-jump",
    ],
    contraindicationTags: [...PLYO, ...KNEE_LATERAL, "visual-impairment"],
    isPublished: true,
  }),
  ex({
    slug: "star-jump",
    title: "Salto estrela",
    description:
      "Salte abrindo braços e pernas em estrela e feche na aterrissagem.",
    targetMuscles: ["full-body"],
    equipmentTags: ["bodyweight"],
    requiredCapabilityTags: ["standing"],
    intensityTags: ["high-intensity", "high-impact", "lower-body-plyometrics"],
    contraindicationTags: [...PLYO],
    isPublished: true,
  }),
  ex({
    slug: "broad-jump",
    title: "Salto em distância parado (broad jumps)",
    description:
      "Salte à frente com os dois pés e aterrise com joelhos flexionados. Espaço livre à frente.",
    targetMuscles: ["legs", "glutes", "full-body"],
    equipmentTags: ["bodyweight"],
    requiredCapabilityTags: ["standing"],
    intensityTags: ["high-intensity", "high-impact", "lower-body-plyometrics", "distance-jump", "spatial-travel"],
    contraindicationTags: [...PLYO, "visual-impairment"],
    isPublished: true,
  }),
  ex({
    slug: "tuck-jump",
    title: "Salto com joelhos no peito (tuck jumps)",
    description:
      "Salte trazendo os joelhos ao peito e aterrise macio.",
    targetMuscles: ["legs", "core", "full-body"],
    equipmentTags: ["bodyweight"],
    requiredCapabilityTags: ["standing"],
    intensityTags: ["high-intensity", "high-impact", "lower-body-plyometrics", "deep-hip-flexion"],
    contraindicationTags: [...PLYO],
    isPublished: true,
  }),
  ex({
    slug: "inchworm",
    title: "Caminhada com as mãos (inchworm)",
    description:
      "Da posição em pé, leve as mãos ao chão e caminhe para uma prancha, depois volte os pés.",
    targetMuscles: ["full-body", "core", "shoulders"],
    equipmentTags: ["bodyweight"],
    requiredCapabilityTags: ["standing", "lying"],
    intensityTags: ["medium-intensity", "wrist-extension-load", "max-range-stretch"],
    contraindicationTags: [...WRIST_LOAD, "chronic-muscle-strain", "labyrinthitis"],
    isPublished: true,
  }),
  ex({
    slug: "bear-crawl",
    title: "Caminhada do urso (bear crawl)",
    description:
      "Em quatro apoios com joelhos elevados, caminhe para frente. Passos curtos.",
    targetMuscles: ["full-body", "core", "shoulders"],
    equipmentTags: ["bodyweight"],
    requiredCapabilityTags: ["lying"],
    intensityTags: ["medium-intensity", "wrist-extension-load", "spatial-travel"],
    contraindicationTags: [...WRIST_LOAD, "visual-impairment", "pregnancy-trimester-3"],
    isPublished: true,
  }),
  ex({
    slug: "crab-walk",
    title: "Caminhada do caranguejo (crab walk)",
    description:
      "Sentado com mãos e pés no solo, elevando o quadril, caminhe para frente ou trás.",
    targetMuscles: ["arms", "core", "glutes"],
    equipmentTags: ["bodyweight"],
    requiredCapabilityTags: ["seated", "lying"],
    intensityTags: ["medium-intensity", "wrist-extension-load", "spatial-travel"],
    contraindicationTags: [...WRIST_LOAD, "shoulder-instability", "visual-impairment"],
    isPublished: true,
  }),
  ex({
    slug: "crab-reach",
    title: "Alcance do caranguejo (crab reach)",
    description:
      "Na posição de caranguejo, eleve um braço cruzando o tronco em direção ao teto.",
    targetMuscles: ["core", "shoulders", "arms"],
    equipmentTags: ["bodyweight"],
    requiredCapabilityTags: ["lying", "seated"],
    intensityTags: ["medium-intensity", "wrist-extension-load", "spine-flexion-rotation"],
    contraindicationTags: [...WRIST_LOAD, ...SPINE_FLEX_ROT],
    isPublished: true,
  }),
  ex({
    slug: "scorpion-reach",
    title: "Alcance do escorpião (scorpion reach)",
    description:
      "De bruços, leve um pé em direção ao lado oposto abrindo o quadril. Amplitude suave.",
    targetMuscles: ["back", "glutes", "core"],
    equipmentTags: ["bodyweight"],
    requiredCapabilityTags: ["lying", "low-impact"],
    intensityTags: ["low-intensity", "prone-position", "spine-hyperextension", "deep-hip-flexion"],
    contraindicationTags: [...SPINE_HYPER, "piriformis-syndrome", "pregnancy-trimester-2", "pregnancy-trimester-3"],
    isPublished: true,
  }),
  ex({
    slug: "shoulder-dislocate-broom",
    title: "Mobilidade de ombros com deslocamento",
    description:
      "Segure um cabo de vassoura com pegada larga e passe-o da frente para trás do corpo com cotovelos estendidos. Sem forçar.",
    targetMuscles: ["shoulders"],
    equipmentTags: ["broomstick"],
    requiredCapabilityTags: ["standing", "seated", "low-impact"],
    intensityTags: ["low-intensity", "wide-arm-tension", "active-pause"],
    contraindicationTags: ["shoulder-instability", "rotator-cuff-injury", "slap-tear", "ac-joint-injury"],
    isPublished: true,
  }),

  // --- Educador extras: seated / pause / inclusive ---
  ex({
    slug: "seated-arm-raise-pause",
    title: "Elevação de braços sentada (pausa ativa)",
    description:
      "Sente-se com a coluna alongada. Eleve os braços até a linha dos ombros e desça com calma. Cerca de um minuto, sem prender o ar.",
    targetMuscles: ["shoulders", "arms"],
    equipmentTags: ["chair", "bodyweight"],
    requiredCapabilityTags: ["seated"],
    intensityTags: ["active-pause", "low-intensity"],
    contraindicationTags: [],
    isPublished: true,
  }),
  ex({
    slug: "seated-towel-row",
    title: "Remada com toalha (sentada)",
    description:
      "Sente-se e puxe uma toalha em direção ao tronco, aproximando as omoplatas. Pode enfatizar um lado.",
    targetMuscles: ["back", "arms"],
    equipmentTags: ["towel", "chair"],
    requiredCapabilityTags: ["seated", "unilateral", "low-impact"],
    intensityTags: ["low-intensity", "active-pause"],
    contraindicationTags: [],
    isPublished: true,
  }),
  ex({
    slug: "seated-bottle-rotation",
    title: "Rotação de tronco sentada com garrafa",
    description:
      "Sente-se e gire o tronco com amplitude pequena segurando uma garrafa. Preferir Pallof se houver histórico de hérnia.",
    targetMuscles: ["core"],
    equipmentTags: ["bottle", "chair"],
    requiredCapabilityTags: ["seated", "low-impact"],
    intensityTags: ["active-pause", "low-intensity", "spine-flexion-rotation"],
    contraindicationTags: [...SPINE_FLEX_ROT],
    isPublished: true,
  }),
  ex({
    slug: "chair-supported-squat",
    title: "Agachamento apoiado na cadeira",
    description:
      "À frente de uma cadeira, desça até tocar o assento de leve e suba. Amplitude confortável.",
    targetMuscles: ["legs", "glutes"],
    equipmentTags: ["chair", "bodyweight"],
    requiredCapabilityTags: ["standing", "low-impact"],
    intensityTags: ["low-intensity", "deep-knee-flexion"],
    contraindicationTags: ["chondromalacia", "torn-pcl", "knee-osteoarthritis"],
    isPublished: true,
  }),
  ex({
    slug: "knee-plank",
    title: "Prancha de joelhos",
    description:
      "Antebraços e joelhos no solo, tronco alinhado. Segure pouco e descanse.",
    targetMuscles: ["core"],
    equipmentTags: ["bodyweight"],
    requiredCapabilityTags: ["lying", "low-impact"],
    intensityTags: ["low-intensity", "forearm-plank-hard", "high-intra-abdominal-pressure"],
    contraindicationTags: [...CORE_PRESSURE, "olecranon-bursitis"],
    isPublished: true,
  }),
  ex({
    slug: "seated-shoulder-press-bottle",
    title: "Desenvolvimento de ombros sentado com garrafa",
    description:
      "Sentado, empurre garrafas acima da cabeça sem arquear a lombar. Pare abaixo de 90 graus se houver dor no ombro.",
    targetMuscles: ["shoulders", "arms"],
    equipmentTags: ["bottle", "chair"],
    requiredCapabilityTags: ["seated", "low-impact"],
    intensityTags: ["low-intensity", "overhead-press"],
    contraindicationTags: [...SHOULDER_OVERHEAD],
    isPublished: true,
  }),
  ex({
    slug: "wall-angel-pause",
    title: "Anjo na parede (pausa ativa)",
    description:
      "Costas e braços na parede; deslize os braços para cima e para baixo mantendo contato. Movimento lento.",
    targetMuscles: ["shoulders", "back"],
    equipmentTags: ["wall", "bodyweight"],
    requiredCapabilityTags: ["standing", "seated", "low-impact"],
    intensityTags: ["active-pause", "low-intensity"],
    contraindicationTags: ["rotator-cuff-injury", "subacromial-bursitis"],
    isPublished: true,
  }),
  ex({
    slug: "seated-march",
    title: "Marcha sentada",
    description:
      "Sente-se e alterne elevar os joelhos como uma marcha. Útil para quem usa cadeira ou evita impacto.",
    targetMuscles: ["legs", "core"],
    equipmentTags: ["chair", "bodyweight"],
    requiredCapabilityTags: ["seated", "low-impact"],
    intensityTags: ["active-pause", "low-intensity"],
    contraindicationTags: [],
    isPublished: true,
  }),
];
