import { meal, type SeedMeal } from "./meal-seed-types";

/** Jantar — foco em digestão leve e aproveitamento. */
export const MEAL_SEED_DINNER: SeedMeal[] = [
  meal({
    slug: "blended-bean-soup-pasta",
    title: "Sopa de feijão batida com macarrão",
    description:
      "Feijão batido com macarrão e sobras de legumes. Contém glúten se o macarrão for de trigo.",
    mealSlot: "dinner",
    containsTags: ["gluten"],
    dietCompatibleTags: ["vegan", "vegetarian", "low-cost"],
    ingredients: [
      { item: "feijão cozido", qty: "2 conchas" },
      { item: "macarrão", qty: "1/2 xícara" },
      { item: "legumes", qty: "1 xícara" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "light-caldo-verde-chicken",
    title: "Caldo verde leve com frango",
    description:
      "Caldo verde sem embutidos pesados: frango desfiado, batata e couve.",
    mealSlot: "dinner",
    containsTags: ["meat"],
    dietCompatibleTags: ["low-cost"],
    ingredients: [
      { item: "frango desfiado", qty: "1/2 xícara" },
      { item: "batata", qty: "2 unidades" },
      { item: "couve", qty: "1 xícara" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "pumpkin-ginger-chicken-soup",
    title: "Caldo de abóbora com gengibre e frango",
    description: "Creme de abóbora com gengibre e frango desfiado.",
    mealSlot: "dinner",
    containsTags: ["meat"],
    dietCompatibleTags: ["low-cost"],
    ingredients: [
      { item: "abóbora", qty: "2 xícaras" },
      { item: "gengibre", qty: "a gosto" },
      { item: "frango desfiado", qty: "1/2 xícara" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "cassava-cream-ground-beef",
    title: "Creme de mandioca com carne moída",
    description: "Creme de mandioca com carne moída.",
    mealSlot: "dinner",
    containsTags: ["meat"],
    dietCompatibleTags: ["low-cost"],
    ingredients: [
      { item: "mandioca", qty: "2 xícaras" },
      { item: "carne moída", qty: "1/2 xícara" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "lentil-carrot-potato-soup",
    title: "Sopa de lentilha com cenoura e batata",
    description: "Sopa de lentilha com raízes. Vegana.",
    mealSlot: "dinner",
    containsTags: [],
    dietCompatibleTags: ["vegan", "vegetarian", "low-cost"],
    ingredients: [
      { item: "lentilha", qty: "1 xícara" },
      { item: "cenoura e batata", qty: "1 xícara" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "leafy-salad-boiled-egg",
    title: "Salada de folhas com ovo cozido",
    description: "Folhas, ovo cozido, tomate e cebola.",
    mealSlot: "dinner",
    containsTags: ["egg"],
    dietCompatibleTags: ["vegetarian", "low-cost"],
    ingredients: [
      { item: "folhas verdes", qty: "2 xícaras" },
      { item: "ovo cozido", qty: "1 a 2 unidades" },
      { item: "tomate e cebola", qty: "a gosto" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "leftover-chicken-veggie-salad",
    title: "Salada completa com frango e legumes",
    description: "Tiras de frango de sobra com legumes cozidos.",
    mealSlot: "dinner",
    containsTags: ["meat"],
    dietCompatibleTags: ["low-cost"],
    ingredients: [
      { item: "frango em tiras", qty: "1/2 xícara" },
      { item: "legumes cozidos", qty: "1 xícara" },
      { item: "folhas", qty: "a gosto" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "kale-wrap-ground-beef",
    title: "Wrap de couve com carne moída",
    description: "Folha grande de couve crua recheada com carne moída.",
    mealSlot: "dinner",
    containsTags: ["meat"],
    dietCompatibleTags: ["low-cost"],
    ingredients: [
      { item: "folha de couve", qty: "2 unidades" },
      { item: "carne moída", qty: "1/2 xícara" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "kale-wrap-chicken-ricotta",
    title: "Wrap de couve com frango e ricota",
    description:
      "Couve recheada com frango, cenoura e ricota. Contém carne e lactose.",
    mealSlot: "dinner",
    containsTags: ["meat", "lactose"],
    dietCompatibleTags: ["low-cost"],
    ingredients: [
      { item: "folha de couve", qty: "2 unidades" },
      { item: "frango", qty: "1/2 xícara" },
      { item: "cenoura", qty: "2 colheres de sopa" },
      { item: "ricota", qty: "2 colheres de sopa" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "scrambled-eggs-toast-dinner",
    title: "Ovos mexidos com pão torrado",
    description:
      "Ovos mexidos com tomate, cebola, pimentão e pão torrado. Contém ovo e glúten.",
    mealSlot: "dinner",
    containsTags: ["egg", "gluten"],
    dietCompatibleTags: ["vegetarian", "low-cost"],
    ingredients: [
      { item: "ovos", qty: "2 unidades" },
      { item: "tomate, cebola e pimentão", qty: "a gosto" },
      { item: "pão torrado", qty: "1 fatia" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "simple-shakshuka",
    title: "Ovos no molho de tomate",
    description: "Ovos pochê ou cozidos no molho de tomate (shakshuka simples).",
    mealSlot: "dinner",
    containsTags: ["egg"],
    dietCompatibleTags: ["vegetarian", "low-cost"],
    ingredients: [
      { item: "ovos", qty: "2 unidades" },
      { item: "molho de tomate", qty: "1 xícara" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "chayote-or-zucchini-souffle",
    title: "Suflê de chuchu ou abobrinha",
    description: "Legumes misturados com ovos batidos e assados.",
    mealSlot: "dinner",
    containsTags: ["egg"],
    dietCompatibleTags: ["vegetarian", "low-cost"],
    ingredients: [
      { item: "chuchu ou abobrinha", qty: "2 xícaras" },
      { item: "ovos", qty: "3 unidades" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "homemade-beef-burger-salad",
    title: "Hambúrguer caseiro com salada",
    description:
      "Hambúrguer só com carne e temperos, no prato com salada grande (sem pão).",
    mealSlot: "dinner",
    containsTags: ["meat"],
    dietCompatibleTags: ["low-cost"],
    ingredients: [
      { item: "carne moída", qty: "120 g" },
      { item: "salada grande", qty: "a gosto" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "homemade-chicken-burger-mash",
    title: "Hambúrguer de frango com purê",
    description:
      "Frango processado com aveia e cebola, com purê de batata. Contém carne e glúten.",
    mealSlot: "dinner",
    containsTags: ["meat", "gluten"],
    dietCompatibleTags: ["low-cost"],
    ingredients: [
      { item: "frango", qty: "120 g" },
      { item: "aveia", qty: "1 colher de sopa" },
      { item: "purê de batata", qty: "1/2 xícara" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "tortilla-skillet-pizza",
    title: "Pizza de frigideira na tortilha",
    description:
      "Tortilha com molho de tomate e queijo branco. Contém lactose; glúten se a tortilha for de trigo.",
    mealSlot: "dinner",
    containsTags: ["lactose", "gluten"],
    dietCompatibleTags: ["vegetarian", "low-cost"],
    ingredients: [
      { item: "tortilha", qty: "1 unidade", alt: "tortilha de milho" },
      { item: "molho de tomate", qty: "2 colheres de sopa" },
      { item: "queijo branco", qty: "2 fatias" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "shredded-chicken-spinach-rice",
    title: "Frango com espinafre e arroz",
    description: "Frango desfiado refogado com espinafre e arroz.",
    mealSlot: "dinner",
    containsTags: ["meat"],
    dietCompatibleTags: ["low-cost"],
    ingredients: [
      { item: "frango desfiado", qty: "1 xícara" },
      { item: "espinafre", qty: "1 xícara" },
      { item: "arroz", qty: "3 colheres de sopa" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "pork-strips-warm-cabbage-salad",
    title: "Iscas de lombo com salada quente",
    description: "Lombo com repolho e cenoura refogados.",
    mealSlot: "dinner",
    containsTags: ["meat"],
    dietCompatibleTags: ["low-cost"],
    ingredients: [
      { item: "lombo de porco", qty: "1 porção" },
      { item: "repolho e cenoura", qty: "2 xícaras" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "baked-tomato-egg",
    title: "Tomate recheado com ovo assado",
    description: "Tomate sem miolo, recheado com ovo e assado.",
    mealSlot: "dinner",
    containsTags: ["egg"],
    dietCompatibleTags: ["vegetarian", "low-cost"],
    ingredients: [
      { item: "tomate grande", qty: "1 unidade" },
      { item: "ovo", qty: "1 unidade" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "cabbage-apple-yogurt-chicken-salad",
    title: "Salada de repolho, maçã e frango",
    description:
      "Repolho roxo e branco, maçã, molho de iogurte e frango. Contém carne e lactose.",
    mealSlot: "dinner",
    containsTags: ["meat", "lactose"],
    dietCompatibleTags: ["low-cost"],
    ingredients: [
      { item: "repolho", qty: "2 xícaras" },
      { item: "maçã", qty: "1/2 unidade" },
      { item: "iogurte natural", qty: "2 colheres de sopa" },
      { item: "frango em cubos", qty: "1/2 xícara" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "vegetable-only-soup",
    title: "Sopa só de legumes",
    description:
      "Batata, cenoura, abóbora e folhas em caldo leve. Opção vegana sem glúten. (extra Nutri)",
    mealSlot: "dinner",
    containsTags: [],
    dietCompatibleTags: ["vegan", "vegetarian", "low-cost"],
    ingredients: [
      { item: "batata, cenoura e abóbora", qty: "3 xícaras" },
      { item: "folhas", qty: "1 xícara" },
      { item: "água", qty: "o suficiente" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "beans-pumpkin-puree-plate",
    title: "Feijão com purê de abóbora",
    description:
      "Concha de feijão com purê de abóbora. Jantar vegano denso e barato. (extra Nutri)",
    mealSlot: "dinner",
    containsTags: [],
    dietCompatibleTags: ["vegan", "vegetarian", "low-cost"],
    ingredients: [
      { item: "feijão", qty: "1 concha" },
      { item: "purê de abóbora", qty: "1 xícara" },
    ],
    isPublished: true,
  }),
];
