import { meal, type SeedMeal } from "./meal-seed-types";

/** Lanches da manhã e da tarde — ambos usam meal_slot snack. */
export const MEAL_SEED_SNACKS: SeedMeal[] = [
  meal({
    slug: "seasonal-fruit",
    title: "Fruta da estação",
    description: "Banana, maçã, laranja, melancia ou melão in natura.",
    mealSlot: "snack",
    containsTags: [],
    dietCompatibleTags: ["vegan", "vegetarian", "low-cost"],
    ingredients: [{ item: "fruta da estação", qty: "1 porção" }],
    isPublished: true,
  }),
  meal({
    slug: "mashed-banana-oats",
    title: "Banana amassada com aveia",
    description: "Amasse a banana com uma colher de aveia. Contém glúten.",
    mealSlot: "snack",
    containsTags: ["gluten"],
    dietCompatibleTags: ["vegan", "vegetarian", "low-cost"],
    ingredients: [
      { item: "banana", qty: "1 unidade" },
      { item: "aveia em flocos", qty: "1 colher de sopa" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "apple-slices-peanut-butter",
    title: "Maçã com pasta de amendoim",
    description: "Fatias de maçã com pasta de amendoim. Contém amendoim.",
    mealSlot: "snack",
    containsTags: ["peanut"],
    dietCompatibleTags: ["vegan", "vegetarian", "low-cost"],
    ingredients: [
      { item: "maçã", qty: "1 unidade" },
      { item: "pasta de amendoim", qty: "1 colher de sopa" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "yogurt-chia-flax",
    title: "Iogurte natural com chia ou linhaça",
    description: "Iogurte natural com sementes. Contém lactose.",
    mealSlot: "snack",
    containsTags: ["lactose"],
    dietCompatibleTags: ["vegetarian", "low-cost"],
    ingredients: [
      { item: "iogurte natural", qty: "1 pote" },
      { item: "chia ou linhaça", qty: "1 colher de chá" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "yogurt-oat-bran",
    title: "Iogurte natural com farelo de aveia",
    description: "Iogurte com farelo de aveia. Contém lactose e glúten.",
    mealSlot: "snack",
    containsTags: ["lactose", "gluten"],
    dietCompatibleTags: ["vegetarian", "low-cost"],
    ingredients: [
      { item: "iogurte natural", qty: "1 pote" },
      { item: "farelo de aveia", qty: "1 colher de sopa" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "papaya-pumpkin-seeds",
    title: "Mamão com sementes de abóbora",
    description: "Meio mamão papaia com sementes de abóbora torradas.",
    mealSlot: "snack",
    containsTags: [],
    dietCompatibleTags: ["vegan", "vegetarian", "low-cost"],
    ingredients: [
      { item: "mamão papaia", qty: "1/2 unidade" },
      { item: "sementes de abóbora torradas", qty: "1 colher de sopa" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "homemade-toasted-seed-mix",
    title: "Mix de sementes torradas caseiras",
    description: "Sementes de abóbora e melão torradas em casa.",
    mealSlot: "snack",
    containsTags: [],
    dietCompatibleTags: ["vegan", "vegetarian", "low-cost"],
    ingredients: [
      { item: "sementes de abóbora", qty: "2 colheres de sopa" },
      { item: "sementes de melão", qty: "1 colher de sopa" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "boiled-egg-oregano",
    title: "Ovo cozido com orégano",
    description: "Ovo cozido com sal e orégano.",
    mealSlot: "snack",
    containsTags: ["egg"],
    dietCompatibleTags: ["vegetarian", "low-cost"],
    ingredients: [
      { item: "ovo cozido", qty: "1 unidade" },
      { item: "orégano", qty: "a gosto" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "quail-eggs-olive-oil",
    title: "Ovos de codorna com azeite",
    description: "Ovos de codorna cozidos com fio de azeite.",
    mealSlot: "snack",
    containsTags: ["egg"],
    dietCompatibleTags: ["vegetarian", "low-cost"],
    ingredients: [
      { item: "ovos de codorna", qty: "4 a 6 unidades" },
      { item: "azeite", qty: "1 fio" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "cold-sweet-potato-chunks",
    title: "Pedacos de batata-doce fria",
    description: "Batata-doce cozida resfriada, em pedaços.",
    mealSlot: "snack",
    containsTags: [],
    dietCompatibleTags: ["vegan", "vegetarian", "low-cost"],
    ingredients: [{ item: "batata-doce cozida", qty: "1 porção" }],
    isPublished: true,
  }),
  meal({
    slug: "rice-cake-homemade-jam",
    title: "Biscoito de arroz com geleia caseira",
    description:
      "Biscoito de arroz com geleia de frutas sem açúcar feita em casa.",
    mealSlot: "snack",
    containsTags: [],
    dietCompatibleTags: ["vegan", "vegetarian", "low-cost"],
    ingredients: [
      { item: "biscoito de arroz", qty: "2 unidades" },
      { item: "geleia de frutas sem açúcar", qty: "1 colher de sopa" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "raw-carrot-sticks",
    title: "Cenoura crua em palitos",
    description: "Cenoura cortada em palitos para lanchar.",
    mealSlot: "snack",
    containsTags: [],
    dietCompatibleTags: ["vegan", "vegetarian", "low-cost"],
    ingredients: [{ item: "cenoura", qty: "1 unidade" }],
    isPublished: true,
  }),
  meal({
    slug: "roasted-unsalted-peanuts",
    title: "Amendoim torrado sem sal",
    description: "Porção pequena de amendoim torrado sem pele e sem sal.",
    mealSlot: "snack",
    containsTags: ["peanut"],
    dietCompatibleTags: ["vegan", "vegetarian", "low-cost"],
    ingredients: [{ item: "amendoim torrado sem sal", qty: "1 punhado" }],
    isPublished: true,
  }),
  meal({
    slug: "stovetop-popcorn",
    title: "Pipoca caseira na panela",
    description: "Pipoca feita na panela com fio de óleo.",
    mealSlot: "snack",
    containsTags: [],
    dietCompatibleTags: ["vegan", "vegetarian", "low-cost"],
    ingredients: [
      { item: "milho de pipoca", qty: "3 colheres de sopa" },
      { item: "óleo", qty: "1 fio" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "mug-cake-banana-cocoa",
    title: "Bolo de caneca de banana e cacau",
    description:
      "Misture banana, ovo, aveia, cacau e fermento. Micro-ondas. Contém glúten e ovo.",
    mealSlot: "snack",
    containsTags: ["gluten", "egg"],
    dietCompatibleTags: ["vegetarian", "low-cost"],
    ingredients: [
      { item: "banana", qty: "1/2 unidade" },
      { item: "ovo", qty: "1 unidade" },
      { item: "aveia", qty: "2 colheres de sopa" },
      { item: "cacau em pó", qty: "1 colher de chá" },
      { item: "fermento", qty: "1 pitada" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "mug-cake-apple-cinnamon",
    title: "Bolo de caneca de maçã com canela",
    description:
      "Maçã, ovo, aveia, canela e fermento no micro-ondas. Contém glúten e ovo.",
    mealSlot: "snack",
    containsTags: ["gluten", "egg"],
    dietCompatibleTags: ["vegetarian", "low-cost"],
    ingredients: [
      { item: "maçã ralada", qty: "1/2 unidade" },
      { item: "ovo", qty: "1 unidade" },
      { item: "aveia", qty: "2 colheres de sopa" },
      { item: "canela", qty: "a gosto" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "whole-bread-ricotta-carrot",
    title: "Sanduíche de ricota e cenoura",
    description:
      "Pão de forma integral com pasta de ricota e cenoura. Contém glúten e lactose.",
    mealSlot: "snack",
    containsTags: ["gluten", "lactose"],
    dietCompatibleTags: ["vegetarian", "low-cost"],
    ingredients: [
      { item: "pão de forma integral", qty: "2 fatias" },
      { item: "ricota", qty: "2 colheres de sopa" },
      { item: "cenoura ralada", qty: "2 colheres de sopa" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "leftover-chicken-sandwich",
    title: "Sanduíche natural de frango",
    description:
      "Pão com frango desfiado de sobra do almoço. Contém glúten e carne.",
    mealSlot: "snack",
    containsTags: ["gluten", "meat"],
    dietCompatibleTags: ["low-cost"],
    ingredients: [
      { item: "pão", qty: "2 fatias" },
      { item: "frango desfiado", qty: "3 colheres de sopa" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "skillet-cheese-bread",
    title: "Pão de queijo de frigideira",
    description:
      "Goma, ovo e queijo ralado na frigideira. Contém ovo e lactose.",
    mealSlot: "snack",
    containsTags: ["egg", "lactose"],
    dietCompatibleTags: ["vegetarian", "low-cost"],
    ingredients: [
      { item: "goma de tapioca", qty: "3 colheres de sopa" },
      { item: "ovo", qty: "1 unidade" },
      { item: "queijo ralado", qty: "2 colheres de sopa" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "stale-bread-toast-oregano",
    title: "Torradas de pão amanhecido",
    description:
      "Pão amanhecido tostado com azeite e orégano. Contém glúten.",
    mealSlot: "snack",
    containsTags: ["gluten"],
    dietCompatibleTags: ["vegan", "vegetarian", "low-cost"],
    ingredients: [
      { item: "pão amanhecido", qty: "2 fatias" },
      { item: "azeite", qty: "1 fio" },
      { item: "orégano", qty: "a gosto" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "rice-cake-peanut-butter",
    title: "Biscoito de arroz com pasta de amendoim",
    description: "Biscoito de arroz com pasta de amendoim. Contém amendoim.",
    mealSlot: "snack",
    containsTags: ["peanut"],
    dietCompatibleTags: ["vegan", "vegetarian", "low-cost"],
    ingredients: [
      { item: "biscoito de arroz", qty: "2 unidades" },
      { item: "pasta de amendoim integral", qty: "1 colher de sopa" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "fruit-salad-honey",
    title: "Salada de frutas com mel",
    description:
      "Frutas picadas com fio de mel. Não é vegano (mel).",
    mealSlot: "snack",
    containsTags: [],
    dietCompatibleTags: ["vegetarian", "low-cost"],
    ingredients: [
      { item: "frutas picadas", qty: "1 xícara" },
      { item: "mel", qty: "1 fio", alt: "sem mel (versão vegana)" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "frozen-banana-cocoa-smoothie",
    title: "Smoothie de banana e cacau",
    description:
      "Banana congelada batida com cacau e água ou leite. Com leite: lactose.",
    mealSlot: "snack",
    containsTags: [],
    dietCompatibleTags: ["vegan", "vegetarian", "low-cost"],
    ingredients: [
      { item: "banana congelada", qty: "1 unidade" },
      { item: "cacau em pó", qty: "1 colher de chá" },
      { item: "água ou leite", qty: "150 ml", alt: "água (sem lactose)" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "veggie-sticks-hummus",
    title: "Palitos de legumes com homus",
    description: "Pepino e cenoura com pasta de grão-de-bico.",
    mealSlot: "snack",
    containsTags: [],
    dietCompatibleTags: ["vegan", "vegetarian", "low-cost"],
    ingredients: [
      { item: "pepino e cenoura", qty: "1 porção" },
      { item: "homus de grão-de-bico", qty: "3 colheres de sopa" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "veggie-sticks-ricotta-dip",
    title: "Palitos de legumes com creme de ricota",
    description: "Legumes em palito com ricota temperada. Contém lactose.",
    mealSlot: "snack",
    containsTags: ["lactose"],
    dietCompatibleTags: ["vegetarian", "low-cost"],
    ingredients: [
      { item: "legumes em palito", qty: "1 porção" },
      { item: "ricota temperada", qty: "3 colheres de sopa" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "savory-oat-porridge-egg",
    title: "Mingau de aveia salgado com ovo",
    description:
      "Aveia com água, sal, azeite e ovo mexido. Contém glúten e ovo.",
    mealSlot: "snack",
    containsTags: ["gluten", "egg"],
    dietCompatibleTags: ["vegetarian", "low-cost"],
    ingredients: [
      { item: "aveia", qty: "3 colheres de sopa" },
      { item: "água", qty: "200 ml" },
      { item: "ovo", qty: "1 unidade" },
      { item: "azeite", qty: "1 fio" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "thin-tapioca-white-cheese",
    title: "Tapioca com queijo branco",
    description: "Tapioca fina com queijo branco derretido. Contém lactose.",
    mealSlot: "snack",
    containsTags: ["lactose"],
    dietCompatibleTags: ["vegetarian", "low-cost"],
    ingredients: [
      { item: "goma de tapioca", qty: "3 colheres de sopa" },
      { item: "queijo branco", qty: "1 fatia" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "sunflower-peanut-handful",
    title: "Sementes de girassol e amendoim",
    description: "Punhado misto de sementes e amendoim. Contém amendoim.",
    mealSlot: "snack",
    containsTags: ["peanut"],
    dietCompatibleTags: ["vegan", "vegetarian", "low-cost"],
    ingredients: [
      { item: "sementes de girassol", qty: "1 colher de sopa" },
      { item: "amendoim", qty: "1 colher de sopa" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "corn-couscous-warm-milk",
    title: "Cuscuz de milho com leite morno",
    description:
      "Cuscuz levemente umedecido com leite morno. Contém lactose. (também serve no jantar leve)",
    mealSlot: "snack",
    containsTags: ["lactose"],
    dietCompatibleTags: ["vegetarian", "low-cost"],
    ingredients: [
      { item: "flocão de milho", qty: "4 colheres de sopa" },
      { item: "leite morno", qty: "100 ml", alt: "bebida vegetal" },
    ],
    isPublished: true,
  }),
];
