import { meal, type SeedMeal } from "./meal-seed-types";

/** Almoço — Nutricionista. */
export const MEAL_SEED_LUNCH: SeedMeal[] = [
  meal({
    slug: "rice-beans-grilled-chicken-salad",
    title: "Arroz, feijão, frango grelhado e salada",
    description:
      "Arroz, feijão carioca, peito de frango grelhado e salada de alface e tomate.",
    mealSlot: "lunch",
    containsTags: ["meat"],
    dietCompatibleTags: ["low-cost"],
    ingredients: [
      { item: "arroz cozido", qty: "4 colheres de sopa" },
      { item: "feijão carioca", qty: "1 concha" },
      { item: "peito de frango grelhado", qty: "1 filé" },
      { item: "alface e tomate", qty: "a gosto" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "rice-black-beans-liver-pumpkin",
    title: "Arroz, feijão preto, fígado e purê de abóbora",
    description:
      "Iscas de fígado acebolado (rico em ferro e acessível) com purê de abóbora.",
    mealSlot: "lunch",
    containsTags: ["meat"],
    dietCompatibleTags: ["low-cost"],
    ingredients: [
      { item: "arroz", qty: "4 colheres de sopa" },
      { item: "feijão preto", qty: "1 concha" },
      { item: "fígado acebolado", qty: "1 porção" },
      { item: "purê de abóbora", qty: "3 colheres de sopa" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "rice-beans-ground-beef-chayote",
    title: "Arroz, feijão e carne moída com chuchu",
    description: "Carne moída refogada com chuchu e cenoura.",
    mealSlot: "lunch",
    containsTags: ["meat"],
    dietCompatibleTags: ["low-cost"],
    ingredients: [
      { item: "arroz", qty: "4 colheres de sopa" },
      { item: "feijão", qty: "1 concha" },
      { item: "carne moída", qty: "1 xícara" },
      { item: "chuchu e cenoura", qty: "1 xícara" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "rice-lentils-pork-cabbage",
    title: "Arroz, lentilha, lombo e salada de repolho",
    description: "Tiras de lombo suíno assado com salada de repolho.",
    mealSlot: "lunch",
    containsTags: ["meat"],
    dietCompatibleTags: ["low-cost"],
    ingredients: [
      { item: "arroz", qty: "4 colheres de sopa" },
      { item: "lentilha", qty: "1 concha" },
      { item: "lombo suíno assado", qty: "1 porção" },
      { item: "repolho", qty: "a gosto" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "spaghetti-homemade-meat-sauce",
    title: "Macarrão ao molho de tomate com carne moída",
    description:
      "Espaguete com molho caseiro, carne moída e ervilhas. Contém glúten e carne.",
    mealSlot: "lunch",
    containsTags: ["gluten", "meat"],
    dietCompatibleTags: ["low-cost"],
    ingredients: [
      { item: "macarrão espaguete", qty: "1 porção" },
      { item: "molho de tomate caseiro", qty: "1 concha" },
      { item: "carne moída", qty: "1/2 xícara" },
      { item: "ervilhas", qty: "2 colheres de sopa" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "garlic-oil-pasta-broccoli-chicken",
    title: "Macarrão alho e óleo com brócolis e frango",
    description:
      "Macarrão com alho, óleo, brócolis, cenoura e tiras de frango. Contém glúten e carne.",
    mealSlot: "lunch",
    containsTags: ["gluten", "meat"],
    dietCompatibleTags: ["low-cost"],
    ingredients: [
      { item: "macarrão", qty: "1 porção" },
      { item: "brócolis e cenoura", qty: "1 xícara" },
      { item: "frango em tiras", qty: "1/2 xícara" },
      { item: "alho e óleo", qty: "a gosto" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "pasta-sardine-tomato",
    title: "Macarrão com sardinha e molho de tomate",
    description:
      "Macarrão com sardinha, molho e cheiro-verde. Contém glúten e peixe.",
    mealSlot: "lunch",
    containsTags: ["gluten", "fish"],
    dietCompatibleTags: ["low-cost"],
    ingredients: [
      { item: "macarrão", qty: "1 porção" },
      { item: "sardinha", qty: "1 lata pequena" },
      { item: "molho de tomate", qty: "1 concha" },
      { item: "cheiro-verde", qty: "a gosto" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "sweet-potato-chicken-shepherd",
    title: "Escondidinho de batata-doce com frango",
    description: "Purê de batata-doce cobrindo frango desfiado.",
    mealSlot: "lunch",
    containsTags: ["meat"],
    dietCompatibleTags: ["low-cost"],
    ingredients: [
      { item: "batata-doce amassada", qty: "2 xícaras" },
      { item: "frango desfiado", qty: "1 xícara" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "cassava-ground-beef-shepherd",
    title: "Escondidinho de mandioca com carne moída",
    description: "Purê de mandioca com carne moída.",
    mealSlot: "lunch",
    containsTags: ["meat"],
    dietCompatibleTags: ["low-cost"],
    ingredients: [
      { item: "mandioca amassada", qty: "2 xícaras" },
      { item: "carne moída", qty: "1 xícara" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "savory-pancake-ground-beef",
    title: "Panqueca recheada com carne moída",
    description:
      "Massa simples de farinha ou aveia recheada com carne. Contém glúten e carne.",
    mealSlot: "lunch",
    containsTags: ["gluten", "meat", "egg"],
    dietCompatibleTags: ["low-cost"],
    ingredients: [
      { item: "farinha ou aveia", qty: "para a massa" },
      { item: "ovo", qty: "1 unidade" },
      { item: "carne moída", qty: "1 xícara" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "spinach-pancake-chicken-corn",
    title: "Panqueca verde com frango e milho",
    description:
      "Massa de espinafre recheada com frango e milho. Contém ovo e carne.",
    mealSlot: "lunch",
    containsTags: ["egg", "meat"],
    dietCompatibleTags: ["low-cost"],
    ingredients: [
      { item: "espinafre", qty: "1 punhado" },
      { item: "ovo", qty: "1 unidade" },
      { item: "frango desfiado", qty: "1 xícara" },
      { item: "milho", qty: "2 colheres de sopa" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "three-egg-omelette-rice",
    title: "Omelete de legumes com arroz",
    description: "Omelete de três ovos com espinafre, tomate e cebola, com arroz.",
    mealSlot: "lunch",
    containsTags: ["egg"],
    dietCompatibleTags: ["vegetarian", "low-cost"],
    ingredients: [
      { item: "ovos", qty: "3 unidades" },
      { item: "espinafre, tomate e cebola", qty: "a gosto" },
      { item: "arroz", qty: "3 colheres de sopa" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "baked-omelette-leftover-veggies",
    title: "Omelete de forno com sobras de legumes",
    description: "Legumes cozidos misturados a ovos e assados.",
    mealSlot: "lunch",
    containsTags: ["egg"],
    dietCompatibleTags: ["vegetarian", "low-cost"],
    ingredients: [
      { item: "ovos", qty: "3 unidades" },
      { item: "legumes cozidos", qty: "1 xícara" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "black-eyed-pea-tuna-salad",
    title: "Salada de feijão fradinho com atum",
    description:
      "Feijão fradinho, atum, cebola roxa, pimentão e coentro. Contém peixe.",
    mealSlot: "lunch",
    containsTags: ["fish"],
    dietCompatibleTags: ["low-cost"],
    ingredients: [
      { item: "feijão fradinho", qty: "1 xícara" },
      { item: "atum em lata", qty: "1 lata pequena" },
      { item: "cebola, pimentão e coentro", qty: "a gosto" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "chickpea-chicken-salad",
    title: "Salada de grão-de-bico com frango",
    description: "Grão-de-bico, frango desfiado, pepino e tomate.",
    mealSlot: "lunch",
    containsTags: ["meat"],
    dietCompatibleTags: ["low-cost"],
    ingredients: [
      { item: "grão-de-bico", qty: "1 xícara" },
      { item: "frango desfiado", qty: "1/2 xícara" },
      { item: "pepino e tomate", qty: "a gosto" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "baiao-dois-economico",
    title: "Baião de dois econômico",
    description:
      "Arroz com feijão de corda ou carioca, queijo meia cura e coentro. Contém lactose.",
    mealSlot: "lunch",
    containsTags: ["lactose"],
    dietCompatibleTags: ["vegetarian", "low-cost"],
    ingredients: [
      { item: "arroz", qty: "1 xícara" },
      { item: "feijão", qty: "1 concha" },
      { item: "queijo meia cura", qty: "2 colheres de sopa" },
      { item: "coentro", qty: "a gosto" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "baked-rice-chicken-carrot",
    title: "Arroz de forno com frango",
    description:
      "Arroz misturado com frango, cenoura, milho e molho de tomate.",
    mealSlot: "lunch",
    containsTags: ["meat"],
    dietCompatibleTags: ["low-cost"],
    ingredients: [
      { item: "arroz", qty: "2 xícaras" },
      { item: "frango desfiado", qty: "1 xícara" },
      { item: "cenoura ralada e milho", qty: "1 xícara" },
      { item: "molho de tomate", qty: "1/2 xícara" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "budget-chicken-stroganoff",
    title: "Strogonoff econômico de frango",
    description:
      "Frango com creme de ricota ou iogurte no lugar do creme de leite, arroz e salada. Contém carne e lactose.",
    mealSlot: "lunch",
    containsTags: ["meat", "lactose"],
    dietCompatibleTags: ["low-cost"],
    ingredients: [
      { item: "frango", qty: "1 xícara" },
      { item: "ricota ou iogurte", qty: "3 colheres de sopa" },
      { item: "arroz", qty: "4 colheres de sopa" },
      { item: "salada", qty: "a gosto" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "chicken-stew-potato-carrot",
    title: "Frango ensopado com batata e cenoura",
    description: "Frango ensopado com batata inglesa e cenoura, com arroz.",
    mealSlot: "lunch",
    containsTags: ["meat"],
    dietCompatibleTags: ["low-cost"],
    ingredients: [
      { item: "frango", qty: "1 porção" },
      { item: "batata e cenoura", qty: "1 xícara" },
      { item: "arroz", qty: "4 colheres de sopa" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "chicken-gizzard-cassava-stew",
    title: "Moela ensopada com mandioca",
    description: "Moela de frango com mandioca, acompanhada de arroz.",
    mealSlot: "lunch",
    containsTags: ["meat"],
    dietCompatibleTags: ["low-cost"],
    ingredients: [
      { item: "moela de frango", qty: "1 porção" },
      { item: "mandioca", qty: "1 xícara" },
      { item: "arroz", qty: "4 colheres de sopa" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "pork-strips-cabbage-pepper",
    title: "Lombo com repolho e pimentão",
    description: "Tiras de lombo refogadas com repolho e pimentão, com arroz.",
    mealSlot: "lunch",
    containsTags: ["meat"],
    dietCompatibleTags: ["low-cost"],
    ingredients: [
      { item: "lombo suíno", qty: "1 porção" },
      { item: "repolho e pimentão", qty: "2 xícaras" },
      { item: "arroz", qty: "4 colheres de sopa" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "stuffed-zucchini-beef",
    title: "Abobrinha recheada com carne moída",
    description: "Abobrinha assada recheada com carne moída.",
    mealSlot: "lunch",
    containsTags: ["meat"],
    dietCompatibleTags: ["low-cost"],
    ingredients: [
      { item: "abobrinha", qty: "2 unidades" },
      { item: "carne moída", qty: "1 xícara" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "stuffed-eggplant-chicken",
    title: "Berinjela recheada com frango",
    description: "Berinjela assada com frango desfiado e tomate.",
    mealSlot: "lunch",
    containsTags: ["meat"],
    dietCompatibleTags: ["low-cost"],
    ingredients: [
      { item: "berinjela", qty: "1 unidade" },
      { item: "frango desfiado", qty: "1 xícara" },
      { item: "tomate", qty: "1/2 unidade" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "cabbage-roll-beef-rice",
    title: "Charuto de repolho com carne e arroz",
    description: "Folha de repolho recheada com carne moída e arroz.",
    mealSlot: "lunch",
    containsTags: ["meat"],
    dietCompatibleTags: ["low-cost"],
    ingredients: [
      { item: "folhas de repolho", qty: "4 unidades" },
      { item: "carne moída", qty: "1 xícara" },
      { item: "arroz", qty: "1/2 xícara" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "blender-veggie-pie-salad",
    title: "Torta de liquidificador de legumes",
    description:
      "Torta de legumes acompanhada de salada verde. Contém ovo e glúten se usar farinha de trigo.",
    mealSlot: "lunch",
    containsTags: ["egg", "gluten"],
    dietCompatibleTags: ["vegetarian", "low-cost"],
    ingredients: [
      { item: "legumes picados", qty: "2 xícaras" },
      { item: "ovos", qty: "2 unidades" },
      { item: "farinha", qty: "1 xícara" },
      { item: "salada verde", qty: "a gosto" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "simple-chicken-salpicao",
    title: "Salpicão simples com iogurte",
    description:
      "Frango, cenoura, milho e iogurte no lugar da maionese, com arroz. Contém carne e lactose.",
    mealSlot: "lunch",
    containsTags: ["meat", "lactose"],
    dietCompatibleTags: ["low-cost"],
    ingredients: [
      { item: "frango desfiado", qty: "1 xícara" },
      { item: "cenoura ralada e milho", qty: "1 xícara" },
      { item: "iogurte natural", qty: "3 colheres de sopa" },
      { item: "arroz", qty: "4 colheres de sopa" },
    ],
    isPublished: true,
  }),
  meal({
    slug: "rice-beans-salad-vegan",
    title: "Arroz, feijão e salada",
    description:
      "Base vegana do MVP: arroz, feijão e salada crua. (mantido Nutri)",
    mealSlot: "lunch",
    containsTags: [],
    dietCompatibleTags: ["vegan", "vegetarian", "low-cost"],
    ingredients: [
      { item: "arroz cozido", qty: "4 colheres de sopa" },
      { item: "feijão", qty: "1 concha" },
      { item: "salada", qty: "a gosto" },
    ],
    isPublished: true,
  }),
];
