/**
 * Generates SQL to sync meal contains_tags + diet_compatible_tags
 * from Nutricionista enrichment (ingredients × FOOD_AVOID_CONDITIONS).
 */

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { mealIdFromSlug } from "../lib/admin/meal-id";
import { MEAL_SEED_CATALOG_FULL } from "../lib/admin/meal-seed-catalog";
import { FOOD_AVOID_CONDITIONS } from "../lib/nutrition/food-conditions-catalog";
import { enrichMealCatalog } from "../lib/nutrition/meal-safety";

function sqlArray(values: string[]): string {
  if (values.length === 0) {
    return "'{}'::text[]";
  }
  const body = values
    .map((value) => `'${value.replace(/'/g, "''")}'`)
    .join(", ");
  return `array[${body}]::text[]`;
}

const enriched = enrichMealCatalog(MEAL_SEED_CATALOG_FULL);

const lines: string[] = [];
lines.push(`-- purpose: sync meal contains_tags + diet_compatible_tags`);
lines.push(`--   from Nutricionista enrichment (ingredients × food avoid catalog).`);
lines.push(`-- affected: tags, meals_library, list_safe_meals`);
lines.push(`-- notes: generated by scripts/generate-meal-safety-sync-sql.ts`);
lines.push(`--   ensures lactose/gluten/egg/meat/fish/peanut/soy match the plate.`);
lines.push("");

lines.push("insert into public.tags (slug, domain, kind, label)");
lines.push("values");
lines.push(
  FOOD_AVOID_CONDITIONS.map(
    (condition) =>
      `  ('${condition.slug}', 'food', 'contains', '${condition.labelPtBr.replace(/'/g, "''")}')`,
  ).join(",\n"),
);
lines.push("on conflict (slug) do update");
lines.push("set domain = excluded.domain, kind = excluded.kind, label = excluded.label;");
lines.push("");

for (const meal of enriched) {
  const id = mealIdFromSlug(meal.slug);
  lines.push(`update public.meals_library`);
  lines.push(`set contains_tags = ${sqlArray(meal.containsTags)},`);
  lines.push(
    `    diet_compatible_tags = ${sqlArray(meal.dietCompatibleTags)},`,
  );
  lines.push(`    updated_at = now()`);
  lines.push(`where id = '${id}';`);
  lines.push("");
}

// Harden comment on the existing motor (logic already correct).
lines.push(`comment on function public.list_safe_meals() is`);
lines.push(
  `  'Meal engine. Blocks when contains_tags overlaps avoids_tags; enforces vegan/vegetarian diet_pattern. Tags enriched by Nutricionista.';`,
);
lines.push("");

const outPath = resolve(
  "supabase/migrations/20260921220000_sync_meal_nutrition_safety.sql",
);
writeFileSync(outPath, `${lines.join("\n")}\n`, "utf8");

const changed = enriched.filter((meal, index) => {
  const raw = MEAL_SEED_CATALOG_FULL[index];
  return (
    meal.containsTags.join() !== raw.containsTags.join() ||
    meal.dietCompatibleTags.join() !== raw.dietCompatibleTags.join()
  );
});

console.log(
  `Wrote sync migration: ${enriched.length} meals, ${changed.length} changed → ${outPath}`,
);
for (const meal of changed) {
  console.log(
    `  ${meal.slug}: contains=[${meal.containsTags.join(",")}] diet=[${meal.dietCompatibleTags.join(",")}]`,
  );
}
