/**
 * Generates SQL to sync tag_block_rules + exercise contraindication_tags
 * from the Educador Físico catalog (conditions-catalog + exercise seeds).
 */

import { writeFileSync } from "node:fs";
import { resolve } from "node:path";

import { exerciseIdFromSlug } from "../lib/admin/exercise-id";
import { EXERCISE_SEED_CATALOG_FULL } from "../lib/admin/exercise-seed-catalog";
import {
  clinicalBlockRules,
  enrichExerciseCatalog,
} from "../lib/clinical/exercise-safety";
import { MOVEMENT_CONTENT_TAGS } from "../lib/clinical/conditions-catalog";

function sqlArray(values: string[]): string {
  if (values.length === 0) {
    return "'{}'::text[]";
  }
  const body = values.map((value) => `'${value.replace(/'/g, "''")}'`).join(", ");
  return `array[${body}]::text[]`;
}

const enriched = enrichExerciseCatalog(EXERCISE_SEED_CATALOG_FULL);
const rules = clinicalBlockRules();

const intensityLabels: Record<string, string> = {
  "use-legs": "Uso de pernas",
  "standing-required": "Exige ficar em pé",
  "seated-only": "Apenas sentado",
  "lower-body-plyometrics": "Pliometria de membros inferiores",
  "high-impact": "Alto impacto",
  "high-speed": "Alta velocidade",
  "bilateral-push-up": "Flexão bilateral",
  "double-hand-support": "Apoio duplo das mãos",
  "floor-push": "Empurrar o chão",
  "spatial-travel": "Deslocamento espacial",
  "distance-jump": "Salto em distância",
  "long-lever": "Alavanca longa",
  "lumbar-impact": "Impacto lombar",
  "deep-knee-flexion": "Flexão profunda de joelho",
  "knee-lateral-force": "Força lateral no joelho",
  "tibial-posterior-load": "Carga tibial posterior",
  "rotational-instability": "Instabilidade rotacional",
  "unilateral-full-load": "Carga unilateral total",
  "side-lying-pressure": "Pressão em decúbito lateral",
  "deep-hip-flexion": "Flexão profunda de quadril",
  "explosive-adductors": "Adutores explosivos",
  "unstable-base": "Base instável",
  "forefoot-impact": "Impacto na ponta dos pés",
  "overhead-press": "Empurrar acima da cabeça",
  "lateral-raise-above-90": "Elevação lateral acima de 90",
  "hanging-traction": "Tração pendurada",
  "wide-arm-tension": "Tensão com braços abertos",
  "cross-body-load": "Carga cruzando o corpo",
  "prolonged-grip": "Preensão prolongada",
  "wrist-extension-load": "Carga em extensão de punho",
  "elbow-valgus-load": "Carga em valgo no cotovelo",
  "forearm-plank-hard": "Prancha nos antebraços em superfície dura",
  "spine-flexion-rotation": "Flexão com rotação da coluna",
  "spine-hyperextension": "Hiperextensão da coluna",
  "high-intra-abdominal-pressure": "Alta pressão intra-abdominal",
  "max-range-stretch": "Alongamento em amplitude máxima",
  "axial-load": "Carga axial",
  inversion: "Inversão",
  spin: "Giro",
  "high-intensity": "Intensidade alta",
  "prone-position": "Decúbito ventral",
  "active-pause": "Pausa ativa",
  "low-intensity": "Intensidade baixa",
  "medium-intensity": "Intensidade média",
};

const lines: string[] = [];
lines.push(`-- purpose: sync clinical block rules + exercise contraindications`);
lines.push(`--   from Educador Físico catalog (conditions-catalog + seed enrichment).`);
lines.push(`-- affected: tags, tag_block_rules, exercises_library, list_safe_exercises`);
lines.push(`-- notes: generated by scripts/generate-exercise-safety-sync-sql.ts`);
lines.push(`--   fills gaps (e.g. torn-acl → high-impact / plyometrics).`);
lines.push("");

// Ensure intensity tags used by rules exist.
const allBlockedTags = Array.from(
  new Set([
    ...MOVEMENT_CONTENT_TAGS,
    ...rules.map((r) => r.blockedContentTag),
    "prone-position",
    "axial-load",
    "inversion",
    "spin",
    "high-intensity",
    "high-impact",
    "lower-body-plyometrics",
  ]),
).sort();

lines.push("insert into public.tags (slug, domain, kind, label)");
lines.push("values");
lines.push(
  allBlockedTags
    .map((slug) => {
      const label = intensityLabels[slug] ?? slug;
      return `  ('${slug}', 'movement', 'intensity', '${label.replace(/'/g, "''")}')`;
    })
    .join(",\n"),
);
lines.push("on conflict (slug) do update");
lines.push("set domain = excluded.domain, kind = excluded.kind, label = excluded.label;");
lines.push("");

lines.push("insert into public.tag_block_rules (condition_slug, blocked_content_tag)");
lines.push("values");
lines.push(
  rules
    .map(
      (rule) =>
        `  ('${rule.conditionSlug}', '${rule.blockedContentTag}')`,
    )
    .join(",\n"),
);
lines.push("on conflict (condition_slug, blocked_content_tag) do nothing;");
lines.push("");

// Enrich each exercise contraindication list.
for (const exercise of enriched) {
  const id = exerciseIdFromSlug(exercise.slug);
  lines.push(`update public.exercises_library`);
  lines.push(
    `set contraindication_tags = ${sqlArray(exercise.contraindicationTags)},`,
  );
  lines.push(`    updated_at = now()`);
  lines.push(`where id = '${id}';`);
  lines.push("");
}

// Harden motor: normalize hernia ↔ disc-herniation + equipment specialty filter.
// Keep in sync with 20260922150000_fix_equipment_specialty_filter.sql
lines.push(`create or replace function public.list_safe_exercises()`);
lines.push(`returns setof public.exercises_library`);
lines.push(`language plpgsql`);
lines.push(`stable`);
lines.push(`security invoker`);
lines.push(`set search_path = ''`);
lines.push(`as $$`);
lines.push(`declare`);
lines.push(`  v_conditions text[] := '{}';`);
lines.push(`  v_capabilities text[] := '{}';`);
lines.push(`  v_equipment text[] := array['bodyweight']::text[];`);
lines.push(`  v_phases text[] := '{}';`);
lines.push(`  v_union text[] := '{}';`);
lines.push(`begin`);
lines.push(`  if not public.has_accepted_consent('health_personalization') then`);
lines.push(`    return;`);
lines.push(`  end if;`);
lines.push(``);
lines.push(`  select`);
lines.push(`    coalesce(clinical.condition_tags, '{}'),`);
lines.push(`    coalesce(clinical.capability_tags, '{}'),`);
lines.push(
  `    coalesce(clinical.available_equipment_tags, array['bodyweight']::text[])`,
);
lines.push(`  into v_conditions, v_capabilities, v_equipment`);
lines.push(`  from public.user_clinical_conditions as clinical`);
lines.push(`  where clinical.user_id = (select auth.uid());`);
lines.push(``);
lines.push(`  if not found then`);
lines.push(`    return;`);
lines.push(`  end if;`);
lines.push(``);
lines.push(`  if not ('bodyweight' = any (v_equipment)) then`);
lines.push(`    v_equipment := array_append(v_equipment, 'bodyweight');`);
lines.push(`  end if;`);
lines.push(``);
lines.push(`  select coalesce(cycle.phase_tags, '{}')`);
lines.push(`  into v_phases`);
lines.push(`  from public.user_cycle_profiles as cycle`);
lines.push(`  where cycle.user_id = (select auth.uid());`);
lines.push(``);
lines.push(`  if not found then`);
lines.push(`    v_phases := '{}';`);
lines.push(`  end if;`);
lines.push(``);
lines.push(`  v_union := v_conditions || v_phases;`);
lines.push(``);
lines.push(`  -- legacy alias: hernia ↔ disc-herniation`);
lines.push(`  if 'hernia' = any (v_union) and not ('disc-herniation' = any (v_union)) then`);
lines.push(`    v_union := array_append(v_union, 'disc-herniation');`);
lines.push(`  end if;`);
lines.push(`  if 'disc-herniation' = any (v_union) and not ('hernia' = any (v_union)) then`);
lines.push(`    v_union := array_append(v_union, 'hernia');`);
lines.push(`  end if;`);
lines.push(``);
lines.push(`  return query`);
lines.push(`  select exercise.*`);
lines.push(`  from public.exercises_library as exercise`);
lines.push(`  where exercise.is_published = true`);
lines.push(`    and not (exercise.contraindication_tags && v_union)`);
lines.push(`    -- posture tags (standing|seated|lying) are OR; other capabilities are AND`);
lines.push(`    and (`);
lines.push(`      coalesce((`);
lines.push(`        select array_agg(tag order by tag)`);
lines.push(`        from unnest(exercise.required_capability_tags) as tag`);
lines.push(`        where tag not in ('standing', 'seated', 'lying')`);
lines.push(`      ), '{}'::text[]) <@ v_capabilities`);
lines.push(`      and (`);
lines.push(`        not exists (`);
lines.push(`          select 1`);
lines.push(`          from unnest(exercise.required_capability_tags) as tag`);
lines.push(`          where tag in ('standing', 'seated', 'lying')`);
lines.push(`        )`);
lines.push(`        or exists (`);
lines.push(`          select 1`);
lines.push(`          from unnest(exercise.required_capability_tags) as tag`);
lines.push(`          where tag in ('standing', 'seated', 'lying')`);
lines.push(`            and tag = any (v_capabilities)`);
lines.push(`        )`);
lines.push(`      )`);
lines.push(`    )`);
lines.push(`    and (`);
lines.push(`      coalesce(cardinality(exercise.equipment_tags), 0) = 0`);
lines.push(`      or (`);
lines.push(`        not (`);
lines.push(`          'resistance-band' = any (exercise.equipment_tags)`);
lines.push(`          and not ('resistance-band' = any (v_equipment))`);
lines.push(`        )`);
lines.push(`        and not (`);
lines.push(`          'dumbbells' = any (exercise.equipment_tags)`);
lines.push(`          and not ('dumbbells' = any (v_equipment))`);
lines.push(`        )`);
lines.push(`        and exercise.equipment_tags && v_equipment`);
lines.push(`      )`);
lines.push(`    )`);
lines.push(`    and not exists (`);
lines.push(`      select 1`);
lines.push(`      from public.tag_block_rules as block_rule`);
lines.push(`      where block_rule.condition_slug = any (v_union)`);
lines.push(`        and block_rule.blocked_content_tag = any (exercise.intensity_tags)`);
lines.push(`    )`);
lines.push(`  order by exercise.title;`);
lines.push(`end;`);
lines.push(`$$;`);
lines.push(``);
lines.push(`comment on function public.list_safe_exercises() is`);
lines.push(
  `  'Motor de treino. Bloqueia contraindicações, capabilities (postura OR), specialty equipment e tag_block_rules. Normaliza hernia/disc-herniation.';`,
);
lines.push("");
lines.push(`revoke all on function public.list_safe_exercises() from public;`);
lines.push(`revoke all on function public.list_safe_exercises() from anon;`);
lines.push(`grant execute on function public.list_safe_exercises() to authenticated;`);
lines.push("");

const outPath = resolve(
  "supabase/migrations/20260922180000_cycle_t1_postpartum_and_posture_capability_or.sql",
);
writeFileSync(outPath, `${lines.join("\n")}\n`, "utf8");
console.log(
  `Wrote sync migration: ${rules.length} block rules, ${enriched.length} exercises → ${outPath}`,
);
