-- purpose: expand clinical condition and movement content tags for inclusive
--   onboarding search UI and deterministic block rules (educador fisico catalog).
-- affected: tags, tag_block_rules
-- notes: labels are pt-BR (user-facing). slugs stay english. upsert-safe.

insert into public.tags (slug, domain, kind, label)
values
  -- existing kept; new conditions
  ('spinal-cord-injury-paraplegia', 'movement', 'condition', 'Lesão medular / cadeira de rodas'),
  ('lower-limb-amputation-unilateral', 'movement', 'condition', 'Amputação de membro inferior (unilateral)'),
  ('upper-limb-amputation-unilateral', 'movement', 'condition', 'Amputação de membro superior (unilateral)'),
  ('hemiplegia-hemiparesis', 'movement', 'condition', 'Hemiplegia ou hemiparesia'),
  ('cerebral-palsy-mild-moderate', 'movement', 'condition', 'Paralisia cerebral (leve a moderada)'),
  ('achondroplasia', 'movement', 'condition', 'Nanismo (acondroplasia)'),
  ('visual-impairment', 'movement', 'condition', 'Deficiência visual'),
  ('torn-pcl', 'movement', 'condition', 'Ruptura do LCP'),
  ('collateral-ligament-injury', 'movement', 'condition', 'Lesão dos ligamentos colaterais'),
  ('patellar-tendinopathy', 'movement', 'condition', 'Tendinopatia patelar'),
  ('knee-osteoarthritis', 'movement', 'condition', 'Artrose de joelho'),
  ('trochanteric-bursitis', 'movement', 'condition', 'Bursite trocantérica'),
  ('piriformis-syndrome', 'movement', 'condition', 'Síndrome do piriforme'),
  ('femoroacetabular-impingement', 'movement', 'condition', 'Impacto femoroacetabular'),
  ('athletic-pubalgia', 'movement', 'condition', 'Pubalgia'),
  ('ankle-ligament-sprain', 'movement', 'condition', 'Entorse de tornozelo'),
  ('plantar-fasciitis', 'movement', 'condition', 'Fascite plantar'),
  ('rotator-cuff-injury', 'movement', 'condition', 'Lesão do manguito rotador'),
  ('subacromial-bursitis', 'movement', 'condition', 'Bursite subacromial'),
  ('slap-tear', 'movement', 'condition', 'Lesão SLAP'),
  ('shoulder-instability', 'movement', 'condition', 'Instabilidade do ombro'),
  ('ac-joint-injury', 'movement', 'condition', 'Lesão acromioclavicular'),
  ('epicondylitis', 'movement', 'condition', 'Epicondilite'),
  ('elbow-ucl-injury', 'movement', 'condition', 'Lesão do UCL do cotovelo'),
  ('olecranon-bursitis', 'movement', 'condition', 'Bursite olecraniana'),
  ('carpal-tunnel-de-quervain', 'movement', 'condition', 'Túnel do carpo / De Quervain'),
  ('tfcc-injury', 'movement', 'condition', 'Lesão do TFCC'),
  ('disc-herniation', 'movement', 'condition', 'Hérnia de disco'),
  ('spondylolisthesis', 'movement', 'condition', 'Espondilolistese'),
  ('spinal-stenosis', 'movement', 'condition', 'Estenose espinhal'),
  ('diastasis-recti', 'movement', 'condition', 'Diástase abdominal'),
  ('osteoporosis-osteopenia', 'movement', 'condition', 'Osteoporose / osteopenia'),
  ('rheumatoid-arthritis', 'movement', 'condition', 'Artrite reumatoide'),
  ('chronic-muscle-strain', 'movement', 'condition', 'Estiramento muscular crônico'),
  -- ensure mobility-derived condition tags remain labeled
  ('wheelchair-user', 'movement', 'condition', 'Uso de cadeira de rodas'),
  ('reduced-mobility', 'movement', 'condition', 'Mobilidade reduzida permanente'),
  ('hypertension', 'movement', 'condition', 'Hipertensão'),
  ('labyrinthitis', 'movement', 'condition', 'Labirintite'),
  ('torn-acl', 'movement', 'condition', 'Ruptura do LCA'),
  ('chondromalacia', 'movement', 'condition', 'Condromalácia patelar'),
  ('hernia', 'movement', 'condition', 'Hérnia (legado)'),
  -- movement content / intensity tags used in block rules
  ('use-legs', 'movement', 'intensity', 'Uso de pernas'),
  ('standing-required', 'movement', 'intensity', 'Exige ficar em pé'),
  ('seated-only', 'movement', 'intensity', 'Apenas sentado'),
  ('high-speed', 'movement', 'intensity', 'Alta velocidade'),
  ('bilateral-push-up', 'movement', 'intensity', 'Flexão bilateral'),
  ('double-hand-support', 'movement', 'intensity', 'Apoio duplo das mãos'),
  ('floor-push', 'movement', 'intensity', 'Empurrar o chão'),
  ('spatial-travel', 'movement', 'intensity', 'Deslocamento espacial'),
  ('distance-jump', 'movement', 'intensity', 'Salto em distância'),
  ('long-lever', 'movement', 'intensity', 'Alavanca longa'),
  ('lumbar-impact', 'movement', 'intensity', 'Impacto lombar'),
  ('deep-knee-flexion', 'movement', 'intensity', 'Flexão profunda de joelho'),
  ('knee-lateral-force', 'movement', 'intensity', 'Força lateral no joelho'),
  ('tibial-posterior-load', 'movement', 'intensity', 'Carga tibial posterior'),
  ('rotational-instability', 'movement', 'intensity', 'Instabilidade rotacional'),
  ('unilateral-full-load', 'movement', 'intensity', 'Carga unilateral total'),
  ('side-lying-pressure', 'movement', 'intensity', 'Pressão em decúbito lateral'),
  ('deep-hip-flexion', 'movement', 'intensity', 'Flexão profunda de quadril'),
  ('explosive-adductors', 'movement', 'intensity', 'Adutores explosivos'),
  ('unstable-base', 'movement', 'intensity', 'Base instável'),
  ('forefoot-impact', 'movement', 'intensity', 'Impacto na ponta dos pés'),
  ('overhead-press', 'movement', 'intensity', 'Empurrar acima da cabeça'),
  ('lateral-raise-above-90', 'movement', 'intensity', 'Elevação lateral acima de 90'),
  ('hanging-traction', 'movement', 'intensity', 'Tração pendurada'),
  ('wide-arm-tension', 'movement', 'intensity', 'Tensão com braços abertos'),
  ('cross-body-load', 'movement', 'intensity', 'Carga cruzando o corpo'),
  ('prolonged-grip', 'movement', 'intensity', 'Preensão prolongada'),
  ('wrist-extension-load', 'movement', 'intensity', 'Carga em extensão de punho'),
  ('elbow-valgus-load', 'movement', 'intensity', 'Carga em valgo no cotovelo'),
  ('forearm-plank-hard', 'movement', 'intensity', 'Prancha nos antebraços em superfície dura'),
  ('spine-flexion-rotation', 'movement', 'intensity', 'Flexão com rotação da coluna'),
  ('spine-hyperextension', 'movement', 'intensity', 'Hiperextensão da coluna'),
  ('high-intra-abdominal-pressure', 'movement', 'intensity', 'Alta pressão intra-abdominal'),
  ('max-range-stretch', 'movement', 'intensity', 'Alongamento em amplitude máxima')
on conflict (slug) do update
set
  domain = excluded.domain,
  kind = excluded.kind,
  label = excluded.label;

-- replace hernia slug usage: keep both hernia (legacy) and disc-herniation
-- map old hernia block to disc-herniation as well
insert into public.tag_block_rules (condition_slug, blocked_content_tag)
values
  ('spinal-cord-injury-paraplegia', 'use-legs'),
  ('spinal-cord-injury-paraplegia', 'standing-required'),
  ('spinal-cord-injury-paraplegia', 'lower-body-plyometrics'),
  ('spinal-cord-injury-paraplegia', 'high-impact'),
  ('lower-limb-amputation-unilateral', 'lower-body-plyometrics'),
  ('lower-limb-amputation-unilateral', 'high-impact'),
  ('lower-limb-amputation-unilateral', 'distance-jump'),
  ('upper-limb-amputation-unilateral', 'double-hand-support'),
  ('upper-limb-amputation-unilateral', 'floor-push'),
  ('upper-limb-amputation-unilateral', 'bilateral-push-up'),
  ('hemiplegia-hemiparesis', 'high-speed'),
  ('hemiplegia-hemiparesis', 'lower-body-plyometrics'),
  ('hemiplegia-hemiparesis', 'high-impact'),
  ('hemiplegia-hemiparesis', 'spatial-travel'),
  ('cerebral-palsy-mild-moderate', 'high-speed'),
  ('cerebral-palsy-mild-moderate', 'lower-body-plyometrics'),
  ('cerebral-palsy-mild-moderate', 'high-impact'),
  ('achondroplasia', 'lumbar-impact'),
  ('achondroplasia', 'long-lever'),
  ('achondroplasia', 'high-impact'),
  ('visual-impairment', 'spatial-travel'),
  ('visual-impairment', 'distance-jump'),
  ('visual-impairment', 'high-speed'),
  ('torn-acl', 'rotational-instability'),
  ('torn-acl', 'spatial-travel'),
  ('torn-pcl', 'tibial-posterior-load'),
  ('torn-pcl', 'deep-knee-flexion'),
  ('torn-pcl', 'high-impact'),
  ('collateral-ligament-injury', 'knee-lateral-force'),
  ('collateral-ligament-injury', 'spatial-travel'),
  ('collateral-ligament-injury', 'lower-body-plyometrics'),
  ('chondromalacia', 'deep-knee-flexion'),
  ('patellar-tendinopathy', 'lower-body-plyometrics'),
  ('patellar-tendinopathy', 'high-impact'),
  ('patellar-tendinopathy', 'high-speed'),
  ('knee-osteoarthritis', 'high-impact'),
  ('knee-osteoarthritis', 'lower-body-plyometrics'),
  ('knee-osteoarthritis', 'unilateral-full-load'),
  ('trochanteric-bursitis', 'side-lying-pressure'),
  ('piriformis-syndrome', 'deep-hip-flexion'),
  ('femoroacetabular-impingement', 'deep-hip-flexion'),
  ('femoroacetabular-impingement', 'deep-knee-flexion'),
  ('athletic-pubalgia', 'explosive-adductors'),
  ('athletic-pubalgia', 'high-intra-abdominal-pressure'),
  ('ankle-ligament-sprain', 'unstable-base'),
  ('ankle-ligament-sprain', 'spatial-travel'),
  ('ankle-ligament-sprain', 'knee-lateral-force'),
  ('plantar-fasciitis', 'forefoot-impact'),
  ('plantar-fasciitis', 'lower-body-plyometrics'),
  ('plantar-fasciitis', 'high-impact'),
  ('rotator-cuff-injury', 'overhead-press'),
  ('rotator-cuff-injury', 'lateral-raise-above-90'),
  ('subacromial-bursitis', 'overhead-press'),
  ('subacromial-bursitis', 'lateral-raise-above-90'),
  ('slap-tear', 'hanging-traction'),
  ('shoulder-instability', 'wide-arm-tension'),
  ('shoulder-instability', 'bilateral-push-up'),
  ('ac-joint-injury', 'cross-body-load'),
  ('ac-joint-injury', 'floor-push'),
  ('epicondylitis', 'prolonged-grip'),
  ('elbow-ucl-injury', 'elbow-valgus-load'),
  ('elbow-ucl-injury', 'wide-arm-tension'),
  ('olecranon-bursitis', 'forearm-plank-hard'),
  ('carpal-tunnel-de-quervain', 'wrist-extension-load'),
  ('carpal-tunnel-de-quervain', 'floor-push'),
  ('tfcc-injury', 'wrist-extension-load'),
  ('disc-herniation', 'spine-flexion-rotation'),
  ('disc-herniation', 'high-impact'),
  ('disc-herniation', 'axial-load'),
  ('disc-herniation', 'lumbar-impact'),
  ('hernia', 'spine-flexion-rotation'),
  ('hernia', 'lumbar-impact'),
  ('spondylolisthesis', 'spine-hyperextension'),
  ('spondylolisthesis', 'axial-load'),
  ('spinal-stenosis', 'spine-hyperextension'),
  ('diastasis-recti', 'high-intra-abdominal-pressure'),
  ('osteoporosis-osteopenia', 'lower-body-plyometrics'),
  ('osteoporosis-osteopenia', 'high-impact'),
  ('osteoporosis-osteopenia', 'spine-flexion-rotation'),
  ('rheumatoid-arthritis', 'high-impact'),
  ('rheumatoid-arthritis', 'wrist-extension-load'),
  ('rheumatoid-arthritis', 'prolonged-grip'),
  ('chronic-muscle-strain', 'max-range-stretch'),
  ('chronic-muscle-strain', 'high-speed'),
  ('hypertension', 'high-intensity'),
  ('hypertension', 'inversion'),
  ('labyrinthitis', 'spin'),
  ('labyrinthitis', 'inversion')
on conflict (condition_slug, blocked_content_tag) do nothing;

-- keep legacy labels for torn-acl / chondromalacia / hypertension / labyrinthitis
update public.tags
set label = 'Ruptura do LCA'
where slug = 'torn-acl';

update public.tags
set label = 'Condromalácia patelar'
where slug = 'chondromalacia';
