-- purpose: full low-cost meal library seed (Nutricionista review).
-- affected: meals_library
-- notes: generated from lib/admin/meal-seed-catalog*.ts
--   upsert by fixed uuid from slug; photos at meals/photos/{slug}.png

delete from public.meals_library
where id in (
  'b1000000-0000-4000-8000-000000000001',
  'b1000000-0000-4000-8000-000000000002',
  'b1000000-0000-4000-8000-000000000003',
  'b1000000-0000-4000-8000-000000000004',
  'b1000000-0000-4000-8000-000000000005',
  'b1000000-0000-4000-8000-000000000006',
  'b1000000-0000-4000-8000-000000000007',
  'b1000000-0000-4000-8000-000000000008',
  'b1000000-0000-4000-8000-000000000009',
  'b1000000-0000-4000-8000-00000000000a',
  'b1000000-0000-4000-8000-00000000000b',
  'b1000000-0000-4000-8000-00000000000c'
);

insert into public.meals_library (
  id, title, description, ingredients, image_paths, meal_slot,
  contains_tags, diet_compatible_tags, phase_tags, is_published, created_by
)
values
  (
    '1da27d99-4219-4aeb-8fa5-1a5852e66bd2',
    'Mingau de aveia com banana e canela',
    'Aqueça a aveia com água ou leite até engrossar. Amasse a banana, junte canela. Sem açúcar se preferir. Aveia comum: contém glúten.',
    '[{"item":"aveia em flocos","qty":"4 colheres de sopa"},{"item":"banana","qty":"1 unidade"},{"item":"canela","qty":"a gosto"},{"item":"água ou leite","qty":"200 ml","alt":"água (sem lactose)"}]'::jsonb,
    array['meals/photos/oatmeal-banana-cinnamon.png'],
    'breakfast',
    array['gluten'],
    array['vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    'd6af4736-e5f2-4add-8c15-375d350c63b1',
    'Mingau de aveia com maçã e cravo',
    'Cozinhe a aveia com água. Acrescente maçã picada e um cravo. Contém glúten.',
    '[{"item":"aveia em flocos","qty":"4 colheres de sopa"},{"item":"maçã","qty":"1 unidade"},{"item":"cravo","qty":"1 unidade"},{"item":"água","qty":"200 ml"}]'::jsonb,
    array['meals/photos/oatmeal-apple-clove.png'],
    'breakfast',
    array['gluten'],
    array['vegan', 'vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    '67d93713-dbdd-4662-8cd6-a363dc6b9eb0',
    'Mingau de fubá com frutas',
    'Dissolva o fubá em água fria, cozinhe mexendo até engrossar. Adoce com frutas picadas, sem açúcar.',
    '[{"item":"fubá","qty":"3 colheres de sopa"},{"item":"água","qty":"250 ml"},{"item":"fruta da estação","qty":"1 unidade"}]'::jsonb,
    array['meals/photos/cornmeal-porridge-fruit.png'],
    'breakfast',
    '{}',
    array['vegan', 'vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    'b786049a-e120-4a6f-8a3d-dbd9a8f130e0',
    'Crepioca com tomate e orégano',
    'Misture goma de tapioca e ovo. Frite fino. Recheie com tomate e orégano.',
    '[{"item":"goma de tapioca","qty":"2 colheres de sopa"},{"item":"ovo","qty":"1 unidade"},{"item":"tomate","qty":"1/2 unidade"},{"item":"orégano","qty":"a gosto"}]'::jsonb,
    array['meals/photos/crepioca-tomato-oregano.png'],
    'breakfast',
    array['egg'],
    array['vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    '4900bf7a-7fc8-44af-84af-01369ce44919',
    'Crepioca verde com creme de ricota',
    'Bata ovo com espinafre ou couve e goma. Recheie com ricota amassada. Contém ovo e lactose.',
    '[{"item":"goma de tapioca","qty":"2 colheres de sopa"},{"item":"ovo","qty":"1 unidade"},{"item":"espinafre ou couve","qty":"1 punhado"},{"item":"ricota","qty":"2 colheres de sopa"}]'::jsonb,
    array['meals/photos/green-crepioca-ricotta.png'],
    'breakfast',
    array['egg', 'lactose'],
    array['vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    '1992c34c-823f-43e5-82b2-08f15f514bf3',
    'Crepioca de cenoura',
    'Rale a cenoura e bata com ovo e goma. Frite em frigideira antiaderente.',
    '[{"item":"goma de tapioca","qty":"2 colheres de sopa"},{"item":"ovo","qty":"1 unidade"},{"item":"cenoura ralada","qty":"2 colheres de sopa"}]'::jsonb,
    array['meals/photos/carrot-crepioca.png'],
    'breakfast',
    array['egg'],
    array['vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    'e76b8b1d-0c99-4406-8a58-6f522d84df6d',
    'Cuscuz de milho com ovos mexidos',
    'Hidrate o flocão de milho. Acompanhe com ovos mexidos simples.',
    '[{"item":"flocão de milho","qty":"4 colheres de sopa"},{"item":"ovos","qty":"2 unidades"},{"item":"água","qty":"para hidratar"}]'::jsonb,
    array['meals/photos/corn-couscous-scrambled-eggs.png'],
    'breakfast',
    array['egg'],
    array['vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    '84a4efdc-1bac-4e4a-8ef2-e70ea6cd0734',
    'Cuscuz de milho com frango desfiado',
    'Cuscuz de milho acompanhado de frango desfiado temperado. Contém carne.',
    '[{"item":"flocão de milho","qty":"4 colheres de sopa"},{"item":"frango desfiado","qty":"1/2 xícara"}]'::jsonb,
    array['meals/photos/corn-couscous-shredded-chicken.png'],
    'breakfast',
    array['meat'],
    array['low-cost'],
    '{}',
    true,
    null
  ),
  (
    'c237b705-881f-4cea-8ff8-18f750816223',
    'Cuscuz de milho com queijo branco',
    'Cuscuz de milho com fatias de queijo minas ou coalho. Contém lactose.',
    '[{"item":"flocão de milho","qty":"4 colheres de sopa"},{"item":"queijo branco","qty":"2 fatias"}]'::jsonb,
    array['meals/photos/corn-couscous-white-cheese.png'],
    'breakfast',
    array['lactose'],
    array['vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    'd4b85a71-85b9-405b-8fe6-e384de0a9ffd',
    'Tapioca com ovos mexidos e cebolinha',
    'Abra a tapioca na frigideira. Recheie com ovos mexidos e cebolinha.',
    '[{"item":"goma de tapioca","qty":"3 colheres de sopa"},{"item":"ovos","qty":"2 unidades"},{"item":"cebolinha","qty":"a gosto"}]'::jsonb,
    array['meals/photos/tapioca-scrambled-eggs-chives.png'],
    'breakfast',
    array['egg'],
    array['vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    '08c56ba5-4570-495f-8f75-51f01554300b',
    'Tapioca com pasta de amendoim',
    'Tapioca fina recheada com pasta de amendoim integral. Contém amendoim.',
    '[{"item":"goma de tapioca","qty":"3 colheres de sopa"},{"item":"pasta de amendoim integral","qty":"1 colher de sopa"}]'::jsonb,
    array['meals/photos/tapioca-peanut-butter.png'],
    'breakfast',
    array['peanut'],
    array['vegan', 'vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    '7e46748b-f472-4653-8bdb-cd09df3baaa4',
    'Pão com ovo na chapa',
    'Pão francês ou de forma integral com ovo frito na chapa. Contém glúten e ovo.',
    '[{"item":"pão","qty":"1 unidade","alt":"pão de forma integral"},{"item":"ovo","qty":"1 unidade"}]'::jsonb,
    array['meals/photos/bread-fried-egg.png'],
    'breakfast',
    array['gluten', 'egg'],
    array['vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    'eb32746d-6a6b-4da1-85ad-398d8cd50b11',
    'Pão com patê de sardinha',
    'Amasse sardinha em lata com iogurte ou ricota. Passe no pão. Contém glúten, peixe e lactose.',
    '[{"item":"pão","qty":"2 fatias"},{"item":"sardinha em lata","qty":"1/2 lata"},{"item":"iogurte natural ou ricota","qty":"1 colher de sopa"}]'::jsonb,
    array['meals/photos/bread-sardine-pate.png'],
    'breakfast',
    array['gluten', 'fish', 'lactose'],
    array['low-cost'],
    '{}',
    true,
    null
  ),
  (
    '67e50501-928d-43bf-8614-16771bb204e7',
    'Pão com patê de cenoura',
    'Misture cenoura ralada, azeite e orégano. Passe no pão. Contém glúten.',
    '[{"item":"pão","qty":"2 fatias"},{"item":"cenoura ralada","qty":"3 colheres de sopa"},{"item":"azeite","qty":"1 fio"},{"item":"orégano","qty":"a gosto"}]'::jsonb,
    array['meals/photos/bread-carrot-pate.png'],
    'breakfast',
    array['gluten'],
    array['vegan', 'vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    'd7fe228c-628e-495d-8051-210e6e22ae17',
    'Panqueca de banana, aveia e ovo',
    'Amasse banana, misture aveia e ovo. Frite. Contém glúten e ovo.',
    '[{"item":"banana","qty":"1 unidade"},{"item":"aveia em flocos","qty":"2 colheres de sopa"},{"item":"ovo","qty":"1 unidade"}]'::jsonb,
    array['meals/photos/banana-oat-egg-pancake.png'],
    'breakfast',
    array['gluten', 'egg'],
    array['vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    '16daacdf-fafc-4e62-8d5a-d26b2c3ae3a2',
    'Panqueca de maçã, canela, aveia e ovo',
    'Rale a maçã, misture aveia, ovo e canela. Frite. Contém glúten e ovo.',
    '[{"item":"maçã ralada","qty":"1 unidade"},{"item":"aveia em flocos","qty":"2 colheres de sopa"},{"item":"ovo","qty":"1 unidade"},{"item":"canela","qty":"a gosto"}]'::jsonb,
    array['meals/photos/apple-cinnamon-oat-pancake.png'],
    'breakfast',
    array['gluten', 'egg'],
    array['vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    '7b18fa67-0f7d-493b-89eb-5372781c4785',
    'Batata-doce com ovos cozidos',
    'Sirva batata-doce cozida com ovos cozidos temperados.',
    '[{"item":"batata-doce","qty":"1 média"},{"item":"ovos cozidos","qty":"2 unidades"}]'::jsonb,
    array['meals/photos/sweet-potato-boiled-eggs.png'],
    'breakfast',
    array['egg'],
    array['vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    '12485244-e3be-4795-8bac-d895f01a3805',
    'Inhame ou mandioca com azeite e café',
    'Cozinhe inhame ou mandioca. Regue com fio de azeite. Acompanhe café preto.',
    '[{"item":"inhame ou mandioca","qty":"1 porção"},{"item":"azeite","qty":"1 fio"},{"item":"café preto","qty":"1 xícara"}]'::jsonb,
    array['meals/photos/yam-or-cassava-olive-oil-coffee.png'],
    'breakfast',
    '{}',
    array['vegan', 'vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    '76f261f7-f189-4a4c-8f96-b7df0f876526',
    'Vitamina de banana, maçã e aveia',
    'Bata banana, maçã e aveia com água. Contém glúten. Sem leite se preferir.',
    '[{"item":"banana","qty":"1 unidade"},{"item":"maçã","qty":"1/2 unidade"},{"item":"aveia","qty":"1 colher de sopa"},{"item":"água","qty":"200 ml"}]'::jsonb,
    array['meals/photos/banana-apple-oat-smoothie.png'],
    'breakfast',
    array['gluten'],
    array['vegan', 'vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    '581511cf-a103-46a7-8e12-6e12fa7f5b01',
    'Maçã assada com canela e farelo de aveia',
    'Asse a maçã no micro-ondas com canela e farelo de aveia. Contém glúten.',
    '[{"item":"maçã","qty":"1 unidade"},{"item":"canela","qty":"a gosto"},{"item":"farelo de aveia","qty":"1 colher de sopa"}]'::jsonb,
    array['meals/photos/microwave-baked-apple-oat-bran.png'],
    'breakfast',
    array['gluten'],
    array['vegan', 'vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    'd4bb113d-283f-4758-8adb-5b1e7d301f8b',
    'Tapioca com banana e canela',
    'Tapioca fina com banana amassada e canela. Opção sem glúten e vegana. (extra Nutri)',
    '[{"item":"goma de tapioca","qty":"3 colheres de sopa"},{"item":"banana","qty":"1 unidade"},{"item":"canela","qty":"a gosto"}]'::jsonb,
    array['meals/photos/banana-cinnamon-tapioca.png'],
    'breakfast',
    '{}',
    array['vegan', 'vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    'b3d12560-e20c-4f1f-883f-41dd7009bc93',
    'Banana amassada com canela',
    'Amasse a banana com canela. Café rápido sem glúten e sem ovo. (extra Nutri)',
    '[{"item":"banana","qty":"1 a 2 unidades"},{"item":"canela","qty":"a gosto"}]'::jsonb,
    array['meals/photos/banana-mash-no-oats.png'],
    'breakfast',
    '{}',
    array['vegan', 'vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    'cdfd31c5-adc1-4072-88f6-b5c692984d03',
    'Fruta da estação',
    'Banana, maçã, laranja, melancia ou melão in natura.',
    '[{"item":"fruta da estação","qty":"1 porção"}]'::jsonb,
    array['meals/photos/seasonal-fruit.png'],
    'snack',
    '{}',
    array['vegan', 'vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    '2131fbe7-10da-4612-85d8-9dcf3ef1be64',
    'Banana amassada com aveia',
    'Amasse a banana com uma colher de aveia. Contém glúten.',
    '[{"item":"banana","qty":"1 unidade"},{"item":"aveia em flocos","qty":"1 colher de sopa"}]'::jsonb,
    array['meals/photos/mashed-banana-oats.png'],
    'snack',
    array['gluten'],
    array['vegan', 'vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    '66765760-b08c-4d9b-8f18-59786d81f68e',
    'Maçã com pasta de amendoim',
    'Fatias de maçã com pasta de amendoim. Contém amendoim.',
    '[{"item":"maçã","qty":"1 unidade"},{"item":"pasta de amendoim","qty":"1 colher de sopa"}]'::jsonb,
    array['meals/photos/apple-slices-peanut-butter.png'],
    'snack',
    array['peanut'],
    array['vegan', 'vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    'e18feff3-fb93-415a-8ca0-58a30b6753eb',
    'Iogurte natural com chia ou linhaça',
    'Iogurte natural com sementes. Contém lactose.',
    '[{"item":"iogurte natural","qty":"1 pote"},{"item":"chia ou linhaça","qty":"1 colher de chá"}]'::jsonb,
    array['meals/photos/yogurt-chia-flax.png'],
    'snack',
    array['lactose'],
    array['vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    'c7eb1e98-8f68-430f-853f-c923c61a929c',
    'Iogurte natural com farelo de aveia',
    'Iogurte com farelo de aveia. Contém lactose e glúten.',
    '[{"item":"iogurte natural","qty":"1 pote"},{"item":"farelo de aveia","qty":"1 colher de sopa"}]'::jsonb,
    array['meals/photos/yogurt-oat-bran.png'],
    'snack',
    array['lactose', 'gluten'],
    array['vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    'cb3c9127-28c6-4526-8e67-568493b89ca8',
    'Mamão com sementes de abóbora',
    'Meio mamão papaia com sementes de abóbora torradas.',
    '[{"item":"mamão papaia","qty":"1/2 unidade"},{"item":"sementes de abóbora torradas","qty":"1 colher de sopa"}]'::jsonb,
    array['meals/photos/papaya-pumpkin-seeds.png'],
    'snack',
    '{}',
    array['vegan', 'vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    '187c0b51-5777-4180-8428-78bbca074cee',
    'Mix de sementes torradas caseiras',
    'Sementes de abóbora e melão torradas em casa.',
    '[{"item":"sementes de abóbora","qty":"2 colheres de sopa"},{"item":"sementes de melão","qty":"1 colher de sopa"}]'::jsonb,
    array['meals/photos/homemade-toasted-seed-mix.png'],
    'snack',
    '{}',
    array['vegan', 'vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    '2e6d385e-c0c8-44dc-8999-2dc0f54f97ae',
    'Ovo cozido com orégano',
    'Ovo cozido com sal e orégano.',
    '[{"item":"ovo cozido","qty":"1 unidade"},{"item":"orégano","qty":"a gosto"}]'::jsonb,
    array['meals/photos/boiled-egg-oregano.png'],
    'snack',
    array['egg'],
    array['vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    'c39cc0b5-0422-4a98-85b6-f9595b01d146',
    'Ovos de codorna com azeite',
    'Ovos de codorna cozidos com fio de azeite.',
    '[{"item":"ovos de codorna","qty":"4 a 6 unidades"},{"item":"azeite","qty":"1 fio"}]'::jsonb,
    array['meals/photos/quail-eggs-olive-oil.png'],
    'snack',
    array['egg'],
    array['vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    '75e73b4f-7e49-4d67-8336-0e598eab770f',
    'Pedacos de batata-doce fria',
    'Batata-doce cozida resfriada, em pedaços.',
    '[{"item":"batata-doce cozida","qty":"1 porção"}]'::jsonb,
    array['meals/photos/cold-sweet-potato-chunks.png'],
    'snack',
    '{}',
    array['vegan', 'vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    '4d4d9064-dff9-4255-81e1-7e1be2c6a33f',
    'Biscoito de arroz com geleia caseira',
    'Biscoito de arroz com geleia de frutas sem açúcar feita em casa.',
    '[{"item":"biscoito de arroz","qty":"2 unidades"},{"item":"geleia de frutas sem açúcar","qty":"1 colher de sopa"}]'::jsonb,
    array['meals/photos/rice-cake-homemade-jam.png'],
    'snack',
    '{}',
    array['vegan', 'vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    '601f3a94-c9d6-47de-8a4d-0a3a28096526',
    'Cenoura crua em palitos',
    'Cenoura cortada em palitos para lanchar.',
    '[{"item":"cenoura","qty":"1 unidade"}]'::jsonb,
    array['meals/photos/raw-carrot-sticks.png'],
    'snack',
    '{}',
    array['vegan', 'vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    'ae07885b-f2f8-4add-822c-f19c584947c2',
    'Amendoim torrado sem sal',
    'Porção pequena de amendoim torrado sem pele e sem sal.',
    '[{"item":"amendoim torrado sem sal","qty":"1 punhado"}]'::jsonb,
    array['meals/photos/roasted-unsalted-peanuts.png'],
    'snack',
    array['peanut'],
    array['vegan', 'vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    '507087b1-c44a-476d-8a5b-890633d1c4a4',
    'Pipoca caseira na panela',
    'Pipoca feita na panela com fio de óleo.',
    '[{"item":"milho de pipoca","qty":"3 colheres de sopa"},{"item":"óleo","qty":"1 fio"}]'::jsonb,
    array['meals/photos/stovetop-popcorn.png'],
    'snack',
    '{}',
    array['vegan', 'vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    'c6b7f2a2-5bea-4855-8150-776c3f81b773',
    'Bolo de caneca de banana e cacau',
    'Misture banana, ovo, aveia, cacau e fermento. Micro-ondas. Contém glúten e ovo.',
    '[{"item":"banana","qty":"1/2 unidade"},{"item":"ovo","qty":"1 unidade"},{"item":"aveia","qty":"2 colheres de sopa"},{"item":"cacau em pó","qty":"1 colher de chá"},{"item":"fermento","qty":"1 pitada"}]'::jsonb,
    array['meals/photos/mug-cake-banana-cocoa.png'],
    'snack',
    array['gluten', 'egg'],
    array['vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    '78c9fe6e-72dd-48ce-8f00-c359db52c288',
    'Bolo de caneca de maçã com canela',
    'Maçã, ovo, aveia, canela e fermento no micro-ondas. Contém glúten e ovo.',
    '[{"item":"maçã ralada","qty":"1/2 unidade"},{"item":"ovo","qty":"1 unidade"},{"item":"aveia","qty":"2 colheres de sopa"},{"item":"canela","qty":"a gosto"}]'::jsonb,
    array['meals/photos/mug-cake-apple-cinnamon.png'],
    'snack',
    array['gluten', 'egg'],
    array['vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    'ec0a4db0-e773-49ad-8deb-47d586f05f63',
    'Sanduíche de ricota e cenoura',
    'Pão de forma integral com pasta de ricota e cenoura. Contém glúten e lactose.',
    '[{"item":"pão de forma integral","qty":"2 fatias"},{"item":"ricota","qty":"2 colheres de sopa"},{"item":"cenoura ralada","qty":"2 colheres de sopa"}]'::jsonb,
    array['meals/photos/whole-bread-ricotta-carrot.png'],
    'snack',
    array['gluten', 'lactose'],
    array['vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    '7d4006cc-1fd2-4498-8e78-01921999988f',
    'Sanduíche natural de frango',
    'Pão com frango desfiado de sobra do almoço. Contém glúten e carne.',
    '[{"item":"pão","qty":"2 fatias"},{"item":"frango desfiado","qty":"3 colheres de sopa"}]'::jsonb,
    array['meals/photos/leftover-chicken-sandwich.png'],
    'snack',
    array['gluten', 'meat'],
    array['low-cost'],
    '{}',
    true,
    null
  ),
  (
    'bf44c21f-620d-4874-8f91-f799a66e70e3',
    'Pão de queijo de frigideira',
    'Goma, ovo e queijo ralado na frigideira. Contém ovo e lactose.',
    '[{"item":"goma de tapioca","qty":"3 colheres de sopa"},{"item":"ovo","qty":"1 unidade"},{"item":"queijo ralado","qty":"2 colheres de sopa"}]'::jsonb,
    array['meals/photos/skillet-cheese-bread.png'],
    'snack',
    array['egg', 'lactose'],
    array['vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    '6d88e33b-4956-47bd-8ab7-ebe121af04f9',
    'Torradas de pão amanhecido',
    'Pão amanhecido tostado com azeite e orégano. Contém glúten.',
    '[{"item":"pão amanhecido","qty":"2 fatias"},{"item":"azeite","qty":"1 fio"},{"item":"orégano","qty":"a gosto"}]'::jsonb,
    array['meals/photos/stale-bread-toast-oregano.png'],
    'snack',
    array['gluten'],
    array['vegan', 'vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    'd3db2332-8784-4503-8a6f-fed28793d421',
    'Biscoito de arroz com pasta de amendoim',
    'Biscoito de arroz com pasta de amendoim. Contém amendoim.',
    '[{"item":"biscoito de arroz","qty":"2 unidades"},{"item":"pasta de amendoim integral","qty":"1 colher de sopa"}]'::jsonb,
    array['meals/photos/rice-cake-peanut-butter.png'],
    'snack',
    array['peanut'],
    array['vegan', 'vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    'e544f418-bc39-4904-8819-39b0382eeccb',
    'Salada de frutas com mel',
    'Frutas picadas com fio de mel. Não é vegano (mel).',
    '[{"item":"frutas picadas","qty":"1 xícara"},{"item":"mel","qty":"1 fio","alt":"sem mel (versão vegana)"}]'::jsonb,
    array['meals/photos/fruit-salad-honey.png'],
    'snack',
    '{}',
    array['vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    'a1f47e0a-ed1a-4481-81f0-d8b17a6c414c',
    'Smoothie de banana e cacau',
    'Banana congelada batida com cacau e água ou leite. Com leite: lactose.',
    '[{"item":"banana congelada","qty":"1 unidade"},{"item":"cacau em pó","qty":"1 colher de chá"},{"item":"água ou leite","qty":"150 ml","alt":"água (sem lactose)"}]'::jsonb,
    array['meals/photos/frozen-banana-cocoa-smoothie.png'],
    'snack',
    '{}',
    array['vegan', 'vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    '523d0cf7-abe2-4b26-828c-160daf93e097',
    'Palitos de legumes com homus',
    'Pepino e cenoura com pasta de grão-de-bico.',
    '[{"item":"pepino e cenoura","qty":"1 porção"},{"item":"homus de grão-de-bico","qty":"3 colheres de sopa"}]'::jsonb,
    array['meals/photos/veggie-sticks-hummus.png'],
    'snack',
    '{}',
    array['vegan', 'vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    '53f6d664-d3b5-41ea-8959-e4e0f1c3c81f',
    'Palitos de legumes com creme de ricota',
    'Legumes em palito com ricota temperada. Contém lactose.',
    '[{"item":"legumes em palito","qty":"1 porção"},{"item":"ricota temperada","qty":"3 colheres de sopa"}]'::jsonb,
    array['meals/photos/veggie-sticks-ricotta-dip.png'],
    'snack',
    array['lactose'],
    array['vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    'a12f5f15-dbf8-49cd-8de7-8bb54dfa8bc7',
    'Mingau de aveia salgado com ovo',
    'Aveia com água, sal, azeite e ovo mexido. Contém glúten e ovo.',
    '[{"item":"aveia","qty":"3 colheres de sopa"},{"item":"água","qty":"200 ml"},{"item":"ovo","qty":"1 unidade"},{"item":"azeite","qty":"1 fio"}]'::jsonb,
    array['meals/photos/savory-oat-porridge-egg.png'],
    'snack',
    array['gluten', 'egg'],
    array['vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    '45e463e2-b542-4045-8c55-fcdc9fe0f8af',
    'Tapioca com queijo branco',
    'Tapioca fina com queijo branco derretido. Contém lactose.',
    '[{"item":"goma de tapioca","qty":"3 colheres de sopa"},{"item":"queijo branco","qty":"1 fatia"}]'::jsonb,
    array['meals/photos/thin-tapioca-white-cheese.png'],
    'snack',
    array['lactose'],
    array['vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    '34ff8a33-2fb6-450b-8fff-47d63cacc5d3',
    'Sementes de girassol e amendoim',
    'Punhado misto de sementes e amendoim. Contém amendoim.',
    '[{"item":"sementes de girassol","qty":"1 colher de sopa"},{"item":"amendoim","qty":"1 colher de sopa"}]'::jsonb,
    array['meals/photos/sunflower-peanut-handful.png'],
    'snack',
    array['peanut'],
    array['vegan', 'vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    'f38a6e82-8b97-4e40-86f0-139d3be5f94c',
    'Cuscuz de milho com leite morno',
    'Cuscuz levemente umedecido com leite morno. Contém lactose. (também serve no jantar leve)',
    '[{"item":"flocão de milho","qty":"4 colheres de sopa"},{"item":"leite morno","qty":"100 ml","alt":"bebida vegetal"}]'::jsonb,
    array['meals/photos/corn-couscous-warm-milk.png'],
    'snack',
    array['lactose'],
    array['vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    '25c942de-df89-49de-8d17-3b9a5bfc0cbf',
    'Arroz, feijão, frango grelhado e salada',
    'Arroz, feijão carioca, peito de frango grelhado e salada de alface e tomate.',
    '[{"item":"arroz cozido","qty":"4 colheres de sopa"},{"item":"feijão carioca","qty":"1 concha"},{"item":"peito de frango grelhado","qty":"1 filé"},{"item":"alface e tomate","qty":"a gosto"}]'::jsonb,
    array['meals/photos/rice-beans-grilled-chicken-salad.png'],
    'lunch',
    array['meat'],
    array['low-cost'],
    '{}',
    true,
    null
  ),
  (
    'b9d8e91a-b474-40ca-8237-8a8ca5a2f1d4',
    'Arroz, feijão preto, fígado e purê de abóbora',
    'Iscas de fígado acebolado (rico em ferro e acessível) com purê de abóbora.',
    '[{"item":"arroz","qty":"4 colheres de sopa"},{"item":"feijão preto","qty":"1 concha"},{"item":"fígado acebolado","qty":"1 porção"},{"item":"purê de abóbora","qty":"3 colheres de sopa"}]'::jsonb,
    array['meals/photos/rice-black-beans-liver-pumpkin.png'],
    'lunch',
    array['meat'],
    array['low-cost'],
    '{}',
    true,
    null
  ),
  (
    '1c5c9a4e-89ff-46b4-86f5-099a6596f078',
    'Arroz, feijão e carne moída com chuchu',
    'Carne moída refogada com chuchu e cenoura.',
    '[{"item":"arroz","qty":"4 colheres de sopa"},{"item":"feijão","qty":"1 concha"},{"item":"carne moída","qty":"1 xícara"},{"item":"chuchu e cenoura","qty":"1 xícara"}]'::jsonb,
    array['meals/photos/rice-beans-ground-beef-chayote.png'],
    'lunch',
    array['meat'],
    array['low-cost'],
    '{}',
    true,
    null
  ),
  (
    'fea9adaf-28c7-4926-8c5c-07de923d2aea',
    'Arroz, lentilha, lombo e salada de repolho',
    'Tiras de lombo suíno assado com salada de repolho.',
    '[{"item":"arroz","qty":"4 colheres de sopa"},{"item":"lentilha","qty":"1 concha"},{"item":"lombo suíno assado","qty":"1 porção"},{"item":"repolho","qty":"a gosto"}]'::jsonb,
    array['meals/photos/rice-lentils-pork-cabbage.png'],
    'lunch',
    array['meat'],
    array['low-cost'],
    '{}',
    true,
    null
  ),
  (
    '0a847862-f1fd-49cc-8984-682c7a685ed3',
    'Macarrão ao molho de tomate com carne moída',
    'Espaguete com molho caseiro, carne moída e ervilhas. Contém glúten e carne.',
    '[{"item":"macarrão espaguete","qty":"1 porção"},{"item":"molho de tomate caseiro","qty":"1 concha"},{"item":"carne moída","qty":"1/2 xícara"},{"item":"ervilhas","qty":"2 colheres de sopa"}]'::jsonb,
    array['meals/photos/spaghetti-homemade-meat-sauce.png'],
    'lunch',
    array['gluten', 'meat'],
    array['low-cost'],
    '{}',
    true,
    null
  ),
  (
    'fb05b30a-f64b-4522-831b-5c42203c7b66',
    'Macarrão alho e óleo com brócolis e frango',
    'Macarrão com alho, óleo, brócolis, cenoura e tiras de frango. Contém glúten e carne.',
    '[{"item":"macarrão","qty":"1 porção"},{"item":"brócolis e cenoura","qty":"1 xícara"},{"item":"frango em tiras","qty":"1/2 xícara"},{"item":"alho e óleo","qty":"a gosto"}]'::jsonb,
    array['meals/photos/garlic-oil-pasta-broccoli-chicken.png'],
    'lunch',
    array['gluten', 'meat'],
    array['low-cost'],
    '{}',
    true,
    null
  ),
  (
    '83ab12a7-eec8-40e5-840e-d4888f230d79',
    'Macarrão com sardinha e molho de tomate',
    'Macarrão com sardinha, molho e cheiro-verde. Contém glúten e peixe.',
    '[{"item":"macarrão","qty":"1 porção"},{"item":"sardinha","qty":"1 lata pequena"},{"item":"molho de tomate","qty":"1 concha"},{"item":"cheiro-verde","qty":"a gosto"}]'::jsonb,
    array['meals/photos/pasta-sardine-tomato.png'],
    'lunch',
    array['gluten', 'fish'],
    array['low-cost'],
    '{}',
    true,
    null
  ),
  (
    '68fd19ac-f243-4922-8037-e86966eb01a6',
    'Escondidinho de batata-doce com frango',
    'Purê de batata-doce cobrindo frango desfiado.',
    '[{"item":"batata-doce amassada","qty":"2 xícaras"},{"item":"frango desfiado","qty":"1 xícara"}]'::jsonb,
    array['meals/photos/sweet-potato-chicken-shepherd.png'],
    'lunch',
    array['meat'],
    array['low-cost'],
    '{}',
    true,
    null
  ),
  (
    'a822520b-0b2f-41f0-8c8d-d1ef68fffa0b',
    'Escondidinho de mandioca com carne moída',
    'Purê de mandioca com carne moída.',
    '[{"item":"mandioca amassada","qty":"2 xícaras"},{"item":"carne moída","qty":"1 xícara"}]'::jsonb,
    array['meals/photos/cassava-ground-beef-shepherd.png'],
    'lunch',
    array['meat'],
    array['low-cost'],
    '{}',
    true,
    null
  ),
  (
    '2e9fa7e8-80ed-485e-8a17-c39ff76053e7',
    'Panqueca recheada com carne moída',
    'Massa simples de farinha ou aveia recheada com carne. Contém glúten e carne.',
    '[{"item":"farinha ou aveia","qty":"para a massa"},{"item":"ovo","qty":"1 unidade"},{"item":"carne moída","qty":"1 xícara"}]'::jsonb,
    array['meals/photos/savory-pancake-ground-beef.png'],
    'lunch',
    array['gluten', 'meat', 'egg'],
    array['low-cost'],
    '{}',
    true,
    null
  ),
  (
    'c41a81ce-06fe-4868-82b1-3b9165003a43',
    'Panqueca verde com frango e milho',
    'Massa de espinafre recheada com frango e milho. Contém ovo e carne.',
    '[{"item":"espinafre","qty":"1 punhado"},{"item":"ovo","qty":"1 unidade"},{"item":"frango desfiado","qty":"1 xícara"},{"item":"milho","qty":"2 colheres de sopa"}]'::jsonb,
    array['meals/photos/spinach-pancake-chicken-corn.png'],
    'lunch',
    array['egg', 'meat'],
    array['low-cost'],
    '{}',
    true,
    null
  ),
  (
    '2fe19879-4fa3-4193-85a1-6513424fa482',
    'Omelete de legumes com arroz',
    'Omelete de três ovos com espinafre, tomate e cebola, com arroz.',
    '[{"item":"ovos","qty":"3 unidades"},{"item":"espinafre, tomate e cebola","qty":"a gosto"},{"item":"arroz","qty":"3 colheres de sopa"}]'::jsonb,
    array['meals/photos/three-egg-omelette-rice.png'],
    'lunch',
    array['egg'],
    array['vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    'fad9f833-3343-4a6f-8c38-ec6816a7b356',
    'Omelete de forno com sobras de legumes',
    'Legumes cozidos misturados a ovos e assados.',
    '[{"item":"ovos","qty":"3 unidades"},{"item":"legumes cozidos","qty":"1 xícara"}]'::jsonb,
    array['meals/photos/baked-omelette-leftover-veggies.png'],
    'lunch',
    array['egg'],
    array['vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    'f249e1cc-3287-49fd-8a9e-893028ebd5c8',
    'Salada de feijão fradinho com atum',
    'Feijão fradinho, atum, cebola roxa, pimentão e coentro. Contém peixe.',
    '[{"item":"feijão fradinho","qty":"1 xícara"},{"item":"atum em lata","qty":"1 lata pequena"},{"item":"cebola, pimentão e coentro","qty":"a gosto"}]'::jsonb,
    array['meals/photos/black-eyed-pea-tuna-salad.png'],
    'lunch',
    array['fish'],
    array['low-cost'],
    '{}',
    true,
    null
  ),
  (
    'dcd81dea-2fdf-4864-898d-48544524893f',
    'Salada de grão-de-bico com frango',
    'Grão-de-bico, frango desfiado, pepino e tomate.',
    '[{"item":"grão-de-bico","qty":"1 xícara"},{"item":"frango desfiado","qty":"1/2 xícara"},{"item":"pepino e tomate","qty":"a gosto"}]'::jsonb,
    array['meals/photos/chickpea-chicken-salad.png'],
    'lunch',
    array['meat'],
    array['low-cost'],
    '{}',
    true,
    null
  ),
  (
    '39b27655-58a1-4bd1-89cf-02f05e65e037',
    'Baião de dois econômico',
    'Arroz com feijão de corda ou carioca, queijo meia cura e coentro. Contém lactose.',
    '[{"item":"arroz","qty":"1 xícara"},{"item":"feijão","qty":"1 concha"},{"item":"queijo meia cura","qty":"2 colheres de sopa"},{"item":"coentro","qty":"a gosto"}]'::jsonb,
    array['meals/photos/baiao-dois-economico.png'],
    'lunch',
    array['lactose'],
    array['vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    'a5abfb2e-7a12-4c9c-8060-780b8666b054',
    'Arroz de forno com frango',
    'Arroz misturado com frango, cenoura, milho e molho de tomate.',
    '[{"item":"arroz","qty":"2 xícaras"},{"item":"frango desfiado","qty":"1 xícara"},{"item":"cenoura ralada e milho","qty":"1 xícara"},{"item":"molho de tomate","qty":"1/2 xícara"}]'::jsonb,
    array['meals/photos/baked-rice-chicken-carrot.png'],
    'lunch',
    array['meat'],
    array['low-cost'],
    '{}',
    true,
    null
  ),
  (
    'd120da1c-2294-43da-82e4-5fbc4ef2044f',
    'Strogonoff econômico de frango',
    'Frango com creme de ricota ou iogurte no lugar do creme de leite, arroz e salada. Contém carne e lactose.',
    '[{"item":"frango","qty":"1 xícara"},{"item":"ricota ou iogurte","qty":"3 colheres de sopa"},{"item":"arroz","qty":"4 colheres de sopa"},{"item":"salada","qty":"a gosto"}]'::jsonb,
    array['meals/photos/budget-chicken-stroganoff.png'],
    'lunch',
    array['meat', 'lactose'],
    array['low-cost'],
    '{}',
    true,
    null
  ),
  (
    'c7f85706-9b22-409c-8e30-958befc5d2ca',
    'Frango ensopado com batata e cenoura',
    'Frango ensopado com batata inglesa e cenoura, com arroz.',
    '[{"item":"frango","qty":"1 porção"},{"item":"batata e cenoura","qty":"1 xícara"},{"item":"arroz","qty":"4 colheres de sopa"}]'::jsonb,
    array['meals/photos/chicken-stew-potato-carrot.png'],
    'lunch',
    array['meat'],
    array['low-cost'],
    '{}',
    true,
    null
  ),
  (
    'afb5f16b-1c0b-48bf-8d72-b0c1a64d8102',
    'Moela ensopada com mandioca',
    'Moela de frango com mandioca, acompanhada de arroz.',
    '[{"item":"moela de frango","qty":"1 porção"},{"item":"mandioca","qty":"1 xícara"},{"item":"arroz","qty":"4 colheres de sopa"}]'::jsonb,
    array['meals/photos/chicken-gizzard-cassava-stew.png'],
    'lunch',
    array['meat'],
    array['low-cost'],
    '{}',
    true,
    null
  ),
  (
    'efb3d58a-c4ee-4afe-808a-a0d24431f9de',
    'Lombo com repolho e pimentão',
    'Tiras de lombo refogadas com repolho e pimentão, com arroz.',
    '[{"item":"lombo suíno","qty":"1 porção"},{"item":"repolho e pimentão","qty":"2 xícaras"},{"item":"arroz","qty":"4 colheres de sopa"}]'::jsonb,
    array['meals/photos/pork-strips-cabbage-pepper.png'],
    'lunch',
    array['meat'],
    array['low-cost'],
    '{}',
    true,
    null
  ),
  (
    '48ffeac7-cb3b-4bc2-853a-599a427a91f0',
    'Abobrinha recheada com carne moída',
    'Abobrinha assada recheada com carne moída.',
    '[{"item":"abobrinha","qty":"2 unidades"},{"item":"carne moída","qty":"1 xícara"}]'::jsonb,
    array['meals/photos/stuffed-zucchini-beef.png'],
    'lunch',
    array['meat'],
    array['low-cost'],
    '{}',
    true,
    null
  ),
  (
    '9ebebbeb-fa8f-4eef-8bcc-8f01d527843d',
    'Berinjela recheada com frango',
    'Berinjela assada com frango desfiado e tomate.',
    '[{"item":"berinjela","qty":"1 unidade"},{"item":"frango desfiado","qty":"1 xícara"},{"item":"tomate","qty":"1/2 unidade"}]'::jsonb,
    array['meals/photos/stuffed-eggplant-chicken.png'],
    'lunch',
    array['meat'],
    array['low-cost'],
    '{}',
    true,
    null
  ),
  (
    'b25e9151-934c-4f73-8012-6c7024008293',
    'Charuto de repolho com carne e arroz',
    'Folha de repolho recheada com carne moída e arroz.',
    '[{"item":"folhas de repolho","qty":"4 unidades"},{"item":"carne moída","qty":"1 xícara"},{"item":"arroz","qty":"1/2 xícara"}]'::jsonb,
    array['meals/photos/cabbage-roll-beef-rice.png'],
    'lunch',
    array['meat'],
    array['low-cost'],
    '{}',
    true,
    null
  ),
  (
    'ffad26b9-a2c2-4509-89de-974b6830feba',
    'Torta de liquidificador de legumes',
    'Torta de legumes acompanhada de salada verde. Contém ovo e glúten se usar farinha de trigo.',
    '[{"item":"legumes picados","qty":"2 xícaras"},{"item":"ovos","qty":"2 unidades"},{"item":"farinha","qty":"1 xícara"},{"item":"salada verde","qty":"a gosto"}]'::jsonb,
    array['meals/photos/blender-veggie-pie-salad.png'],
    'lunch',
    array['egg', 'gluten'],
    array['vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    '920bc641-49ec-4eb5-8359-3887d86d2339',
    'Salpicão simples com iogurte',
    'Frango, cenoura, milho e iogurte no lugar da maionese, com arroz. Contém carne e lactose.',
    '[{"item":"frango desfiado","qty":"1 xícara"},{"item":"cenoura ralada e milho","qty":"1 xícara"},{"item":"iogurte natural","qty":"3 colheres de sopa"},{"item":"arroz","qty":"4 colheres de sopa"}]'::jsonb,
    array['meals/photos/simple-chicken-salpicao.png'],
    'lunch',
    array['meat', 'lactose'],
    array['low-cost'],
    '{}',
    true,
    null
  ),
  (
    'c6500a80-505c-42ab-808d-023084119ed9',
    'Arroz, feijão e salada',
    'Base vegana do MVP: arroz, feijão e salada crua. (mantido Nutri)',
    '[{"item":"arroz cozido","qty":"4 colheres de sopa"},{"item":"feijão","qty":"1 concha"},{"item":"salada","qty":"a gosto"}]'::jsonb,
    array['meals/photos/rice-beans-salad-vegan.png'],
    'lunch',
    '{}',
    array['vegan', 'vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    'fa40b966-f587-4881-82fb-e0e73b457b45',
    'Sopa de feijão batida com macarrão',
    'Feijão batido com macarrão e sobras de legumes. Contém glúten se o macarrão for de trigo.',
    '[{"item":"feijão cozido","qty":"2 conchas"},{"item":"macarrão","qty":"1/2 xícara"},{"item":"legumes","qty":"1 xícara"}]'::jsonb,
    array['meals/photos/blended-bean-soup-pasta.png'],
    'dinner',
    array['gluten'],
    array['vegan', 'vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    'f445e88e-558a-4b1b-8903-349224296d8e',
    'Caldo verde leve com frango',
    'Caldo verde sem embutidos pesados: frango desfiado, batata e couve.',
    '[{"item":"frango desfiado","qty":"1/2 xícara"},{"item":"batata","qty":"2 unidades"},{"item":"couve","qty":"1 xícara"}]'::jsonb,
    array['meals/photos/light-caldo-verde-chicken.png'],
    'dinner',
    array['meat'],
    array['low-cost'],
    '{}',
    true,
    null
  ),
  (
    'f89b9362-2d58-4297-812d-e09bbfe30776',
    'Caldo de abóbora com gengibre e frango',
    'Creme de abóbora com gengibre e frango desfiado.',
    '[{"item":"abóbora","qty":"2 xícaras"},{"item":"gengibre","qty":"a gosto"},{"item":"frango desfiado","qty":"1/2 xícara"}]'::jsonb,
    array['meals/photos/pumpkin-ginger-chicken-soup.png'],
    'dinner',
    array['meat'],
    array['low-cost'],
    '{}',
    true,
    null
  ),
  (
    '115af1ea-071e-46fa-88eb-0ab35d37018a',
    'Creme de mandioca com carne moída',
    'Creme de mandioca com carne moída.',
    '[{"item":"mandioca","qty":"2 xícaras"},{"item":"carne moída","qty":"1/2 xícara"}]'::jsonb,
    array['meals/photos/cassava-cream-ground-beef.png'],
    'dinner',
    array['meat'],
    array['low-cost'],
    '{}',
    true,
    null
  ),
  (
    '62b95f2f-e4df-4042-8d92-9e32c0f7050d',
    'Sopa de lentilha com cenoura e batata',
    'Sopa de lentilha com raízes. Vegana.',
    '[{"item":"lentilha","qty":"1 xícara"},{"item":"cenoura e batata","qty":"1 xícara"}]'::jsonb,
    array['meals/photos/lentil-carrot-potato-soup.png'],
    'dinner',
    '{}',
    array['vegan', 'vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    '4ee3174e-faea-4800-8dfa-3a74d865448e',
    'Salada de folhas com ovo cozido',
    'Folhas, ovo cozido, tomate e cebola.',
    '[{"item":"folhas verdes","qty":"2 xícaras"},{"item":"ovo cozido","qty":"1 a 2 unidades"},{"item":"tomate e cebola","qty":"a gosto"}]'::jsonb,
    array['meals/photos/leafy-salad-boiled-egg.png'],
    'dinner',
    array['egg'],
    array['vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    'd7911018-4618-4a2f-8731-31c8dd642bf0',
    'Salada completa com frango e legumes',
    'Tiras de frango de sobra com legumes cozidos.',
    '[{"item":"frango em tiras","qty":"1/2 xícara"},{"item":"legumes cozidos","qty":"1 xícara"},{"item":"folhas","qty":"a gosto"}]'::jsonb,
    array['meals/photos/leftover-chicken-veggie-salad.png'],
    'dinner',
    array['meat'],
    array['low-cost'],
    '{}',
    true,
    null
  ),
  (
    '348f7fe8-da0f-4bc2-82f3-2b4db096b542',
    'Wrap de couve com carne moída',
    'Folha grande de couve crua recheada com carne moída.',
    '[{"item":"folha de couve","qty":"2 unidades"},{"item":"carne moída","qty":"1/2 xícara"}]'::jsonb,
    array['meals/photos/kale-wrap-ground-beef.png'],
    'dinner',
    array['meat'],
    array['low-cost'],
    '{}',
    true,
    null
  ),
  (
    'fb45e8e3-6984-46f7-8bda-6d2091cf452e',
    'Wrap de couve com frango e ricota',
    'Couve recheada com frango, cenoura e ricota. Contém carne e lactose.',
    '[{"item":"folha de couve","qty":"2 unidades"},{"item":"frango","qty":"1/2 xícara"},{"item":"cenoura","qty":"2 colheres de sopa"},{"item":"ricota","qty":"2 colheres de sopa"}]'::jsonb,
    array['meals/photos/kale-wrap-chicken-ricotta.png'],
    'dinner',
    array['meat', 'lactose'],
    array['low-cost'],
    '{}',
    true,
    null
  ),
  (
    '93ad4bee-ef03-4fc9-8273-e31feca265b8',
    'Ovos mexidos com pão torrado',
    'Ovos mexidos com tomate, cebola, pimentão e pão torrado. Contém ovo e glúten.',
    '[{"item":"ovos","qty":"2 unidades"},{"item":"tomate, cebola e pimentão","qty":"a gosto"},{"item":"pão torrado","qty":"1 fatia"}]'::jsonb,
    array['meals/photos/scrambled-eggs-toast-dinner.png'],
    'dinner',
    array['egg', 'gluten'],
    array['vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    '608e11c6-f8af-4365-8f67-17a94eb1e4d7',
    'Ovos no molho de tomate',
    'Ovos pochê ou cozidos no molho de tomate (shakshuka simples).',
    '[{"item":"ovos","qty":"2 unidades"},{"item":"molho de tomate","qty":"1 xícara"}]'::jsonb,
    array['meals/photos/simple-shakshuka.png'],
    'dinner',
    array['egg'],
    array['vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    'f034247f-3862-4beb-8db3-20b1bb5f909b',
    'Suflê de chuchu ou abobrinha',
    'Legumes misturados com ovos batidos e assados.',
    '[{"item":"chuchu ou abobrinha","qty":"2 xícaras"},{"item":"ovos","qty":"3 unidades"}]'::jsonb,
    array['meals/photos/chayote-or-zucchini-souffle.png'],
    'dinner',
    array['egg'],
    array['vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    '438756b6-342f-4572-84a2-f2c159689190',
    'Hambúrguer caseiro com salada',
    'Hambúrguer só com carne e temperos, no prato com salada grande (sem pão).',
    '[{"item":"carne moída","qty":"120 g"},{"item":"salada grande","qty":"a gosto"}]'::jsonb,
    array['meals/photos/homemade-beef-burger-salad.png'],
    'dinner',
    array['meat'],
    array['low-cost'],
    '{}',
    true,
    null
  ),
  (
    '19dbdd95-6d77-427e-89b6-70ee0d886aa3',
    'Hambúrguer de frango com purê',
    'Frango processado com aveia e cebola, com purê de batata. Contém carne e glúten.',
    '[{"item":"frango","qty":"120 g"},{"item":"aveia","qty":"1 colher de sopa"},{"item":"purê de batata","qty":"1/2 xícara"}]'::jsonb,
    array['meals/photos/homemade-chicken-burger-mash.png'],
    'dinner',
    array['meat', 'gluten'],
    array['low-cost'],
    '{}',
    true,
    null
  ),
  (
    '205d7d5b-1dad-4c11-81d8-44b738768f2d',
    'Pizza de frigideira na tortilha',
    'Tortilha com molho de tomate e queijo branco. Contém lactose; glúten se a tortilha for de trigo.',
    '[{"item":"tortilha","qty":"1 unidade","alt":"tortilha de milho"},{"item":"molho de tomate","qty":"2 colheres de sopa"},{"item":"queijo branco","qty":"2 fatias"}]'::jsonb,
    array['meals/photos/tortilla-skillet-pizza.png'],
    'dinner',
    array['lactose', 'gluten'],
    array['vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    'ecca07a1-793c-4245-8172-7910497d70aa',
    'Frango com espinafre e arroz',
    'Frango desfiado refogado com espinafre e arroz.',
    '[{"item":"frango desfiado","qty":"1 xícara"},{"item":"espinafre","qty":"1 xícara"},{"item":"arroz","qty":"3 colheres de sopa"}]'::jsonb,
    array['meals/photos/shredded-chicken-spinach-rice.png'],
    'dinner',
    array['meat'],
    array['low-cost'],
    '{}',
    true,
    null
  ),
  (
    'd87ce55c-a7ca-43b0-89b0-7d5292764154',
    'Iscas de lombo com salada quente',
    'Lombo com repolho e cenoura refogados.',
    '[{"item":"lombo de porco","qty":"1 porção"},{"item":"repolho e cenoura","qty":"2 xícaras"}]'::jsonb,
    array['meals/photos/pork-strips-warm-cabbage-salad.png'],
    'dinner',
    array['meat'],
    array['low-cost'],
    '{}',
    true,
    null
  ),
  (
    '5561271b-0308-4d01-81b8-2ecd14647d8a',
    'Tomate recheado com ovo assado',
    'Tomate sem miolo, recheado com ovo e assado.',
    '[{"item":"tomate grande","qty":"1 unidade"},{"item":"ovo","qty":"1 unidade"}]'::jsonb,
    array['meals/photos/baked-tomato-egg.png'],
    'dinner',
    array['egg'],
    array['vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    '94cf95d5-47a0-4cc4-83c5-5da54a8ac8cb',
    'Salada de repolho, maçã e frango',
    'Repolho roxo e branco, maçã, molho de iogurte e frango. Contém carne e lactose.',
    '[{"item":"repolho","qty":"2 xícaras"},{"item":"maçã","qty":"1/2 unidade"},{"item":"iogurte natural","qty":"2 colheres de sopa"},{"item":"frango em cubos","qty":"1/2 xícara"}]'::jsonb,
    array['meals/photos/cabbage-apple-yogurt-chicken-salad.png'],
    'dinner',
    array['meat', 'lactose'],
    array['low-cost'],
    '{}',
    true,
    null
  ),
  (
    '63cfc81d-66b5-438d-8289-e56df7892d82',
    'Sopa só de legumes',
    'Batata, cenoura, abóbora e folhas em caldo leve. Opção vegana sem glúten. (extra Nutri)',
    '[{"item":"batata, cenoura e abóbora","qty":"3 xícaras"},{"item":"folhas","qty":"1 xícara"},{"item":"água","qty":"o suficiente"}]'::jsonb,
    array['meals/photos/vegetable-only-soup.png'],
    'dinner',
    '{}',
    array['vegan', 'vegetarian', 'low-cost'],
    '{}',
    true,
    null
  ),
  (
    'fbbbb4c0-28bd-4aeb-853c-3ef9ec06d996',
    'Feijão com purê de abóbora',
    'Concha de feijão com purê de abóbora. Jantar vegano denso e barato. (extra Nutri)',
    '[{"item":"feijão","qty":"1 concha"},{"item":"purê de abóbora","qty":"1 xícara"}]'::jsonb,
    array['meals/photos/beans-pumpkin-puree-plate.png'],
    'dinner',
    '{}',
    array['vegan', 'vegetarian', 'low-cost'],
    '{}',
    true,
    null
  )
on conflict (id) do update
set
  title = excluded.title,
  description = excluded.description,
  ingredients = excluded.ingredients,
  image_paths = excluded.image_paths,
  meal_slot = excluded.meal_slot,
  contains_tags = excluded.contains_tags,
  diet_compatible_tags = excluded.diet_compatible_tags,
  phase_tags = excluded.phase_tags,
  is_published = excluded.is_published,
  updated_at = now();

