-- purpose: full low-cost exercise library seed (Educador Físico review).
-- affected: tags, exercises_library
-- notes: generated from lib/admin/exercise-seed-catalog*.ts
--   upsert by fixed uuid from slug. titles/descriptions pt-BR.

insert into public.tags (slug, domain, kind, label)
values
  ('resistance-band', 'movement', 'equipment', 'Elástico'),
  ('broomstick', 'movement', 'equipment', 'Cabo de vassoura'),
  ('backpack', 'movement', 'equipment', 'Mochila'),
  ('cushion', 'movement', 'equipment', 'Almofada')
on conflict (slug) do update
set domain = excluded.domain, kind = excluded.kind, label = excluded.label;

delete from public.exercises_library
where id in (
  'a1000000-0000-4000-8000-000000000001',
  'a1000000-0000-4000-8000-000000000002',
  'a1000000-0000-4000-8000-000000000003',
  'a1000000-0000-4000-8000-000000000004',
  'a1000000-0000-4000-8000-000000000005',
  'a1000000-0000-4000-8000-000000000006',
  'a1000000-0000-4000-8000-000000000007',
  'a1000000-0000-4000-8000-000000000008'
);

insert into public.exercises_library (
  id, title, description, image_paths, video_url, target_muscles,
  equipment_tags, contraindication_tags, required_capability_tags,
  intensity_tags, is_published, created_by
)
values
  (
    'a4529e30-5fa2-461c-855a-bdc548c927c7',
    'Agachamento tradicional',
    'Pés na largura dos ombros. Desça o quadril como se fosse sentar, mantendo o peito aberto, e suba com controle. Amplitude confortável.',
    '{}',
    null,
    array['legs', 'glutes'],
    array['bodyweight'],
    array['chondromalacia', 'torn-pcl', 'knee-osteoarthritis', 'femoroacetabular-impingement'],
    array['standing', 'low-impact'],
    array['low-intensity', 'deep-knee-flexion'],
    true,
    null
  ),
  (
    'c7e2cd90-3a67-41cb-86bd-470023e6103d',
    'Agachamento sumô',
    'Pés mais abertos e pontas levemente para fora. Desça o quadril e suba. Pode segurar uma garrafa ou mochila no peito.',
    '{}',
    null,
    array['legs', 'glutes'],
    array['bodyweight', 'bottle', 'backpack'],
    array['chondromalacia', 'torn-pcl', 'knee-osteoarthritis', 'femoroacetabular-impingement', 'collateral-ligament-injury', 'torn-acl', 'ankle-ligament-sprain', 'chronic-muscle-strain'],
    array['standing', 'low-impact'],
    array['low-intensity', 'deep-knee-flexion', 'knee-lateral-force'],
    true,
    null
  ),
  (
    '4d4700a1-e0bd-4c25-8e6e-ce498c9481d9',
    'Agachamento isométrico',
    'Desça até uma altura confortável e mantenha a posição sem se mover. Respire sem prender o ar. Saia da posição se houver tontura.',
    '{}',
    null,
    array['legs', 'glutes'],
    array['bodyweight'],
    array['chondromalacia', 'torn-pcl', 'knee-osteoarthritis', 'femoroacetabular-impingement', 'hypertension'],
    array['standing', 'low-impact'],
    array['low-intensity', 'deep-knee-flexion'],
    true,
    null
  ),
  (
    '99e9323c-5ed7-4414-83ab-046d27d1213a',
    'Agachamento unilateral assistido (pistol)',
    'Apoie-se em um cabo de vassoura ou cadeira. Desça em uma perna com a outra à frente, só até onde houver controle. Sem forçar o joelho.',
    '{}',
    null,
    array['legs', 'glutes'],
    array['bodyweight', 'broomstick', 'chair'],
    array['chondromalacia', 'torn-pcl', 'knee-osteoarthritis', 'femoroacetabular-impingement', 'knee-osteoarthritis', 'lower-limb-amputation-unilateral', 'torn-acl', 'torn-pcl', 'patellar-tendinopathy', 'knee-osteoarthritis', 'chondromalacia'],
    array['standing', 'unilateral'],
    array['medium-intensity', 'deep-knee-flexion', 'unilateral-full-load'],
    true,
    null
  ),
  (
    '174207e3-e81a-4cbf-8d37-dc2b0aa6c92c',
    'Agachamento cossaco',
    'Em postura ampla, desça o peso para um lado flexionando um joelho e mantendo a outra perna mais estendida. Troque de lado com calma.',
    '{}',
    null,
    array['legs', 'glutes'],
    array['bodyweight'],
    array['collateral-ligament-injury', 'torn-acl', 'ankle-ligament-sprain', 'chondromalacia', 'torn-pcl', 'knee-osteoarthritis', 'femoroacetabular-impingement', 'piriformis-syndrome', 'femoroacetabular-impingement'],
    array['standing'],
    array['medium-intensity', 'deep-knee-flexion', 'knee-lateral-force', 'deep-hip-flexion'],
    true,
    null
  ),
  (
    'df25b5ed-e826-49bc-8288-68a5cf0415c8',
    'Agachamento camarão',
    'Segure um pé atrás do corpo e desça o joelho de trás em direção ao solo, com apoio se precisar. Movimento avançado — use assistência.',
    '{}',
    null,
    array['legs', 'glutes'],
    array['bodyweight', 'chair'],
    array['chondromalacia', 'torn-pcl', 'knee-osteoarthritis', 'femoroacetabular-impingement', 'torn-acl', 'torn-pcl', 'patellar-tendinopathy', 'knee-osteoarthritis', 'chondromalacia', 'knee-osteoarthritis', 'lower-limb-amputation-unilateral'],
    array['standing', 'unilateral'],
    array['high-intensity', 'deep-knee-flexion', 'unilateral-full-load'],
    true,
    null
  ),
  (
    '04020eda-4114-46b4-8a88-580f71762fb7',
    'Agachamento sissy',
    'Incline o tronco para trás enquanto flexiona os joelhos, mantendo quadril avançado. Amplitude curta e controlada. Alto estresse no joelho.',
    '{}',
    null,
    array['legs'],
    array['bodyweight'],
    array['chondromalacia', 'torn-pcl', 'knee-osteoarthritis', 'femoroacetabular-impingement', 'chondromalacia', 'patellar-tendinopathy', 'torn-acl'],
    array['standing'],
    array['high-intensity', 'deep-knee-flexion'],
    true,
    null
  ),
  (
    '10921525-e39d-4e1f-8a58-4296addd06d6',
    'Agachamento sapo',
    'Pés abertos, desça o quadril e apoie os cotovelos nas coxas se quiser. Suba empurrando o chão. Mantenha a coluna confortável.',
    '{}',
    null,
    array['legs', 'glutes', 'core'],
    array['bodyweight'],
    array['chondromalacia', 'torn-pcl', 'knee-osteoarthritis', 'femoroacetabular-impingement', 'femoroacetabular-impingement'],
    array['standing', 'low-impact'],
    array['low-intensity', 'deep-knee-flexion', 'deep-hip-flexion'],
    true,
    null
  ),
  (
    'c3fc0ba1-6207-47d7-8ce4-9f2dc0889173',
    'Agachamento com insistência (pulsos)',
    'Desça até a metade do agachamento e faça pequenos movimentos de sobe-desce sem estender totalmente. Pode usar elástico.',
    '{}',
    null,
    array['legs', 'glutes'],
    array['bodyweight', 'resistance-band'],
    array['chondromalacia', 'torn-pcl', 'knee-osteoarthritis', 'femoroacetabular-impingement'],
    array['standing', 'low-impact'],
    array['medium-intensity', 'deep-knee-flexion'],
    true,
    null
  ),
  (
    '9a24c328-5450-4dd1-8a8a-646eaa59389f',
    'Agachamento com salto',
    'Agache e estenda as pernas em um salto suave, aterrissando com joelhos flexionados. Evite se houver dor ou instabilidade.',
    '{}',
    null,
    array['legs', 'glutes'],
    array['bodyweight'],
    array['torn-acl', 'patellar-tendinopathy', 'knee-osteoarthritis', 'plantar-fasciitis', 'osteoporosis-osteopenia', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'labyrinthitis', 'hemiplegia-hemiparesis', 'cerebral-palsy-mild-moderate', 'visual-impairment'],
    array['standing'],
    array['high-intensity', 'high-impact', 'lower-body-plyometrics'],
    true,
    null
  ),
  (
    '24c5fbaa-9da0-40e9-8694-338e323c045a',
    'Agachamento abre e fecha (pop squat)',
    'Salte abrindo e fechando as pernas entre as descidas. Movimento rápido — priorize controle na aterrissagem.',
    '{}',
    null,
    array['legs', 'glutes'],
    array['bodyweight'],
    array['torn-acl', 'patellar-tendinopathy', 'knee-osteoarthritis', 'plantar-fasciitis', 'osteoporosis-osteopenia', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'labyrinthitis', 'hemiplegia-hemiparesis', 'cerebral-palsy-mild-moderate', 'visual-impairment', 'collateral-ligament-injury', 'torn-acl', 'ankle-ligament-sprain'],
    array['standing'],
    array['high-intensity', 'high-impact', 'lower-body-plyometrics', 'knee-lateral-force', 'spatial-travel'],
    true,
    null
  ),
  (
    'be9117c6-3428-4254-8713-d4ced66de3c6',
    'Agachamento cálice (goblet squat)',
    'Segure um garrafão ou pacote junto ao peito e agache. O peso à frente ajuda a postura. Amplitude confortável.',
    '{}',
    null,
    array['legs', 'glutes', 'core'],
    array['bottle', 'food-bag', 'bodyweight'],
    array['chondromalacia', 'torn-pcl', 'knee-osteoarthritis', 'femoroacetabular-impingement'],
    array['standing', 'low-impact'],
    array['low-intensity', 'deep-knee-flexion'],
    true,
    null
  ),
  (
    'ea7afbeb-a559-42d7-8714-6ad30e3cc4ea',
    'Agachamento lastreado',
    'Use uma mochila preenchida nas costas ou no peito e execute o agachamento tradicional com controle.',
    '{}',
    null,
    array['legs', 'glutes'],
    array['backpack', 'bodyweight'],
    array['chondromalacia', 'torn-pcl', 'knee-osteoarthritis', 'femoroacetabular-impingement', 'disc-herniation', 'hernia', 'spondylolisthesis', 'osteoporosis-osteopenia'],
    array['standing', 'low-impact'],
    array['medium-intensity', 'deep-knee-flexion', 'axial-load'],
    true,
    null
  ),
  (
    '1c1a9b68-5e23-4092-8ca2-79de0e27bc2a',
    'Agachamento instável',
    'Agache descalço sobre uma almofada firme, com apoio próximo se precisar. Priorize equilíbrio, não profundidade.',
    '{}',
    null,
    array['legs', 'glutes'],
    array['cushion', 'bodyweight'],
    array['chondromalacia', 'torn-pcl', 'knee-osteoarthritis', 'femoroacetabular-impingement', 'ankle-ligament-sprain', 'labyrinthitis', 'visual-impairment'],
    array['standing'],
    array['low-intensity', 'unstable-base', 'deep-knee-flexion'],
    true,
    null
  ),
  (
    '65b6e883-c0a9-4901-8833-81f3a32b242d',
    'Agachamento búlgaro',
    'Apoie o peito do pé de trás em uma cadeira e desça o joelho da frente. Tronco ereto, movimento lento.',
    '{}',
    null,
    array['legs', 'glutes'],
    array['chair', 'bodyweight'],
    array['chondromalacia', 'torn-pcl', 'knee-osteoarthritis', 'femoroacetabular-impingement', 'knee-osteoarthritis', 'lower-limb-amputation-unilateral', 'torn-pcl'],
    array['standing', 'unilateral'],
    array['medium-intensity', 'deep-knee-flexion', 'unilateral-full-load', 'tibial-posterior-load'],
    true,
    null
  ),
  (
    '3b1798ca-a6f6-4930-8bc4-2b547c10e7df',
    'Agachamento com super band',
    'Pise sobre um elástico longo e segure as pontas nos ombros ou mãos. Agache contra a resistência.',
    '{}',
    null,
    array['legs', 'glutes'],
    array['resistance-band', 'bodyweight'],
    array['chondromalacia', 'torn-pcl', 'knee-osteoarthritis', 'femoroacetabular-impingement'],
    array['standing', 'low-impact'],
    array['medium-intensity', 'deep-knee-flexion'],
    true,
    null
  ),
  (
    '2cd1c0ad-f67b-4cef-8fd0-4a9feacc0f47',
    'Afundo tradicional',
    'Dê um passo à frente e desça o joelho de trás em direção ao solo. Empurre para voltar. Pode usar garrafas.',
    '{}',
    null,
    array['legs', 'glutes'],
    array['bodyweight', 'bottle'],
    array['chondromalacia', 'torn-pcl', 'knee-osteoarthritis', 'femoroacetabular-impingement', 'torn-acl', 'torn-pcl', 'patellar-tendinopathy', 'knee-osteoarthritis', 'chondromalacia', 'visual-impairment'],
    array['standing'],
    array['medium-intensity', 'deep-knee-flexion', 'spatial-travel'],
    true,
    null
  ),
  (
    '35338f11-4e2c-4792-8f2c-c5e93520acce',
    'Afundo reverso',
    'Dê um passo para trás e desça o joelho de trás com controle. Volte à posição inicial sem balançar o tronco.',
    '{}',
    null,
    array['legs', 'glutes'],
    array['bodyweight'],
    array['chondromalacia', 'torn-pcl', 'knee-osteoarthritis', 'femoroacetabular-impingement', 'torn-pcl'],
    array['standing'],
    array['medium-intensity', 'deep-knee-flexion', 'tibial-posterior-load'],
    true,
    null
  ),
  (
    '3a8188ae-38fb-4f46-86e9-7c9cf0b60ee7',
    'Afundo lateral',
    'Dê um passo para o lado e sente o quadril sobre a perna que avançou, mantendo a outra mais estendida.',
    '{}',
    null,
    array['legs', 'glutes'],
    array['bodyweight'],
    array['collateral-ligament-injury', 'torn-acl', 'ankle-ligament-sprain', 'femoroacetabular-impingement'],
    array['standing'],
    array['medium-intensity', 'knee-lateral-force', 'deep-hip-flexion', 'spatial-travel'],
    true,
    null
  ),
  (
    '614d7ec5-1d3a-4e58-84d0-27b9b52d3460',
    'Afundo pendular',
    'Alterne afundo à frente e atrás com a mesma perna, como um pêndulo, sem pausa longa no meio.',
    '{}',
    null,
    array['legs', 'glutes'],
    array['bodyweight'],
    array['torn-acl', 'torn-pcl', 'patellar-tendinopathy', 'knee-osteoarthritis', 'chondromalacia', 'labyrinthitis', 'hemiplegia-hemiparesis'],
    array['standing'],
    array['medium-intensity', 'deep-knee-flexion', 'high-speed', 'spatial-travel'],
    true,
    null
  ),
  (
    'b00bf0ff-7e18-4dd1-83c3-5d021e719f8c',
    'Afundo com insistência',
    'Fique na posição de afundo e faça pequenos pulsos sem estender totalmente as pernas.',
    '{}',
    null,
    array['legs', 'glutes'],
    array['bodyweight'],
    array['chondromalacia', 'torn-pcl', 'knee-osteoarthritis', 'femoroacetabular-impingement'],
    array['standing', 'low-impact'],
    array['medium-intensity', 'deep-knee-flexion'],
    true,
    null
  ),
  (
    '9ae70a56-0ae7-4b6a-83eb-a8604a2c5c57',
    'Afundo com salto',
    'Alterne as pernas com um salto entre os afundos. Aterrise macio. Evite se houver dor no joelho ou tornozelo.',
    '{}',
    null,
    array['legs', 'glutes'],
    array['bodyweight'],
    array['torn-acl', 'patellar-tendinopathy', 'knee-osteoarthritis', 'plantar-fasciitis', 'osteoporosis-osteopenia', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'labyrinthitis', 'hemiplegia-hemiparesis', 'cerebral-palsy-mild-moderate', 'visual-impairment'],
    array['standing'],
    array['high-intensity', 'high-impact', 'lower-body-plyometrics', 'spatial-travel'],
    true,
    null
  ),
  (
    '34212438-c891-4f61-8d07-c5e3e2a40c88',
    'Passada (caminhada em afundo)',
    'Avance o espaço fazendo afundos sucessivos. Passos curtos e estáveis. Pode carregar garrafas.',
    '{}',
    null,
    array['legs', 'glutes'],
    array['bodyweight', 'bottle'],
    array['chondromalacia', 'torn-pcl', 'knee-osteoarthritis', 'femoroacetabular-impingement', 'visual-impairment', 'labyrinthitis'],
    array['standing'],
    array['medium-intensity', 'deep-knee-flexion', 'spatial-travel'],
    true,
    null
  ),
  (
    '635d6a6f-c250-4e26-846c-ec536de3c9c0',
    'Avanço cruzado (curtsy lunge)',
    'Leve uma perna para trás cruzando atrás da outra e desça o joelho com controle. Volte sem torcer o joelho da frente.',
    '{}',
    null,
    array['legs', 'glutes'],
    array['bodyweight'],
    array['collateral-ligament-injury', 'torn-acl', 'ankle-ligament-sprain', 'torn-acl', 'piriformis-syndrome'],
    array['standing'],
    array['medium-intensity', 'knee-lateral-force', 'deep-hip-flexion', 'rotational-instability'],
    true,
    null
  ),
  (
    '5e7c8a73-f2fd-48e4-8085-80f1d8482657',
    'Elevação pélvica (ponte)',
    'Deite de costas, joelhos flexionados. Eleve o quadril alinhando ombros e joelhos. Pode usar elástico ou pacote no quadril.',
    '{}',
    null,
    array['glutes', 'core'],
    array['bodyweight', 'resistance-band', 'food-bag'],
    '{}',
    array['lying', 'low-impact'],
    array['low-intensity'],
    true,
    null
  ),
  (
    'b145eec6-2533-4870-8bd4-35626d2c258e',
    'Elevação pélvica unilateral',
    'Na ponte, estenda uma perna e eleve o quadril com a outra. Troque os lados. Amplitude controlada.',
    '{}',
    null,
    array['glutes', 'core'],
    array['bodyweight'],
    array['knee-osteoarthritis', 'lower-limb-amputation-unilateral'],
    array['lying', 'unilateral', 'low-impact'],
    array['medium-intensity', 'unilateral-full-load'],
    true,
    null
  ),
  (
    '817328cc-bc72-4d84-8406-faed6a8c85d1',
    'Elevação pélvica com amplitude',
    'Apoie os pés em uma cadeira e eleve o quadril. Evite arquear demais a lombar.',
    '{}',
    null,
    array['glutes', 'legs', 'core'],
    array['chair', 'bodyweight'],
    array['spondylolisthesis', 'spinal-stenosis', 'disc-herniation'],
    array['lying', 'low-impact'],
    array['medium-intensity'],
    true,
    null
  ),
  (
    'eadfec12-131c-4989-8d6e-b0ed2999ce8c',
    'Bomba de sapo (frog pump)',
    'Deite de costas com as solas dos pés juntas e joelhos abertos. Eleve o quadril em impulsos curtos.',
    '{}',
    null,
    array['glutes'],
    array['bodyweight'],
    array['piriformis-syndrome', 'femoroacetabular-impingement', 'trochanteric-bursitis'],
    array['lying', 'low-impact'],
    array['low-intensity', 'deep-hip-flexion'],
    true,
    null
  ),
  (
    '7dc112d3-d066-4315-8e21-ddc0597af349',
    'Stiff / levantamento terra',
    'Com elástico ou garrafas, incline o tronco com joelhos levemente flexionados e coluna neutra. Suba empurrando o chão com os calcanhares.',
    '{}',
    null,
    array['glutes', 'legs', 'back'],
    array['resistance-band', 'bottle', 'bodyweight'],
    array['disc-herniation', 'hernia', 'spondylolisthesis', 'chronic-muscle-strain', 'osteoporosis-osteopenia'],
    array['standing', 'low-impact'],
    array['medium-intensity', 'max-range-stretch', 'axial-load'],
    true,
    null
  ),
  (
    '18b4ddd5-f81e-4c77-84d8-7bc54e297835',
    'Mesa flexora deslizante',
    'Deite de costas com os calcanhares sobre uma toalha em piso liso. Eleve o quadril e deslize os pés para longe e de volta.',
    '{}',
    null,
    array['legs', 'glutes'],
    array['towel', 'bodyweight'],
    array['chronic-muscle-strain'],
    array['lying', 'low-impact'],
    array['medium-intensity'],
    true,
    null
  ),
  (
    '3ca074f7-8f39-4b8a-810a-f5dddfe72c3c',
    'Flexão de perna em pé (isquiotibiais)',
    'Ancore um elástico e flexione o joelho trazendo o calcanhar ao glúteo. Controle a volta.',
    '{}',
    null,
    array['legs'],
    array['resistance-band'],
    array['chronic-muscle-strain'],
    array['standing', 'unilateral', 'low-impact'],
    array['low-intensity'],
    true,
    null
  ),
  (
    '43d7af7c-ae52-4e3c-807e-65c6d185465b',
    'Extensão de quadril (coice) em quatro apoios',
    'Em quatro apoios, estenda uma perna para trás sem arquear a lombar. Pode usar elástico. Apoie os punhos de forma neutra se houver desconforto.',
    '{}',
    null,
    array['glutes'],
    array['bodyweight', 'resistance-band'],
    array['pregnancy-trimester-2', 'pregnancy-trimester-3', 'carpal-tunnel-de-quervain', 'tfcc-injury', 'rheumatoid-arthritis'],
    array['lying', 'low-impact'],
    array['low-intensity', 'wrist-extension-load'],
    true,
    null
  ),
  (
    '51726f8a-becd-4158-8114-ace81abe5874',
    'Abdução de quadril em quatro apoios (fire hydrant)',
    'Em quatro apoios, eleve o joelho para o lado mantendo o quadril estável. Evite girar demais a coluna.',
    '{}',
    null,
    array['glutes'],
    array['bodyweight', 'resistance-band'],
    array['trochanteric-bursitis', 'piriformis-syndrome', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'carpal-tunnel-de-quervain', 'tfcc-injury', 'rheumatoid-arthritis'],
    array['lying', 'low-impact'],
    array['low-intensity', 'side-lying-pressure', 'wrist-extension-load'],
    true,
    null
  ),
  (
    '8555be14-76a5-4b2d-8c35-ac47e6ab0ed0',
    'Abdução de quadril em pé',
    'Em pé, com elástico nos tornozelos ou coxas, afaste uma perna para o lado sem inclinar o tronco.',
    '{}',
    null,
    array['glutes'],
    array['resistance-band', 'bodyweight'],
    array['trochanteric-bursitis'],
    array['standing', 'unilateral', 'low-impact'],
    array['low-intensity'],
    true,
    null
  ),
  (
    '790a99ea-b649-4840-8511-5bb6daeb6e8e',
    'Ostra (clamshells)',
    'Deite de lado com joelhos flexionados e abra o joelho de cima mantendo os pés juntos. Use colchão macio sob o quadril.',
    '{}',
    null,
    array['glutes'],
    array['bodyweight', 'resistance-band', 'cushion'],
    array['trochanteric-bursitis', 'piriformis-syndrome'],
    array['lying', 'low-impact'],
    array['low-intensity', 'side-lying-pressure'],
    true,
    null
  ),
  (
    '955add04-8118-47b9-89ae-490646a01cc1',
    'Caminhada lateral (monster walk)',
    'Com elástico nas pernas, caminhe lateralmente em semi-agachamento. Passos curtos e controlados.',
    '{}',
    null,
    array['glutes', 'legs'],
    array['resistance-band'],
    array['collateral-ligament-injury', 'torn-acl', 'ankle-ligament-sprain', 'visual-impairment'],
    array['standing'],
    array['medium-intensity', 'knee-lateral-force', 'spatial-travel'],
    true,
    null
  ),
  (
    '248bf262-ddf6-46f6-82da-a87a63496f9c',
    'Bom dia (good morning)',
    'Com cabo de vassoura nas costas, incline o tronco à frente mantendo a coluna neutra e joelhos levemente flexionados.',
    '{}',
    null,
    array['back', 'glutes', 'legs'],
    array['broomstick', 'bodyweight'],
    array['disc-herniation', 'hernia', 'spondylolisthesis', 'osteoporosis-osteopenia'],
    array['standing', 'low-impact'],
    array['low-intensity', 'axial-load', 'max-range-stretch'],
    true,
    null
  ),
  (
    '06dbbcfb-d5d2-475f-84d1-1f1febd8956b',
    'Cadeirinha isométrica (wall sit)',
    'Encoste as costas na parede e desça até um ângulo confortável de joelhos. Segure por poucos segundos e suba.',
    '{}',
    null,
    array['legs'],
    array['wall', 'bodyweight'],
    array['chondromalacia', 'torn-pcl', 'knee-osteoarthritis', 'femoroacetabular-impingement', 'hypertension'],
    array['standing', 'low-impact'],
    array['low-intensity', 'deep-knee-flexion'],
    true,
    null
  ),
  (
    '8ff75a53-d59e-4a58-83d8-f7c09ff6f36f',
    'Caminhada do pato',
    'Em agachamento baixo, caminhe para frente com passos curtos. Só use se a amplitude for confortável.',
    '{}',
    null,
    array['legs', 'glutes'],
    array['bodyweight'],
    array['chondromalacia', 'torn-pcl', 'knee-osteoarthritis', 'femoroacetabular-impingement', 'visual-impairment', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'labyrinthitis'],
    array['standing'],
    array['high-intensity', 'deep-knee-flexion', 'spatial-travel'],
    true,
    null
  ),
  (
    'f0192e92-75c1-42bd-8123-401cd3e19e4a',
    'Subida no banco (step-up)',
    'Suba em uma cadeira estável com uma perna e desça com controle. Pode usar mochila. Confira se a cadeira aguenta o peso.',
    '{}',
    null,
    array['legs', 'glutes'],
    array['chair', 'backpack', 'bodyweight'],
    array['knee-osteoarthritis', 'lower-limb-amputation-unilateral', 'torn-acl', 'torn-pcl', 'patellar-tendinopathy', 'knee-osteoarthritis', 'chondromalacia', 'pregnancy-trimester-3'],
    array['standing', 'unilateral'],
    array['medium-intensity', 'unilateral-full-load'],
    true,
    null
  ),
  (
    '4ef78f98-8784-45c4-8b0f-f2de30d566cd',
    'Elevação de panturrilha em pé',
    'Suba na ponta dos pés e desça com controle. Pode usar mochila ou garrafas. Sem salto.',
    '{}',
    null,
    array['legs'],
    array['bodyweight', 'backpack', 'bottle'],
    array['plantar-fasciitis', 'ankle-ligament-sprain'],
    array['standing', 'low-impact'],
    array['low-intensity', 'forefoot-impact'],
    true,
    null
  ),
  (
    '4c362df5-53d1-42a3-8cf4-ad2e8ae5c199',
    'Elevação de panturrilha unilateral',
    'Apoie-se se precisar e eleve o corpo na ponta de um pé. Troque os lados.',
    '{}',
    null,
    array['legs'],
    array['bodyweight'],
    array['plantar-fasciitis', 'ankle-ligament-sprain'],
    array['standing', 'unilateral', 'low-impact'],
    array['low-intensity', 'forefoot-impact', 'unilateral-full-load'],
    true,
    null
  ),
  (
    'ebd3d29e-49f3-413b-843c-65a6c0360e98',
    'Elevação de panturrilha com insistência',
    'Na ponta dos pés, faça pequenos pulsos sem apoiar todo o pé no chão.',
    '{}',
    null,
    array['legs'],
    array['bodyweight'],
    array['plantar-fasciitis'],
    array['standing', 'low-impact'],
    array['medium-intensity', 'forefoot-impact'],
    true,
    null
  ),
  (
    '1e4e9256-2962-44f5-8905-6168d642aa66',
    'Salto de panturrilha',
    'Pequenos saltos só com a panturrilha, aterrissando macio na ponta dos pés.',
    '{}',
    null,
    array['legs'],
    array['bodyweight'],
    array['torn-acl', 'patellar-tendinopathy', 'knee-osteoarthritis', 'plantar-fasciitis', 'osteoporosis-osteopenia', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'labyrinthitis', 'hemiplegia-hemiparesis', 'cerebral-palsy-mild-moderate', 'visual-impairment', 'plantar-fasciitis'],
    array['standing'],
    array['high-intensity', 'lower-body-plyometrics', 'forefoot-impact', 'high-impact'],
    true,
    null
  ),
  (
    '43e3b176-1c4c-46e1-8fbe-ff4e1d0a7f12',
    'Flexão de braços tradicional',
    'Mãos no chão na linha dos ombros, corpo alinhado. Desça o peito e empurre o chão. Joelhos no solo se precisar regressar.',
    '{}',
    null,
    array['chest', 'arms', 'core'],
    array['bodyweight'],
    array['carpal-tunnel-de-quervain', 'tfcc-injury', 'rheumatoid-arthritis', 'shoulder-instability', 'slap-tear', 'ac-joint-injury', 'ac-joint-injury'],
    array['lying', 'low-impact'],
    array['medium-intensity', 'floor-push', 'bilateral-push-up', 'wrist-extension-load'],
    true,
    null
  ),
  (
    '04b300ac-80a6-4db9-8ab8-9c8e75739654',
    'Flexão com joelhos apoiados',
    'Mesma linha de flexão com joelhos no solo. Mantém o tronco firme sem deixar o quadril cair.',
    '{}',
    null,
    array['chest', 'arms', 'core'],
    array['bodyweight'],
    array['carpal-tunnel-de-quervain', 'tfcc-injury', 'rheumatoid-arthritis', 'shoulder-instability', 'slap-tear', 'ac-joint-injury'],
    array['lying', 'low-impact'],
    array['low-intensity', 'floor-push', 'bilateral-push-up', 'wrist-extension-load'],
    true,
    null
  ),
  (
    '22a47d33-b934-499f-8aa4-ad9762b2ac7b',
    'Flexão diamante',
    'Mãos próximas formando um diamante sob o peito. Desça e empurre com controle.',
    '{}',
    null,
    array['arms', 'chest'],
    array['bodyweight'],
    array['carpal-tunnel-de-quervain', 'tfcc-injury', 'rheumatoid-arthritis', 'epicondylitis', 'elbow-ucl-injury', 'olecranon-bursitis'],
    array['lying'],
    array['high-intensity', 'floor-push', 'wrist-extension-load', 'prolonged-grip'],
    true,
    null
  ),
  (
    'd9c44890-7cee-4100-8a15-ecc872df8306',
    'Flexão aberta',
    'Mãos mais afastadas que os ombros. Desça o peito entre as mãos sem forçar o ombro.',
    '{}',
    null,
    array['chest', 'shoulders'],
    array['bodyweight'],
    array['shoulder-instability', 'slap-tear', 'ac-joint-injury', 'carpal-tunnel-de-quervain', 'tfcc-injury', 'rheumatoid-arthritis'],
    array['lying'],
    array['medium-intensity', 'floor-push', 'wide-arm-tension', 'wrist-extension-load'],
    true,
    null
  ),
  (
    '3e896eee-0134-4fa4-8035-4919eba34b26',
    'Flexão declinada',
    'Pés na cadeira e mãos no chão. Aumenta a demanda de ombros — use só com base estável.',
    '{}',
    null,
    array['chest', 'shoulders', 'arms'],
    array['chair', 'bodyweight'],
    array['rotator-cuff-injury', 'subacromial-bursitis', 'shoulder-instability', 'carpal-tunnel-de-quervain', 'tfcc-injury', 'rheumatoid-arthritis', 'pregnancy-trimester-3'],
    array['lying'],
    array['high-intensity', 'floor-push', 'overhead-press', 'wrist-extension-load'],
    true,
    null
  ),
  (
    '1b1bac00-e0e2-44e8-8fd8-b590190c7002',
    'Flexão inclinada',
    'Mãos na cadeira e pés no chão. Boa regressão da flexão tradicional.',
    '{}',
    null,
    array['chest', 'arms', 'core'],
    array['chair', 'bodyweight'],
    array['carpal-tunnel-de-quervain', 'tfcc-injury', 'rheumatoid-arthritis', 'upper-limb-amputation-unilateral'],
    array['standing', 'low-impact'],
    array['low-intensity', 'floor-push'],
    true,
    null
  ),
  (
    'c02bc932-0be4-491a-8b43-083bd1150262',
    'Flexão pike',
    'Quadril elevado formando um V invertido. Flexione os cotovelos levando a cabeça ao chão entre as mãos.',
    '{}',
    null,
    array['shoulders', 'arms'],
    array['bodyweight'],
    array['rotator-cuff-injury', 'subacromial-bursitis', 'shoulder-instability', 'carpal-tunnel-de-quervain', 'tfcc-injury', 'rheumatoid-arthritis', 'pregnancy-trimester-2', 'pregnancy-trimester-3'],
    array['lying'],
    array['high-intensity', 'overhead-press', 'wrist-extension-load'],
    true,
    null
  ),
  (
    '0cbf40c6-aae5-4361-8f40-328c61804749',
    'Flexão pike na parede',
    'Pés na parede e mãos no chão em pike. Desça a cabeça com controle. Exige equilíbrio.',
    '{}',
    null,
    array['shoulders', 'arms'],
    array['wall', 'bodyweight'],
    array['rotator-cuff-injury', 'subacromial-bursitis', 'shoulder-instability', 'carpal-tunnel-de-quervain', 'tfcc-injury', 'rheumatoid-arthritis', 'hypertension', 'labyrinthitis', 'pregnancy-trimester-2', 'pregnancy-trimester-3'],
    array['lying'],
    array['high-intensity', 'overhead-press', 'inversion', 'wrist-extension-load'],
    true,
    null
  ),
  (
    'b4fbe1c1-c34e-4c17-8085-49aa488d8c61',
    'Flexão assimétrica',
    'Uma mão em apoio mais alto (livro ou degrau baixo) e a outra no chão. Alternar lados.',
    '{}',
    null,
    array['chest', 'arms', 'core'],
    array['bodyweight'],
    array['carpal-tunnel-de-quervain', 'tfcc-injury', 'rheumatoid-arthritis', 'shoulder-instability', 'slap-tear', 'ac-joint-injury'],
    array['lying', 'unilateral'],
    array['medium-intensity', 'floor-push', 'wrist-extension-load'],
    true,
    null
  ),
  (
    '09f276c3-98af-4290-87fa-ec68dcab9d44',
    'Flexão arqueiro',
    'Em flexão, desloque o peito para um braço enquanto o outro permanece mais estendido. Avançado.',
    '{}',
    null,
    array['chest', 'arms'],
    array['bodyweight'],
    array['shoulder-instability', 'slap-tear', 'ac-joint-injury', 'carpal-tunnel-de-quervain', 'tfcc-injury', 'rheumatoid-arthritis'],
    array['lying', 'unilateral'],
    array['high-intensity', 'wide-arm-tension', 'floor-push', 'wrist-extension-load'],
    true,
    null
  ),
  (
    'd6ebb4db-6cd3-4ace-8ab7-5bd52b625566',
    'Flexão máquina de escrever',
    'Na posição baixa da flexão, deslize o peito de um lado para o outro antes de subir.',
    '{}',
    null,
    array['chest', 'arms', 'core'],
    array['bodyweight'],
    array['shoulder-instability', 'slap-tear', 'ac-joint-injury', 'carpal-tunnel-de-quervain', 'tfcc-injury', 'rheumatoid-arthritis', 'ac-joint-injury'],
    array['lying'],
    array['high-intensity', 'wide-arm-tension', 'floor-push', 'wrist-extension-load'],
    true,
    null
  ),
  (
    '2e63dfdd-c187-4940-8b65-c1165cae8959',
    'Flexão homem-aranha',
    'A cada descida, leve um joelho em direção ao cotovelo do mesmo lado. Alterne.',
    '{}',
    null,
    array['chest', 'core', 'arms'],
    array['bodyweight'],
    array['carpal-tunnel-de-quervain', 'tfcc-injury', 'rheumatoid-arthritis', 'femoroacetabular-impingement'],
    array['lying'],
    array['medium-intensity', 'floor-push', 'deep-hip-flexion', 'wrist-extension-load'],
    true,
    null
  ),
  (
    '1cfe53af-be71-49c2-8551-17e5885f1929',
    'Flexão hindu / dive bomber',
    'Do pike, desça o peito em um arco passando para extensão da coluna. Evite se houver dor lombar.',
    '{}',
    null,
    array['chest', 'shoulders', 'back', 'core'],
    array['bodyweight'],
    array['spondylolisthesis', 'spinal-stenosis', 'disc-herniation', 'carpal-tunnel-de-quervain', 'tfcc-injury', 'rheumatoid-arthritis', 'rotator-cuff-injury', 'subacromial-bursitis', 'shoulder-instability'],
    array['lying'],
    array['high-intensity', 'spine-hyperextension', 'floor-push', 'wrist-extension-load'],
    true,
    null
  ),
  (
    '549d4c00-9ec2-4511-87a0-59bc6916d410',
    'Flexão pseudo-planche',
    'Mãos mais abaixo do peito, inclinando o ombro à frente. Extremamente avançado — amplitude curta.',
    '{}',
    null,
    array['shoulders', 'arms', 'core'],
    array['bodyweight'],
    array['carpal-tunnel-de-quervain', 'tfcc-injury', 'rheumatoid-arthritis', 'shoulder-instability', 'slap-tear', 'ac-joint-injury', 'elbow-ucl-injury'],
    array['lying'],
    array['high-intensity', 'wrist-extension-load', 'floor-push'],
    false,
    null
  ),
  (
    '8b21c1e5-dfea-417c-8f72-619eaa1fce05',
    'Flexão pliométrica (com palmas)',
    'Empurre o chão com força suficiente para bater palmas e aterrissar com cotovelos macios.',
    '{}',
    null,
    array['chest', 'arms'],
    array['bodyweight'],
    array['carpal-tunnel-de-quervain', 'tfcc-injury', 'rheumatoid-arthritis', 'shoulder-instability', 'slap-tear', 'ac-joint-injury', 'labyrinthitis', 'torn-acl', 'patellar-tendinopathy', 'knee-osteoarthritis', 'plantar-fasciitis', 'osteoporosis-osteopenia', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'labyrinthitis', 'hemiplegia-hemiparesis', 'cerebral-palsy-mild-moderate', 'visual-impairment'],
    array['lying'],
    array['high-intensity', 'high-impact', 'high-speed', 'floor-push', 'wrist-extension-load'],
    true,
    null
  ),
  (
    '59a91f47-a120-45f3-8977-f071a39978cd',
    'Flexão esfinge',
    'Dos antebraços, estenda os cotovelos até a prancha alta e volte. Controle o punho e o ombro.',
    '{}',
    null,
    array['arms', 'shoulders', 'core'],
    array['bodyweight'],
    array['epicondylitis', 'elbow-ucl-injury', 'olecranon-bursitis', 'carpal-tunnel-de-quervain', 'tfcc-injury', 'rheumatoid-arthritis', 'olecranon-bursitis'],
    array['lying', 'low-impact'],
    array['medium-intensity', 'forearm-plank-hard', 'wrist-extension-load'],
    true,
    null
  ),
  (
    '13b2c43c-cd5f-4fbe-82a6-41b8a094d285',
    'Flexão deslizante lateral',
    'Com uma mão sobre toalha em piso liso, deslize para o lado na descida e volte.',
    '{}',
    null,
    array['chest', 'arms', 'core'],
    array['towel', 'bodyweight'],
    array['shoulder-instability', 'slap-tear', 'ac-joint-injury', 'carpal-tunnel-de-quervain', 'tfcc-injury', 'rheumatoid-arthritis'],
    array['lying'],
    array['medium-intensity', 'wide-arm-tension', 'floor-push', 'wrist-extension-load'],
    true,
    null
  ),
  (
    '8d31f4af-e0d1-46c8-8891-51f91663e611',
    'Flexão lastreada',
    'Flexão tradicional com mochila preenchida nas costas. Carga leve e controle total.',
    '{}',
    null,
    array['chest', 'arms', 'core'],
    array['backpack', 'bodyweight'],
    array['carpal-tunnel-de-quervain', 'tfcc-injury', 'rheumatoid-arthritis', 'shoulder-instability', 'slap-tear', 'ac-joint-injury', 'osteoporosis-osteopenia'],
    array['lying'],
    array['high-intensity', 'floor-push', 'wrist-extension-load', 'axial-load'],
    true,
    null
  ),
  (
    'ebc3eb51-e8a5-49bf-8fa8-a3af975502ac',
    'Flexão de braços resistida',
    'Passe um elástico longo pelas costas e sob as mãos. Execute a flexão contra a resistência.',
    '{}',
    null,
    array['chest', 'arms'],
    array['resistance-band', 'bodyweight'],
    array['carpal-tunnel-de-quervain', 'tfcc-injury', 'rheumatoid-arthritis', 'shoulder-instability', 'slap-tear', 'ac-joint-injury'],
    array['lying'],
    array['medium-intensity', 'floor-push', 'wrist-extension-load'],
    true,
    null
  ),
  (
    '6bbd511f-41b4-4ba4-867f-392ad7b9d883',
    'Supino no chão (floor press)',
    'Deite de costas e empurre garrafas ou pacotes do peito para cima até estender os cotovelos.',
    '{}',
    null,
    array['chest', 'arms'],
    array['bottle', 'food-bag', 'bodyweight'],
    array['shoulder-instability', 'slap-tear', 'ac-joint-injury', 'shoulder-instability'],
    array['lying', 'low-impact'],
    array['low-intensity'],
    true,
    null
  ),
  (
    'b45bb731-a0b0-4302-802e-de4881e88935',
    'Crucifixo no solo',
    'Deite de costas e abra os braços com garrafas ou elástico, depois una à frente do peito sem forçar o ombro.',
    '{}',
    null,
    array['chest'],
    array['bottle', 'food-bag', 'resistance-band'],
    array['shoulder-instability', 'slap-tear', 'ac-joint-injury', 'ac-joint-injury'],
    array['lying', 'low-impact'],
    array['low-intensity', 'wide-arm-tension', 'cross-body-load'],
    true,
    null
  ),
  (
    '2f902563-38a2-4d66-84f4-d07ed117b666',
    'Remada curvada bilateral',
    'Tronco inclinado com coluna neutra. Puxe elástico ou garrafas em direção ao tronco e solte com controle.',
    '{}',
    null,
    array['back', 'arms'],
    array['resistance-band', 'bottle', 'bodyweight'],
    array['disc-herniation', 'hernia', 'spondylolisthesis'],
    array['standing', 'low-impact'],
    array['medium-intensity'],
    true,
    null
  ),
  (
    'a32f1ab4-cac2-429c-88aa-4b4b94e50c99',
    'Remada unilateral (serrote)',
    'Apoie uma mão e um joelho na cadeira. Puxe o peso com o outro braço até o tronco.',
    '{}',
    null,
    array['back', 'arms'],
    array['chair', 'bottle', 'backpack'],
    array['upper-limb-amputation-unilateral'],
    array['standing', 'unilateral', 'low-impact'],
    array['medium-intensity'],
    true,
    null
  ),
  (
    '6a195661-158f-48f5-85dc-5c6fd4f0f746',
    'Remada sentada',
    'Sente-se e puxe um elástico ancorado à frente em direção ao tronco, aproximando as omoplatas.',
    '{}',
    null,
    array['back', 'arms'],
    array['resistance-band', 'chair'],
    '{}',
    array['seated', 'low-impact'],
    array['low-intensity', 'active-pause'],
    true,
    null
  ),
  (
    '84c1df51-a467-471f-804a-46bf8ee2a0cd',
    'Puxada alta',
    'Ancore o elástico no alto e puxe as mãos em direção aos ombros. Controle a subida.',
    '{}',
    null,
    array['back', 'arms'],
    array['resistance-band'],
    array['slap-tear', 'shoulder-instability', 'rotator-cuff-injury'],
    array['standing', 'seated', 'low-impact'],
    array['medium-intensity', 'hanging-traction'],
    true,
    null
  ),
  (
    '8b238d79-5ef6-47ca-8175-3e694a5b8632',
    'Anjo de neve invertido',
    'Deite de bruços e deslize os braços do lado do corpo até acima da cabeça, sem dor no ombro.',
    '{}',
    null,
    array['back', 'shoulders'],
    array['bodyweight'],
    array['pregnancy-trimester-2', 'pregnancy-trimester-3', 'rotator-cuff-injury', 'subacromial-bursitis', 'shoulder-instability'],
    array['lying', 'low-impact'],
    array['low-intensity', 'prone-position'],
    true,
    null
  ),
  (
    '3b20a252-f498-4eb9-88ef-e09d196055b4',
    'Puxada de costas no solo',
    'Deite de bruços e puxe os cotovelos para trás apertando as omoplatas. Solte com calma.',
    '{}',
    null,
    array['back'],
    array['bodyweight'],
    array['pregnancy-trimester-2', 'pregnancy-trimester-3'],
    array['lying', 'low-impact'],
    array['low-intensity', 'prone-position'],
    true,
    null
  ),
  (
    'f01d0b05-2a56-447c-8bf6-db674ffe96d0',
    'Extensão de tronco (superman)',
    'Deite de bruços e eleve levemente braços e pernas. Amplitude pequena. Pare se houver dor lombar.',
    '{}',
    null,
    array['back', 'glutes'],
    array['bodyweight'],
    array['spondylolisthesis', 'spinal-stenosis', 'disc-herniation', 'pregnancy-trimester-2', 'pregnancy-trimester-3'],
    array['lying', 'low-impact'],
    array['low-intensity', 'prone-position', 'spine-hyperextension'],
    true,
    null
  ),
  (
    '7eebc5e8-08ea-423d-84ac-9861b71319b1',
    'Pullover no solo',
    'Deite de costas e leve um pacote ou garrafão de cima da cabeça até o peito, com cotovelos semi-flexionados.',
    '{}',
    null,
    array['back', 'chest'],
    array['food-bag', 'bottle'],
    array['rotator-cuff-injury', 'subacromial-bursitis', 'shoulder-instability', 'slap-tear'],
    array['lying', 'low-impact'],
    array['low-intensity'],
    true,
    null
  ),
  (
    '1f9fbfc3-8ca6-42c4-82ce-00a3f73a166d',
    'Desenvolvimento de ombros',
    'Em pé ou sentado, empurre garrafas ou elástico acima da cabeça até estender os cotovelos sem arquear a lombar.',
    '{}',
    null,
    array['shoulders', 'arms'],
    array['resistance-band', 'bottle', 'chair'],
    array['rotator-cuff-injury', 'subacromial-bursitis', 'shoulder-instability'],
    array['standing', 'seated', 'low-impact'],
    array['medium-intensity', 'overhead-press', 'lateral-raise-above-90'],
    true,
    null
  ),
  (
    'bfaa14af-eb1c-4798-812f-b60c0389e416',
    'Elevação lateral',
    'Eleve os braços ao lado até no máximo a linha dos ombros. Evite subir acima de 90 graus se houver dor.',
    '{}',
    null,
    array['shoulders'],
    array['resistance-band', 'bottle', 'food-bag'],
    array['rotator-cuff-injury', 'subacromial-bursitis', 'shoulder-instability'],
    array['standing', 'seated', 'low-impact'],
    array['low-intensity', 'lateral-raise-above-90'],
    true,
    null
  ),
  (
    '621c4d71-ee07-4b0e-8b1e-ee6f7ef34f6d',
    'Elevação frontal',
    'Eleve os braços à frente até a linha dos ombros e desça com controle.',
    '{}',
    null,
    array['shoulders'],
    array['resistance-band', 'bottle', 'food-bag'],
    array['rotator-cuff-injury', 'subacromial-bursitis', 'shoulder-instability'],
    array['standing', 'seated', 'low-impact'],
    array['low-intensity', 'lateral-raise-above-90'],
    true,
    null
  ),
  (
    'cef854b7-86a8-497c-8f0f-6ac8d92106ca',
    'Afastamento peitoral (pull-apart)',
    'Segure o elástico à frente e afaste as mãos abrindo o peito, apertando as omoplatas.',
    '{}',
    null,
    array['shoulders', 'back'],
    array['resistance-band'],
    array['ac-joint-injury'],
    array['standing', 'seated', 'low-impact'],
    array['low-intensity', 'active-pause'],
    true,
    null
  ),
  (
    '553981fd-b368-41e2-8288-372d2c55f585',
    'Isometria em cruz no solo',
    'Deite de bruços com braços abertos em T e mantenha uma leve elevação dos braços.',
    '{}',
    null,
    array['shoulders', 'back'],
    array['bodyweight'],
    array['pregnancy-trimester-2', 'pregnancy-trimester-3', 'shoulder-instability', 'slap-tear', 'ac-joint-injury'],
    array['lying', 'low-impact'],
    array['low-intensity', 'prone-position', 'wide-arm-tension'],
    true,
    null
  ),
  (
    '2fe33432-2b8d-4b4f-84f1-b464f1620ecf',
    'Mergulho no solo (tríceps dip no chão)',
    'Sentado no chão com mãos atrás do corpo, eleve o quadril e flexione os cotovelos. Amplitude curta.',
    '{}',
    null,
    array['arms'],
    array['bodyweight'],
    array['carpal-tunnel-de-quervain', 'tfcc-injury', 'rheumatoid-arthritis', 'epicondylitis', 'elbow-ucl-injury', 'olecranon-bursitis'],
    array['lying', 'seated', 'low-impact'],
    array['low-intensity', 'wrist-extension-load'],
    true,
    null
  ),
  (
    '4beb20eb-7602-46b0-8f7d-f5bf4fe7d35e',
    'Mergulho em cadeira/banco',
    'Mãos na beira da cadeira, desça o corpo flexionando os cotovelos e empurre para subir. Pés no chão.',
    '{}',
    null,
    array['arms', 'shoulders'],
    array['chair', 'bodyweight'],
    array['carpal-tunnel-de-quervain', 'tfcc-injury', 'rheumatoid-arthritis', 'epicondylitis', 'elbow-ucl-injury', 'olecranon-bursitis', 'shoulder-instability'],
    array['seated', 'standing', 'low-impact'],
    array['medium-intensity', 'wrist-extension-load'],
    true,
    null
  ),
  (
    '7d76305b-348d-4220-8d12-2eeccec609e8',
    'Tríceps francês',
    'Segure garrafa ou elástico acima da cabeça e flexione só o cotovelo, levando o peso atrás da cabeça.',
    '{}',
    null,
    array['arms'],
    array['resistance-band', 'bottle'],
    array['epicondylitis', 'elbow-ucl-injury', 'olecranon-bursitis', 'rotator-cuff-injury', 'subacromial-bursitis', 'shoulder-instability'],
    array['standing', 'seated', 'low-impact'],
    array['low-intensity', 'overhead-press'],
    true,
    null
  ),
  (
    '25d4aa1b-e1f5-4e30-88de-5e08bb5fd94c',
    'Tríceps coice (kickback)',
    'Tronco inclinado, cotovelo fixo ao lado do corpo. Estenda o antebraço para trás com garrafa ou elástico.',
    '{}',
    null,
    array['arms'],
    array['resistance-band', 'bottle'],
    array['epicondylitis', 'elbow-ucl-injury', 'olecranon-bursitis'],
    array['standing', 'low-impact'],
    array['low-intensity'],
    true,
    null
  ),
  (
    'e7bd0351-8f56-4b9e-8cc4-5b1e3b3d54ad',
    'Tríceps pulley',
    'Ancore o elástico no alto e estenda os cotovelos para baixo, mantendo os braços junto ao tronco.',
    '{}',
    null,
    array['arms'],
    array['resistance-band'],
    array['epicondylitis', 'elbow-ucl-injury', 'olecranon-bursitis'],
    array['standing', 'seated', 'low-impact'],
    array['low-intensity'],
    true,
    null
  ),
  (
    '9512d49d-885d-436f-8082-e9fab95895e0',
    'Rosca direta',
    'Segure garrafas ou elástico e flexione os cotovelos levando as mãos aos ombros. Controle a descida.',
    '{}',
    null,
    array['arms'],
    array['resistance-band', 'bottle'],
    array['epicondylitis', 'elbow-ucl-injury', 'olecranon-bursitis', 'rheumatoid-arthritis'],
    array['standing', 'seated', 'low-impact'],
    array['low-intensity', 'prolonged-grip'],
    true,
    null
  ),
  (
    'ab76b38f-54b7-4aa5-89a3-ab6f31d22617',
    'Rosca martelo',
    'Como a rosca direta, mas com as palmas voltadas uma para a outra (garrafas em posição neutra).',
    '{}',
    null,
    array['arms'],
    array['bottle'],
    array['epicondylitis', 'elbow-ucl-injury', 'olecranon-bursitis'],
    array['standing', 'seated', 'low-impact'],
    array['low-intensity', 'prolonged-grip'],
    true,
    null
  ),
  (
    '3b6c2a7b-aa88-44cb-8a0d-77854f584fb5',
    'Flexão de pulso invertida no solo',
    'Apoio com dorso das mãos no solo (ou punhos neutros em suportes). Só para quem não tem dor no punho.',
    '{}',
    null,
    array['arms'],
    array['bodyweight'],
    array['carpal-tunnel-de-quervain', 'tfcc-injury', 'rheumatoid-arthritis'],
    array['lying'],
    array['low-intensity', 'wrist-extension-load'],
    false,
    null
  ),
  (
    'b49602f2-ae55-4f3d-8edd-5df7197edb73',
    'Prancha frontal isométrica',
    'Antebraços e pontas dos pés no solo, corpo alinhado. Segure poucos segundos. Joelho no solo se precisar.',
    '{}',
    null,
    array['core'],
    array['bodyweight'],
    array['diastasis-recti', 'athletic-pubalgia', 'olecranon-bursitis', 'hypertension'],
    array['lying', 'low-impact'],
    array['low-intensity', 'forearm-plank-hard', 'high-intra-abdominal-pressure'],
    true,
    null
  ),
  (
    '2f9bb67b-4a4a-4180-871b-48feca482bdd',
    'Prancha instável',
    'Prancha com antebraços sobre almofada firme. Priorize estabilidade, não tempo longo.',
    '{}',
    null,
    array['core'],
    array['cushion', 'bodyweight'],
    array['diastasis-recti', 'athletic-pubalgia', 'labyrinthitis'],
    array['lying', 'low-impact'],
    array['medium-intensity', 'unstable-base', 'high-intra-abdominal-pressure'],
    true,
    null
  ),
  (
    '5c1894da-9411-4df2-8358-ab70e80025ad',
    'Prancha lateral isométrica',
    'Apoie um antebraço e a lateral do pé. Quadril elevado. Troque de lado. Use joelho no solo para regressão.',
    '{}',
    null,
    array['core'],
    array['bodyweight'],
    array['trochanteric-bursitis', 'olecranon-bursitis', 'diastasis-recti', 'athletic-pubalgia'],
    array['lying', 'unilateral', 'low-impact'],
    array['low-intensity', 'forearm-plank-hard', 'side-lying-pressure'],
    true,
    null
  ),
  (
    '852db82d-6f18-4174-84ae-a61b225aaab5',
    'Prancha lateral com mergulho de quadril',
    'Na prancha lateral, abaixe e eleve o quadril com controle sem perder o alinhamento.',
    '{}',
    null,
    array['core'],
    array['bodyweight'],
    array['trochanteric-bursitis', 'diastasis-recti', 'athletic-pubalgia'],
    array['lying', 'unilateral'],
    array['medium-intensity', 'side-lying-pressure'],
    true,
    null
  ),
  (
    '3acddcaa-2888-4e15-8fb6-7420ca8d019f',
    'Prancha com toque nos ombros',
    'Em prancha alta, toque o ombro oposto com a mão alternando lados, sem girar o quadril.',
    '{}',
    null,
    array['core', 'shoulders'],
    array['bodyweight'],
    array['carpal-tunnel-de-quervain', 'tfcc-injury', 'rheumatoid-arthritis', 'diastasis-recti', 'athletic-pubalgia'],
    array['lying'],
    array['medium-intensity', 'wrist-extension-load', 'floor-push'],
    true,
    null
  ),
  (
    'c504a8f8-aa8d-48d8-8f49-6edd1bd9ec6e',
    'Prancha comando (sobe e desce)',
    'Alternee entre prancha de antebraços e prancha alta, um braço de cada vez.',
    '{}',
    null,
    array['core', 'arms'],
    array['bodyweight'],
    array['carpal-tunnel-de-quervain', 'tfcc-injury', 'rheumatoid-arthritis', 'epicondylitis', 'elbow-ucl-injury', 'olecranon-bursitis', 'diastasis-recti', 'athletic-pubalgia'],
    array['lying'],
    array['medium-intensity', 'wrist-extension-load', 'forearm-plank-hard'],
    true,
    null
  ),
  (
    '9b47264e-b98c-4082-8617-1e671bfe00a5',
    'Prancha com abdução de pernas (plank jacks)',
    'Em prancha, abra e feche as pernas com saltitos. Versão sem salto: deslize os pés.',
    '{}',
    null,
    array['core', 'legs'],
    array['bodyweight'],
    array['diastasis-recti', 'athletic-pubalgia', 'athletic-pubalgia', 'torn-acl', 'patellar-tendinopathy', 'knee-osteoarthritis', 'plantar-fasciitis', 'osteoporosis-osteopenia', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'labyrinthitis', 'hemiplegia-hemiparesis', 'cerebral-palsy-mild-moderate', 'visual-impairment'],
    array['lying'],
    array['high-intensity', 'explosive-adductors', 'high-intra-abdominal-pressure', 'lower-body-plyometrics'],
    true,
    null
  ),
  (
    '2a45eba2-8788-478e-8bb3-5971fb3c8877',
    'Prancha com salto agrupado',
    'Da prancha alta, salte os pés em direção às mãos e volte. Alto impacto.',
    '{}',
    null,
    array['core', 'legs', 'full-body'],
    array['bodyweight'],
    array['torn-acl', 'patellar-tendinopathy', 'knee-osteoarthritis', 'plantar-fasciitis', 'osteoporosis-osteopenia', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'labyrinthitis', 'hemiplegia-hemiparesis', 'cerebral-palsy-mild-moderate', 'visual-impairment', 'diastasis-recti', 'athletic-pubalgia'],
    array['lying'],
    array['high-intensity', 'high-impact', 'lower-body-plyometrics', 'high-intra-abdominal-pressure'],
    true,
    null
  ),
  (
    '475045c7-965f-4f7d-8bd2-6ae14ff60ad8',
    'Prancha reversa',
    'Sente-se, apoie as mãos atrás e eleve o quadril alinhando o corpo. Olhar neutro.',
    '{}',
    null,
    array['core', 'arms', 'glutes'],
    array['bodyweight'],
    array['carpal-tunnel-de-quervain', 'tfcc-injury', 'rheumatoid-arthritis', 'shoulder-instability'],
    array['lying', 'seated', 'low-impact'],
    array['medium-intensity', 'wrist-extension-load'],
    true,
    null
  ),
  (
    '0b034b83-cefe-4fe3-8758-5ee7fde7e41d',
    'Prancha com remada',
    'Em prancha alta, puxe um elástico ancorado à frente até o tronco. Alternar lados.',
    '{}',
    null,
    array['core', 'back', 'arms'],
    array['resistance-band', 'bodyweight'],
    array['carpal-tunnel-de-quervain', 'tfcc-injury', 'rheumatoid-arthritis', 'diastasis-recti', 'athletic-pubalgia'],
    array['lying'],
    array['medium-intensity', 'wrist-extension-load', 'floor-push'],
    true,
    null
  ),
  (
    'eaeb4484-396c-41ab-8206-1d5ba6b720f4',
    'Abdominal supra (curto)',
    'Deite de costas e eleve só a cabeça e os ombros do solo. Sem puxar o pescoço.',
    '{}',
    null,
    array['core'],
    array['bodyweight'],
    array['disc-herniation', 'pregnancy-trimester-2', 'pregnancy-trimester-3'],
    array['lying', 'low-impact'],
    array['low-intensity'],
    true,
    null
  ),
  (
    '3b00282c-bef9-4820-87b4-89bcf781930b',
    'Abdominal supra com carga',
    'Mesmo supra com pacote leve no peito. Só se o movimento sem carga já estiver confortável.',
    '{}',
    null,
    array['core'],
    array['food-bag', 'bodyweight'],
    array['diastasis-recti', 'athletic-pubalgia', 'disc-herniation', 'pregnancy-trimester-2', 'pregnancy-trimester-3'],
    array['lying', 'low-impact'],
    array['medium-intensity'],
    true,
    null
  ),
  (
    '19365006-11af-441f-8061-8aa7bb913caf',
    'Abdominal remador (completo)',
    'Sente até o tronco vertical e desça com controle. Evite se houver dor lombar.',
    '{}',
    null,
    array['core'],
    array['bodyweight'],
    array['disc-herniation', 'hernia', 'spondylolisthesis', 'diastasis-recti', 'athletic-pubalgia', 'pregnancy-trimester-2', 'pregnancy-trimester-3'],
    array['lying'],
    array['medium-intensity', 'spine-flexion-rotation'],
    true,
    null
  ),
  (
    '42f57da7-e61a-4d8a-804a-2c6d4d73da92',
    'Abdominal infra (elevação de pernas)',
    'Deite de costas e eleve as pernas estendidas ou semi-flexionadas. Lombar colada ao solo.',
    '{}',
    null,
    array['core'],
    array['bodyweight'],
    array['diastasis-recti', 'athletic-pubalgia', 'femoroacetabular-impingement', 'disc-herniation'],
    array['lying', 'low-impact'],
    array['medium-intensity', 'high-intra-abdominal-pressure', 'deep-hip-flexion'],
    true,
    null
  ),
  (
    '2a31cdbe-d5c5-440c-8e37-a7125caf00ce',
    'Abdominal bicicleta',
    'Alterne cotovelo e joelho opostos em movimento de pedalada. Ritmo controlado.',
    '{}',
    null,
    array['core'],
    array['bodyweight'],
    array['disc-herniation', 'hernia', 'spondylolisthesis', 'pregnancy-trimester-2', 'pregnancy-trimester-3'],
    array['lying'],
    array['medium-intensity', 'spine-flexion-rotation'],
    true,
    null
  ),
  (
    '7ddbbfd5-51c8-49f9-83e7-9ff17d3dacce',
    'Abdominal canivete (V-up)',
    'Eleve tronco e pernas ao mesmo tempo tentando tocar os pés. Avançado — prefira versão unilateral se for iniciante.',
    '{}',
    null,
    array['core'],
    array['bodyweight'],
    array['diastasis-recti', 'athletic-pubalgia', 'disc-herniation', 'hernia', 'spondylolisthesis', 'pregnancy-trimester-2', 'pregnancy-trimester-3'],
    array['lying'],
    array['high-intensity', 'high-intra-abdominal-pressure'],
    true,
    null
  ),
  (
    '29f4fc71-cec9-4617-8a1e-37cefeffacd1',
    'Abdominal canivete unilateral com carga',
    'Eleve uma perna e o tronco com uma garrafa. Alternar. Menos pressão que o canivete bilateral.',
    '{}',
    null,
    array['core'],
    array['bottle', 'bodyweight'],
    array['diastasis-recti', 'athletic-pubalgia', 'pregnancy-trimester-2', 'pregnancy-trimester-3'],
    array['lying', 'unilateral'],
    array['medium-intensity', 'high-intra-abdominal-pressure'],
    true,
    null
  ),
  (
    '3d53c9ed-ab56-438c-8c1c-99fff818be61',
    'Abdominal borboleta',
    'Solas dos pés juntas, joelhos abertos. Eleve os ombros do solo em um supra curto.',
    '{}',
    null,
    array['core'],
    array['bodyweight'],
    array['piriformis-syndrome', 'pregnancy-trimester-2', 'pregnancy-trimester-3'],
    array['lying', 'low-impact'],
    array['low-intensity', 'deep-hip-flexion'],
    true,
    null
  ),
  (
    'd21934be-e4b7-4977-8289-482bf1500afb',
    'Abdominal grupado (tuck crunches)',
    'Joelhos flexionados junto ao peito, eleve a cabeça e os ombros. Útil quando se evita extensão lombar.',
    '{}',
    null,
    array['core'],
    array['bodyweight'],
    array['pregnancy-trimester-2', 'pregnancy-trimester-3'],
    array['lying', 'low-impact'],
    array['low-intensity'],
    true,
    null
  ),
  (
    '5503bb24-87bc-4642-8d3c-41fef523cab7',
    'Abdominal escalador (rope crunch)',
    'De joelhos, com elástico ancorado atrás/acima, flexione o tronco trazendo as mãos aos joelhos.',
    '{}',
    null,
    array['core'],
    array['resistance-band'],
    array['disc-herniation', 'hernia', 'spondylolisthesis'],
    array['lying', 'seated', 'low-impact'],
    array['medium-intensity', 'spine-flexion-rotation'],
    true,
    null
  ),
  (
    '98976610-fc69-4565-8915-41c858450ef8',
    'Abdominal resistido',
    'Elástico ancorado atrás da cabeça; flexione o tronco contra a resistência em amplitude curta.',
    '{}',
    null,
    array['core'],
    array['resistance-band'],
    array['disc-herniation', 'hernia', 'spondylolisthesis', 'diastasis-recti', 'athletic-pubalgia'],
    array['lying', 'seated', 'low-impact'],
    array['medium-intensity'],
    true,
    null
  ),
  (
    'b6993d3e-9b4c-4ffe-870e-0225bfc93451',
    'Abdominal pike deslizante',
    'Em prancha com pés sobre toalha, deslize os pés em direção às mãos elevando o quadril.',
    '{}',
    null,
    array['core', 'shoulders'],
    array['towel', 'bodyweight'],
    array['carpal-tunnel-de-quervain', 'tfcc-injury', 'rheumatoid-arthritis', 'diastasis-recti', 'athletic-pubalgia', 'rotator-cuff-injury', 'subacromial-bursitis', 'shoulder-instability'],
    array['lying'],
    array['high-intensity', 'wrist-extension-load', 'high-intra-abdominal-pressure'],
    true,
    null
  ),
  (
    'fd066298-4e12-401b-8a91-2103b60bcdef',
    'Toque nos calcanhares',
    'Deite de costas com joelhos flexionados e alterne tocar os calcanhares com as mãos.',
    '{}',
    null,
    array['core'],
    array['bodyweight'],
    array['pregnancy-trimester-3'],
    array['lying', 'low-impact'],
    array['low-intensity'],
    true,
    null
  ),
  (
    '73a40a70-dd29-490e-89a3-145586a8f153',
    'Giro russo (russian twist)',
    'Sentado, incline o tronco e gire o tronco de um lado para o outro. Pode segurar garrafa. Amplitude pequena.',
    '{}',
    null,
    array['core'],
    array['bodyweight', 'bottle', 'food-bag'],
    array['disc-herniation', 'hernia', 'spondylolisthesis', 'pregnancy-trimester-2', 'pregnancy-trimester-3'],
    array['seated', 'lying'],
    array['medium-intensity', 'spine-flexion-rotation'],
    true,
    null
  ),
  (
    '96e2c21e-82d3-43e7-8b3c-4395fde90dfc',
    'Perdigueiro (bird-dog)',
    'Em quatro apoios, estenda o braço e a perna opostos. Faça em fases lentas se houver espasticidade ou dor.',
    '{}',
    null,
    array['core', 'back', 'glutes'],
    array['bodyweight'],
    array['carpal-tunnel-de-quervain', 'tfcc-injury', 'rheumatoid-arthritis'],
    array['lying', 'low-impact'],
    array['low-intensity', 'wrist-extension-load'],
    true,
    null
  ),
  (
    '23873d65-62d8-4d71-8c96-214f280e59e8',
    'Posição de canoa (hollow body hold)',
    'Deite de costas, lombar colada, braços e pernas levemente elevadas. Segure pouco tempo.',
    '{}',
    null,
    array['core'],
    array['bodyweight'],
    array['diastasis-recti', 'athletic-pubalgia', 'disc-herniation'],
    array['lying', 'low-impact'],
    array['medium-intensity', 'high-intra-abdominal-pressure'],
    true,
    null
  ),
  (
    '8d3534d6-828b-4352-8c5b-81fd73ce1dd4',
    'Balanço em canoa (hollow body rocks)',
    'Na posição de canoa, balance suavemente sem perder o contato da lombar.',
    '{}',
    null,
    array['core'],
    array['bodyweight'],
    array['diastasis-recti', 'athletic-pubalgia', 'labyrinthitis', 'disc-herniation'],
    array['lying'],
    array['medium-intensity', 'high-intra-abdominal-pressure', 'spin'],
    true,
    null
  ),
  (
    'bc2234d8-d9ad-457e-8f50-345a12bb59cf',
    'Inseto morto (dead bug)',
    'Deite de costas e alterne estender braço e perna opostos mantendo a lombar no solo. Ideal para coluna neutra.',
    '{}',
    null,
    array['core'],
    array['bodyweight'],
    '{}',
    array['lying', 'low-impact'],
    array['low-intensity', 'active-pause'],
    true,
    null
  ),
  (
    'c4ff7454-d2bf-43ff-856a-055f0480799c',
    'Chute de tesoura',
    'Deite de costas e alterne as pernas em tesoura, lombar estável.',
    '{}',
    null,
    array['core'],
    array['bodyweight'],
    array['diastasis-recti', 'athletic-pubalgia', 'athletic-pubalgia', 'disc-herniation'],
    array['lying'],
    array['medium-intensity', 'explosive-adductors', 'high-intra-abdominal-pressure'],
    true,
    null
  ),
  (
    '6f4abaf1-884a-4dec-8567-a882eeaf0365',
    'Chute de nadador (flutter kicks)',
    'Pequenos chutes alternados com as pernas elevadas. Pare se a lombar descolar do solo.',
    '{}',
    null,
    array['core'],
    array['bodyweight'],
    array['diastasis-recti', 'athletic-pubalgia', 'disc-herniation'],
    array['lying'],
    array['medium-intensity', 'high-intra-abdominal-pressure'],
    true,
    null
  ),
  (
    'fec7aaa4-94f7-477e-82ec-c42c81866bb4',
    'Limpador de para-brisa (windshield wipers)',
    'Pernas elevadas, mova-as de um lado para o outro como limpadores. Amplitude pequena.',
    '{}',
    null,
    array['core'],
    array['bodyweight'],
    array['disc-herniation', 'hernia', 'spondylolisthesis', 'diastasis-recti', 'athletic-pubalgia'],
    array['lying'],
    array['high-intensity', 'spine-flexion-rotation'],
    true,
    null
  ),
  (
    '513b6fe5-4087-4f87-8b86-29be4ed9b0b8',
    'L-sit no solo',
    'Sente com as mãos ao lado do quadril e tente elevar o corpo com as pernas estendidas. Avançado.',
    '{}',
    null,
    array['core', 'arms'],
    array['bodyweight'],
    array['carpal-tunnel-de-quervain', 'tfcc-injury', 'rheumatoid-arthritis', 'diastasis-recti', 'athletic-pubalgia'],
    array['seated'],
    array['high-intensity', 'wrist-extension-load', 'high-intra-abdominal-pressure'],
    false,
    null
  ),
  (
    'b65619c3-341e-4556-85af-df7ac2260af9',
    'Rotação de tronco (lenhador)',
    'Com elástico ancorado alto ou baixo, puxe em diagonal cruzando o tronco. Quadril estável.',
    '{}',
    null,
    array['core', 'shoulders'],
    array['resistance-band'],
    array['disc-herniation', 'hernia', 'spondylolisthesis'],
    array['standing', 'seated', 'low-impact'],
    array['medium-intensity', 'spine-flexion-rotation'],
    true,
    null
  ),
  (
    'b47fe78f-49d0-44b2-8305-ded38adae046',
    'Press antirotação (Pallof press)',
    'Elástico ancorado ao lado; empurre as mãos à frente resistindo à rotação do tronco. Excelente para quem tem controle de tronco sentado.',
    '{}',
    null,
    array['core'],
    array['resistance-band', 'chair'],
    '{}',
    array['standing', 'seated', 'low-impact'],
    array['low-intensity', 'active-pause'],
    true,
    null
  ),
  (
    '780cdfb2-513d-4bd0-83b8-2bff0f31e07f',
    'Polichinelo',
    'Abra e feche braços e pernas em saltos ritmados. Versão sem salto: passo lateral.',
    '{}',
    null,
    array['full-body'],
    array['bodyweight'],
    array['torn-acl', 'patellar-tendinopathy', 'knee-osteoarthritis', 'plantar-fasciitis', 'osteoporosis-osteopenia', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'labyrinthitis', 'hemiplegia-hemiparesis', 'cerebral-palsy-mild-moderate', 'visual-impairment'],
    array['standing'],
    array['medium-intensity', 'high-impact', 'lower-body-plyometrics', 'spatial-travel'],
    true,
    null
  ),
  (
    '9c71cdef-72aa-44c2-88f1-6494e3388a42',
    'Burpee',
    'Agache, leve as mãos ao chão, estenda as pernas, volte e suba. Pode eliminar o salto final.',
    '{}',
    null,
    array['full-body'],
    array['bodyweight'],
    array['torn-acl', 'patellar-tendinopathy', 'knee-osteoarthritis', 'plantar-fasciitis', 'osteoporosis-osteopenia', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'labyrinthitis', 'hemiplegia-hemiparesis', 'cerebral-palsy-mild-moderate', 'visual-impairment', 'diastasis-recti', 'athletic-pubalgia', 'labyrinthitis'],
    array['standing', 'lying'],
    array['high-intensity', 'high-impact', 'lower-body-plyometrics', 'deep-hip-flexion', 'high-speed'],
    true,
    null
  ),
  (
    'db8015bb-1ddd-454d-8691-5a1874b757d0',
    'Meio burpee (sprawl)',
    'Das mãos no chão, estenda e recolha as pernas sem o salto vertical final.',
    '{}',
    null,
    array['full-body', 'core'],
    array['bodyweight'],
    array['torn-acl', 'patellar-tendinopathy', 'knee-osteoarthritis', 'plantar-fasciitis', 'osteoporosis-osteopenia', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'labyrinthitis', 'hemiplegia-hemiparesis', 'cerebral-palsy-mild-moderate', 'visual-impairment', 'labyrinthitis'],
    array['standing', 'lying'],
    array['medium-intensity', 'high-speed', 'deep-hip-flexion'],
    true,
    null
  ),
  (
    '98fc73d9-935c-4cd6-8c55-e33392dd808c',
    'Escalador (mountain climber)',
    'Em prancha alta, alterne os joelhos em direção ao peito. Ritmo controlado.',
    '{}',
    null,
    array['core', 'legs', 'full-body'],
    array['bodyweight'],
    array['carpal-tunnel-de-quervain', 'tfcc-injury', 'rheumatoid-arthritis', 'plantar-fasciitis', 'diastasis-recti', 'athletic-pubalgia', 'torn-acl', 'patellar-tendinopathy', 'knee-osteoarthritis', 'plantar-fasciitis', 'osteoporosis-osteopenia', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'labyrinthitis', 'hemiplegia-hemiparesis', 'cerebral-palsy-mild-moderate', 'visual-impairment'],
    array['lying'],
    array['high-intensity', 'high-speed', 'forefoot-impact', 'wrist-extension-load', 'high-intra-abdominal-pressure'],
    true,
    null
  ),
  (
    'ea6bc101-0c0f-454c-818a-f8b5dca81b76',
    'Escalador cruzado',
    'Como o escalador, levando o joelho ao cotovelo oposto.',
    '{}',
    null,
    array['core', 'legs'],
    array['bodyweight'],
    array['disc-herniation', 'hernia', 'spondylolisthesis', 'carpal-tunnel-de-quervain', 'tfcc-injury', 'rheumatoid-arthritis', 'torn-acl', 'patellar-tendinopathy', 'knee-osteoarthritis', 'plantar-fasciitis', 'osteoporosis-osteopenia', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'labyrinthitis', 'hemiplegia-hemiparesis', 'cerebral-palsy-mild-moderate', 'visual-impairment'],
    array['lying'],
    array['high-intensity', 'spine-flexion-rotation', 'wrist-extension-load', 'high-speed'],
    true,
    null
  ),
  (
    'eccbcca3-5847-403c-8010-315ad8d17320',
    'Escalador deslizante',
    'Pés sobre toalha em piso liso; deslize um pé de cada vez em direção ao peito.',
    '{}',
    null,
    array['core', 'legs'],
    array['towel', 'bodyweight'],
    array['carpal-tunnel-de-quervain', 'tfcc-injury', 'rheumatoid-arthritis', 'diastasis-recti', 'athletic-pubalgia'],
    array['lying', 'low-impact'],
    array['medium-intensity', 'wrist-extension-load'],
    true,
    null
  ),
  (
    '36a59d98-2536-4d9c-83f1-12dd6688e752',
    'Corrida estacionária (high knees)',
    'Eleve os joelhos alternadamente no lugar. Pode ser marcha sem salto.',
    '{}',
    null,
    array['legs', 'full-body'],
    array['bodyweight'],
    array['plantar-fasciitis', 'torn-acl', 'patellar-tendinopathy', 'knee-osteoarthritis', 'plantar-fasciitis', 'osteoporosis-osteopenia', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'labyrinthitis', 'hemiplegia-hemiparesis', 'cerebral-palsy-mild-moderate', 'visual-impairment'],
    array['standing'],
    array['medium-intensity', 'forefoot-impact', 'high-speed'],
    true,
    null
  ),
  (
    '74d35fdb-ca65-4d13-8b26-19af8331fb47',
    'Chutes traseiros (butt kicks)',
    'Leve os calcanhares aos glúteos alternadamente, no lugar.',
    '{}',
    null,
    array['legs'],
    array['bodyweight'],
    array['plantar-fasciitis', 'chronic-muscle-strain', 'torn-acl', 'patellar-tendinopathy', 'knee-osteoarthritis', 'plantar-fasciitis', 'osteoporosis-osteopenia', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'labyrinthitis', 'hemiplegia-hemiparesis', 'cerebral-palsy-mild-moderate', 'visual-impairment'],
    array['standing'],
    array['medium-intensity', 'forefoot-impact', 'high-speed'],
    true,
    null
  ),
  (
    '8857383d-04c5-449b-81ec-e1534aabe201',
    'Patinação lateral (skater jumps)',
    'Salte lateralmente de um pé para o outro como na patinação. Aterrise macio.',
    '{}',
    null,
    array['legs', 'glutes'],
    array['bodyweight'],
    array['torn-acl', 'patellar-tendinopathy', 'knee-osteoarthritis', 'plantar-fasciitis', 'osteoporosis-osteopenia', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'labyrinthitis', 'hemiplegia-hemiparesis', 'cerebral-palsy-mild-moderate', 'visual-impairment', 'collateral-ligament-injury', 'torn-acl', 'ankle-ligament-sprain', 'visual-impairment'],
    array['standing', 'unilateral'],
    array['high-intensity', 'lower-body-plyometrics', 'knee-lateral-force', 'spatial-travel', 'distance-jump'],
    true,
    null
  ),
  (
    'b6d4cf96-39e4-4061-86bf-3b3ff1a82f48',
    'Salto estrela',
    'Salte abrindo braços e pernas em estrela e feche na aterrissagem.',
    '{}',
    null,
    array['full-body'],
    array['bodyweight'],
    array['torn-acl', 'patellar-tendinopathy', 'knee-osteoarthritis', 'plantar-fasciitis', 'osteoporosis-osteopenia', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'labyrinthitis', 'hemiplegia-hemiparesis', 'cerebral-palsy-mild-moderate', 'visual-impairment'],
    array['standing'],
    array['high-intensity', 'high-impact', 'lower-body-plyometrics'],
    true,
    null
  ),
  (
    '4898e041-3321-42f1-84d8-22abf6fb50b2',
    'Salto em distância parado (broad jumps)',
    'Salte à frente com os dois pés e aterrise com joelhos flexionados. Espaço livre à frente.',
    '{}',
    null,
    array['legs', 'glutes', 'full-body'],
    array['bodyweight'],
    array['torn-acl', 'patellar-tendinopathy', 'knee-osteoarthritis', 'plantar-fasciitis', 'osteoporosis-osteopenia', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'labyrinthitis', 'hemiplegia-hemiparesis', 'cerebral-palsy-mild-moderate', 'visual-impairment', 'visual-impairment'],
    array['standing'],
    array['high-intensity', 'high-impact', 'lower-body-plyometrics', 'distance-jump', 'spatial-travel'],
    true,
    null
  ),
  (
    'dc1ba2de-7ab6-47d6-8f9b-c000af4b8dbc',
    'Salto com joelhos no peito (tuck jumps)',
    'Salte trazendo os joelhos ao peito e aterrise macio.',
    '{}',
    null,
    array['legs', 'core', 'full-body'],
    array['bodyweight'],
    array['torn-acl', 'patellar-tendinopathy', 'knee-osteoarthritis', 'plantar-fasciitis', 'osteoporosis-osteopenia', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'labyrinthitis', 'hemiplegia-hemiparesis', 'cerebral-palsy-mild-moderate', 'visual-impairment'],
    array['standing'],
    array['high-intensity', 'high-impact', 'lower-body-plyometrics', 'deep-hip-flexion'],
    true,
    null
  ),
  (
    '0adcb8ff-1b40-473a-8850-e93376694927',
    'Caminhada com as mãos (inchworm)',
    'Da posição em pé, leve as mãos ao chão e caminhe para uma prancha, depois volte os pés.',
    '{}',
    null,
    array['full-body', 'core', 'shoulders'],
    array['bodyweight'],
    array['carpal-tunnel-de-quervain', 'tfcc-injury', 'rheumatoid-arthritis', 'chronic-muscle-strain', 'labyrinthitis'],
    array['standing', 'lying'],
    array['medium-intensity', 'wrist-extension-load', 'max-range-stretch'],
    true,
    null
  ),
  (
    '866d6867-839f-494b-8fe2-02cd49308ad7',
    'Caminhada do urso (bear crawl)',
    'Em quatro apoios com joelhos elevados, caminhe para frente. Passos curtos.',
    '{}',
    null,
    array['full-body', 'core', 'shoulders'],
    array['bodyweight'],
    array['carpal-tunnel-de-quervain', 'tfcc-injury', 'rheumatoid-arthritis', 'visual-impairment', 'pregnancy-trimester-3'],
    array['lying'],
    array['medium-intensity', 'wrist-extension-load', 'spatial-travel'],
    true,
    null
  ),
  (
    '052bc64e-f484-44c0-8985-dae34df8b942',
    'Caminhada do caranguejo (crab walk)',
    'Sentado com mãos e pés no solo, elevando o quadril, caminhe para frente ou trás.',
    '{}',
    null,
    array['arms', 'core', 'glutes'],
    array['bodyweight'],
    array['carpal-tunnel-de-quervain', 'tfcc-injury', 'rheumatoid-arthritis', 'shoulder-instability', 'visual-impairment'],
    array['seated', 'lying'],
    array['medium-intensity', 'wrist-extension-load', 'spatial-travel'],
    true,
    null
  ),
  (
    'ed4dd230-b3e0-4421-8631-30dad340f3cf',
    'Alcance do caranguejo (crab reach)',
    'Na posição de caranguejo, eleve um braço cruzando o tronco em direção ao teto.',
    '{}',
    null,
    array['core', 'shoulders', 'arms'],
    array['bodyweight'],
    array['carpal-tunnel-de-quervain', 'tfcc-injury', 'rheumatoid-arthritis', 'disc-herniation', 'hernia', 'spondylolisthesis'],
    array['lying', 'seated'],
    array['medium-intensity', 'wrist-extension-load', 'spine-flexion-rotation'],
    true,
    null
  ),
  (
    '407dc114-6a52-40ca-8c42-49a13def5af8',
    'Alcance do escorpião (scorpion reach)',
    'De bruços, leve um pé em direção ao lado oposto abrindo o quadril. Amplitude suave.',
    '{}',
    null,
    array['back', 'glutes', 'core'],
    array['bodyweight'],
    array['spondylolisthesis', 'spinal-stenosis', 'disc-herniation', 'piriformis-syndrome', 'pregnancy-trimester-2', 'pregnancy-trimester-3'],
    array['lying', 'low-impact'],
    array['low-intensity', 'prone-position', 'spine-hyperextension', 'deep-hip-flexion'],
    true,
    null
  ),
  (
    'e7a37ed1-3b62-482b-8bc1-579a7b98b6f2',
    'Mobilidade de ombros com deslocamento',
    'Segure um cabo de vassoura com pegada larga e passe-o da frente para trás do corpo com cotovelos estendidos. Sem forçar.',
    '{}',
    null,
    array['shoulders'],
    array['broomstick'],
    array['shoulder-instability', 'rotator-cuff-injury', 'slap-tear', 'ac-joint-injury'],
    array['standing', 'seated', 'low-impact'],
    array['low-intensity', 'wide-arm-tension', 'active-pause'],
    true,
    null
  ),
  (
    '955dfadf-6f1c-4332-826e-e81c83973b67',
    'Elevação de braços sentada (pausa ativa)',
    'Sente-se com a coluna alongada. Eleve os braços até a linha dos ombros e desça com calma. Cerca de um minuto, sem prender o ar.',
    '{}',
    null,
    array['shoulders', 'arms'],
    array['chair', 'bodyweight'],
    '{}',
    array['seated'],
    array['active-pause', 'low-intensity'],
    true,
    null
  ),
  (
    '5cb286fa-bbb3-47d5-8653-a4f79bcec509',
    'Remada com toalha (sentada)',
    'Sente-se e puxe uma toalha em direção ao tronco, aproximando as omoplatas. Pode enfatizar um lado.',
    '{}',
    null,
    array['back', 'arms'],
    array['towel', 'chair'],
    '{}',
    array['seated', 'unilateral', 'low-impact'],
    array['low-intensity', 'active-pause'],
    true,
    null
  ),
  (
    'b06fa5f0-4863-4539-8f2a-45cf240ca01a',
    'Rotação de tronco sentada com garrafa',
    'Sente-se e gire o tronco com amplitude pequena segurando uma garrafa. Preferir Pallof se houver histórico de hérnia.',
    '{}',
    null,
    array['core'],
    array['bottle', 'chair'],
    array['disc-herniation', 'hernia', 'spondylolisthesis'],
    array['seated', 'low-impact'],
    array['active-pause', 'low-intensity', 'spine-flexion-rotation'],
    true,
    null
  ),
  (
    'e80774b4-c526-4af2-8e53-d9e3102a1c32',
    'Agachamento apoiado na cadeira',
    'À frente de uma cadeira, desça até tocar o assento de leve e suba. Amplitude confortável.',
    '{}',
    null,
    array['legs', 'glutes'],
    array['chair', 'bodyweight'],
    array['chondromalacia', 'torn-pcl', 'knee-osteoarthritis'],
    array['standing', 'low-impact'],
    array['low-intensity', 'deep-knee-flexion'],
    true,
    null
  ),
  (
    'b57e7cef-6995-48ee-8fd3-38eefe967fb7',
    'Prancha de joelhos',
    'Antebraços e joelhos no solo, tronco alinhado. Segure pouco e descanse.',
    '{}',
    null,
    array['core'],
    array['bodyweight'],
    array['diastasis-recti', 'athletic-pubalgia', 'olecranon-bursitis'],
    array['lying', 'low-impact'],
    array['low-intensity', 'forearm-plank-hard', 'high-intra-abdominal-pressure'],
    true,
    null
  ),
  (
    '92d42749-bf9a-4066-8726-9f428e9f69d2',
    'Desenvolvimento de ombros sentado com garrafa',
    'Sentado, empurre garrafas acima da cabeça sem arquear a lombar. Pare abaixo de 90 graus se houver dor no ombro.',
    '{}',
    null,
    array['shoulders', 'arms'],
    array['bottle', 'chair'],
    array['rotator-cuff-injury', 'subacromial-bursitis', 'shoulder-instability'],
    array['seated', 'low-impact'],
    array['low-intensity', 'overhead-press'],
    true,
    null
  ),
  (
    'a0c0aec6-e80e-4df4-8bdb-9f982f9b4b43',
    'Anjo na parede (pausa ativa)',
    'Costas e braços na parede; deslize os braços para cima e para baixo mantendo contato. Movimento lento.',
    '{}',
    null,
    array['shoulders', 'back'],
    array['wall', 'bodyweight'],
    array['rotator-cuff-injury', 'subacromial-bursitis'],
    array['standing', 'seated', 'low-impact'],
    array['active-pause', 'low-intensity'],
    true,
    null
  ),
  (
    'b3eca6ef-68a4-4a54-8b39-cc095b7a48b7',
    'Marcha sentada',
    'Sente-se e alterne elevar os joelhos como uma marcha. Útil para quem usa cadeira ou evita impacto.',
    '{}',
    null,
    array['legs', 'core'],
    array['chair', 'bodyweight'],
    '{}',
    array['seated', 'low-impact'],
    array['active-pause', 'low-intensity'],
    true,
    null
  )
on conflict (id) do update
set
  title = excluded.title,
  description = excluded.description,
  target_muscles = excluded.target_muscles,
  equipment_tags = excluded.equipment_tags,
  contraindication_tags = excluded.contraindication_tags,
  required_capability_tags = excluded.required_capability_tags,
  intensity_tags = excluded.intensity_tags,
  is_published = excluded.is_published,
  updated_at = now();

