-- purpose: sync meal contains_tags + diet_compatible_tags
--   from Nutricionista enrichment (ingredients × food avoid catalog).
-- affected: tags, meals_library, list_safe_meals
-- notes: generated by scripts/generate-meal-safety-sync-sql.ts
--   ensures lactose/gluten/egg/meat/fish/peanut/soy match the plate.

insert into public.tags (slug, domain, kind, label)
values
  ('gluten', 'food', 'contains', 'Glúten'),
  ('lactose', 'food', 'contains', 'Lactose'),
  ('egg', 'food', 'contains', 'Ovo'),
  ('peanut', 'food', 'contains', 'Amendoim'),
  ('soy', 'food', 'contains', 'Soja'),
  ('meat', 'food', 'contains', 'Carne'),
  ('fish', 'food', 'contains', 'Peixe e frutos do mar')
on conflict (slug) do update
set domain = excluded.domain, kind = excluded.kind, label = excluded.label;

update public.meals_library
set contains_tags = array['gluten', 'lactose']::text[],
    diet_compatible_tags = array['vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = '1da27d99-4219-4aeb-8fa5-1a5852e66bd2';

update public.meals_library
set contains_tags = array['gluten']::text[],
    diet_compatible_tags = array['vegan', 'vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = 'd6af4736-e5f2-4add-8c15-375d350c63b1';

update public.meals_library
set contains_tags = '{}'::text[],
    diet_compatible_tags = array['vegan', 'vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = '67d93713-dbdd-4662-8cd6-a363dc6b9eb0';

update public.meals_library
set contains_tags = array['egg']::text[],
    diet_compatible_tags = array['vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = 'b786049a-e120-4a6f-8a3d-dbd9a8f130e0';

update public.meals_library
set contains_tags = array['egg', 'lactose']::text[],
    diet_compatible_tags = array['vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = '4900bf7a-7fc8-44af-84af-01369ce44919';

update public.meals_library
set contains_tags = array['egg']::text[],
    diet_compatible_tags = array['vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = '1992c34c-823f-43e5-82b2-08f15f514bf3';

update public.meals_library
set contains_tags = array['egg']::text[],
    diet_compatible_tags = array['vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = 'e76b8b1d-0c99-4406-8a58-6f522d84df6d';

update public.meals_library
set contains_tags = array['meat']::text[],
    diet_compatible_tags = array['low-cost']::text[],
    updated_at = now()
where id = '84a4efdc-1bac-4e4a-8ef2-e70ea6cd0734';

update public.meals_library
set contains_tags = array['lactose']::text[],
    diet_compatible_tags = array['vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = 'c237b705-881f-4cea-8ff8-18f750816223';

update public.meals_library
set contains_tags = array['egg']::text[],
    diet_compatible_tags = array['vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = 'd4b85a71-85b9-405b-8fe6-e384de0a9ffd';

update public.meals_library
set contains_tags = array['peanut']::text[],
    diet_compatible_tags = array['vegan', 'vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = '08c56ba5-4570-495f-8f75-51f01554300b';

update public.meals_library
set contains_tags = array['egg', 'gluten']::text[],
    diet_compatible_tags = array['vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = '7e46748b-f472-4653-8bdb-cd09df3baaa4';

update public.meals_library
set contains_tags = array['fish', 'gluten', 'lactose']::text[],
    diet_compatible_tags = array['low-cost']::text[],
    updated_at = now()
where id = 'eb32746d-6a6b-4da1-85ad-398d8cd50b11';

update public.meals_library
set contains_tags = array['gluten']::text[],
    diet_compatible_tags = array['vegan', 'vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = '67e50501-928d-43bf-8614-16771bb204e7';

update public.meals_library
set contains_tags = array['egg', 'gluten']::text[],
    diet_compatible_tags = array['vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = 'd7fe228c-628e-495d-8051-210e6e22ae17';

update public.meals_library
set contains_tags = array['egg', 'gluten']::text[],
    diet_compatible_tags = array['vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = '16daacdf-fafc-4e62-8d5a-d26b2c3ae3a2';

update public.meals_library
set contains_tags = array['egg']::text[],
    diet_compatible_tags = array['vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = '7b18fa67-0f7d-493b-89eb-5372781c4785';

update public.meals_library
set contains_tags = '{}'::text[],
    diet_compatible_tags = array['vegan', 'vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = '12485244-e3be-4795-8bac-d895f01a3805';

update public.meals_library
set contains_tags = array['gluten']::text[],
    diet_compatible_tags = array['vegan', 'vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = '76f261f7-f189-4a4c-8f96-b7df0f876526';

update public.meals_library
set contains_tags = array['gluten']::text[],
    diet_compatible_tags = array['vegan', 'vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = '581511cf-a103-46a7-8e12-6e12fa7f5b01';

update public.meals_library
set contains_tags = '{}'::text[],
    diet_compatible_tags = array['vegan', 'vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = 'd4bb113d-283f-4758-8adb-5b1e7d301f8b';

update public.meals_library
set contains_tags = '{}'::text[],
    diet_compatible_tags = array['vegan', 'vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = 'b3d12560-e20c-4f1f-883f-41dd7009bc93';

update public.meals_library
set contains_tags = '{}'::text[],
    diet_compatible_tags = array['vegan', 'vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = 'cdfd31c5-adc1-4072-88f6-b5c692984d03';

update public.meals_library
set contains_tags = array['gluten']::text[],
    diet_compatible_tags = array['vegan', 'vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = '2131fbe7-10da-4612-85d8-9dcf3ef1be64';

update public.meals_library
set contains_tags = array['peanut']::text[],
    diet_compatible_tags = array['vegan', 'vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = '66765760-b08c-4d9b-8f18-59786d81f68e';

update public.meals_library
set contains_tags = array['lactose']::text[],
    diet_compatible_tags = array['vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = 'e18feff3-fb93-415a-8ca0-58a30b6753eb';

update public.meals_library
set contains_tags = array['gluten', 'lactose']::text[],
    diet_compatible_tags = array['vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = 'c7eb1e98-8f68-430f-853f-c923c61a929c';

update public.meals_library
set contains_tags = '{}'::text[],
    diet_compatible_tags = array['vegan', 'vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = 'cb3c9127-28c6-4526-8e67-568493b89ca8';

update public.meals_library
set contains_tags = '{}'::text[],
    diet_compatible_tags = array['vegan', 'vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = '187c0b51-5777-4180-8428-78bbca074cee';

update public.meals_library
set contains_tags = array['egg']::text[],
    diet_compatible_tags = array['vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = '2e6d385e-c0c8-44dc-8999-2dc0f54f97ae';

update public.meals_library
set contains_tags = array['egg']::text[],
    diet_compatible_tags = array['vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = 'c39cc0b5-0422-4a98-85b6-f9595b01d146';

update public.meals_library
set contains_tags = '{}'::text[],
    diet_compatible_tags = array['vegan', 'vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = '75e73b4f-7e49-4d67-8336-0e598eab770f';

update public.meals_library
set contains_tags = '{}'::text[],
    diet_compatible_tags = array['vegan', 'vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = '4d4d9064-dff9-4255-81e1-7e1be2c6a33f';

update public.meals_library
set contains_tags = '{}'::text[],
    diet_compatible_tags = array['vegan', 'vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = '601f3a94-c9d6-47de-8a4d-0a3a28096526';

update public.meals_library
set contains_tags = array['peanut']::text[],
    diet_compatible_tags = array['vegan', 'vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = 'ae07885b-f2f8-4add-822c-f19c584947c2';

update public.meals_library
set contains_tags = '{}'::text[],
    diet_compatible_tags = array['vegan', 'vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = '507087b1-c44a-476d-8a5b-890633d1c4a4';

update public.meals_library
set contains_tags = array['egg', 'gluten']::text[],
    diet_compatible_tags = array['vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = 'c6b7f2a2-5bea-4855-8150-776c3f81b773';

update public.meals_library
set contains_tags = array['egg', 'gluten']::text[],
    diet_compatible_tags = array['vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = '78c9fe6e-72dd-48ce-8f00-c359db52c288';

update public.meals_library
set contains_tags = array['gluten', 'lactose']::text[],
    diet_compatible_tags = array['vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = 'ec0a4db0-e773-49ad-8deb-47d586f05f63';

update public.meals_library
set contains_tags = array['gluten', 'meat']::text[],
    diet_compatible_tags = array['low-cost']::text[],
    updated_at = now()
where id = '7d4006cc-1fd2-4498-8e78-01921999988f';

update public.meals_library
set contains_tags = array['egg', 'lactose']::text[],
    diet_compatible_tags = array['vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = 'bf44c21f-620d-4874-8f91-f799a66e70e3';

update public.meals_library
set contains_tags = array['gluten']::text[],
    diet_compatible_tags = array['vegan', 'vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = '6d88e33b-4956-47bd-8ab7-ebe121af04f9';

update public.meals_library
set contains_tags = array['peanut']::text[],
    diet_compatible_tags = array['vegan', 'vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = 'd3db2332-8784-4503-8a6f-fed28793d421';

update public.meals_library
set contains_tags = '{}'::text[],
    diet_compatible_tags = array['vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = 'e544f418-bc39-4904-8819-39b0382eeccb';

update public.meals_library
set contains_tags = array['lactose']::text[],
    diet_compatible_tags = array['vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = 'a1f47e0a-ed1a-4481-81f0-d8b17a6c414c';

update public.meals_library
set contains_tags = '{}'::text[],
    diet_compatible_tags = array['vegan', 'vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = '523d0cf7-abe2-4b26-828c-160daf93e097';

update public.meals_library
set contains_tags = array['lactose']::text[],
    diet_compatible_tags = array['vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = '53f6d664-d3b5-41ea-8959-e4e0f1c3c81f';

update public.meals_library
set contains_tags = array['egg', 'gluten']::text[],
    diet_compatible_tags = array['vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = 'a12f5f15-dbf8-49cd-8de7-8bb54dfa8bc7';

update public.meals_library
set contains_tags = array['lactose']::text[],
    diet_compatible_tags = array['vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = '45e463e2-b542-4045-8c55-fcdc9fe0f8af';

update public.meals_library
set contains_tags = array['peanut']::text[],
    diet_compatible_tags = array['vegan', 'vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = '34ff8a33-2fb6-450b-8fff-47d63cacc5d3';

update public.meals_library
set contains_tags = array['lactose']::text[],
    diet_compatible_tags = array['vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = 'f38a6e82-8b97-4e40-86f0-139d3be5f94c';

update public.meals_library
set contains_tags = array['meat']::text[],
    diet_compatible_tags = array['low-cost']::text[],
    updated_at = now()
where id = '25c942de-df89-49de-8d17-3b9a5bfc0cbf';

update public.meals_library
set contains_tags = array['meat']::text[],
    diet_compatible_tags = array['low-cost']::text[],
    updated_at = now()
where id = 'b9d8e91a-b474-40ca-8237-8a8ca5a2f1d4';

update public.meals_library
set contains_tags = array['meat']::text[],
    diet_compatible_tags = array['low-cost']::text[],
    updated_at = now()
where id = '1c5c9a4e-89ff-46b4-86f5-099a6596f078';

update public.meals_library
set contains_tags = array['meat']::text[],
    diet_compatible_tags = array['low-cost']::text[],
    updated_at = now()
where id = 'fea9adaf-28c7-4926-8c5c-07de923d2aea';

update public.meals_library
set contains_tags = array['gluten', 'meat']::text[],
    diet_compatible_tags = array['low-cost']::text[],
    updated_at = now()
where id = '0a847862-f1fd-49cc-8984-682c7a685ed3';

update public.meals_library
set contains_tags = array['gluten', 'meat']::text[],
    diet_compatible_tags = array['low-cost']::text[],
    updated_at = now()
where id = 'fb05b30a-f64b-4522-831b-5c42203c7b66';

update public.meals_library
set contains_tags = array['fish', 'gluten']::text[],
    diet_compatible_tags = array['low-cost']::text[],
    updated_at = now()
where id = '83ab12a7-eec8-40e5-840e-d4888f230d79';

update public.meals_library
set contains_tags = array['meat']::text[],
    diet_compatible_tags = array['low-cost']::text[],
    updated_at = now()
where id = '68fd19ac-f243-4922-8037-e86966eb01a6';

update public.meals_library
set contains_tags = array['meat']::text[],
    diet_compatible_tags = array['low-cost']::text[],
    updated_at = now()
where id = 'a822520b-0b2f-41f0-8c8d-d1ef68fffa0b';

update public.meals_library
set contains_tags = array['egg', 'gluten', 'meat']::text[],
    diet_compatible_tags = array['low-cost']::text[],
    updated_at = now()
where id = '2e9fa7e8-80ed-485e-8a17-c39ff76053e7';

update public.meals_library
set contains_tags = array['egg', 'meat']::text[],
    diet_compatible_tags = array['low-cost']::text[],
    updated_at = now()
where id = 'c41a81ce-06fe-4868-82b1-3b9165003a43';

update public.meals_library
set contains_tags = array['egg']::text[],
    diet_compatible_tags = array['vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = '2fe19879-4fa3-4193-85a1-6513424fa482';

update public.meals_library
set contains_tags = array['egg']::text[],
    diet_compatible_tags = array['vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = 'fad9f833-3343-4a6f-8c38-ec6816a7b356';

update public.meals_library
set contains_tags = array['fish']::text[],
    diet_compatible_tags = array['low-cost']::text[],
    updated_at = now()
where id = 'f249e1cc-3287-49fd-8a9e-893028ebd5c8';

update public.meals_library
set contains_tags = array['meat']::text[],
    diet_compatible_tags = array['low-cost']::text[],
    updated_at = now()
where id = 'dcd81dea-2fdf-4864-898d-48544524893f';

update public.meals_library
set contains_tags = array['lactose']::text[],
    diet_compatible_tags = array['vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = '39b27655-58a1-4bd1-89cf-02f05e65e037';

update public.meals_library
set contains_tags = array['meat']::text[],
    diet_compatible_tags = array['low-cost']::text[],
    updated_at = now()
where id = 'a5abfb2e-7a12-4c9c-8060-780b8666b054';

update public.meals_library
set contains_tags = array['lactose', 'meat']::text[],
    diet_compatible_tags = array['low-cost']::text[],
    updated_at = now()
where id = 'd120da1c-2294-43da-82e4-5fbc4ef2044f';

update public.meals_library
set contains_tags = array['meat']::text[],
    diet_compatible_tags = array['low-cost']::text[],
    updated_at = now()
where id = 'c7f85706-9b22-409c-8e30-958befc5d2ca';

update public.meals_library
set contains_tags = array['meat']::text[],
    diet_compatible_tags = array['low-cost']::text[],
    updated_at = now()
where id = 'afb5f16b-1c0b-48bf-8d72-b0c1a64d8102';

update public.meals_library
set contains_tags = array['meat']::text[],
    diet_compatible_tags = array['low-cost']::text[],
    updated_at = now()
where id = 'efb3d58a-c4ee-4afe-808a-a0d24431f9de';

update public.meals_library
set contains_tags = array['meat']::text[],
    diet_compatible_tags = array['low-cost']::text[],
    updated_at = now()
where id = '48ffeac7-cb3b-4bc2-853a-599a427a91f0';

update public.meals_library
set contains_tags = array['meat']::text[],
    diet_compatible_tags = array['low-cost']::text[],
    updated_at = now()
where id = '9ebebbeb-fa8f-4eef-8bcc-8f01d527843d';

update public.meals_library
set contains_tags = array['meat']::text[],
    diet_compatible_tags = array['low-cost']::text[],
    updated_at = now()
where id = 'b25e9151-934c-4f73-8012-6c7024008293';

update public.meals_library
set contains_tags = array['egg', 'gluten']::text[],
    diet_compatible_tags = array['vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = 'ffad26b9-a2c2-4509-89de-974b6830feba';

update public.meals_library
set contains_tags = array['lactose', 'meat']::text[],
    diet_compatible_tags = array['low-cost']::text[],
    updated_at = now()
where id = '920bc641-49ec-4eb5-8359-3887d86d2339';

update public.meals_library
set contains_tags = '{}'::text[],
    diet_compatible_tags = array['vegan', 'vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = 'c6500a80-505c-42ab-808d-023084119ed9';

update public.meals_library
set contains_tags = array['gluten']::text[],
    diet_compatible_tags = array['vegan', 'vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = 'fa40b966-f587-4881-82fb-e0e73b457b45';

update public.meals_library
set contains_tags = array['meat']::text[],
    diet_compatible_tags = array['low-cost']::text[],
    updated_at = now()
where id = 'f445e88e-558a-4b1b-8903-349224296d8e';

update public.meals_library
set contains_tags = array['meat']::text[],
    diet_compatible_tags = array['low-cost']::text[],
    updated_at = now()
where id = 'f89b9362-2d58-4297-812d-e09bbfe30776';

update public.meals_library
set contains_tags = array['meat']::text[],
    diet_compatible_tags = array['low-cost']::text[],
    updated_at = now()
where id = '115af1ea-071e-46fa-88eb-0ab35d37018a';

update public.meals_library
set contains_tags = '{}'::text[],
    diet_compatible_tags = array['vegan', 'vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = '62b95f2f-e4df-4042-8d92-9e32c0f7050d';

update public.meals_library
set contains_tags = array['egg']::text[],
    diet_compatible_tags = array['vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = '4ee3174e-faea-4800-8dfa-3a74d865448e';

update public.meals_library
set contains_tags = array['meat']::text[],
    diet_compatible_tags = array['low-cost']::text[],
    updated_at = now()
where id = 'd7911018-4618-4a2f-8731-31c8dd642bf0';

update public.meals_library
set contains_tags = array['meat']::text[],
    diet_compatible_tags = array['low-cost']::text[],
    updated_at = now()
where id = '348f7fe8-da0f-4bc2-82f3-2b4db096b542';

update public.meals_library
set contains_tags = array['lactose', 'meat']::text[],
    diet_compatible_tags = array['low-cost']::text[],
    updated_at = now()
where id = 'fb45e8e3-6984-46f7-8bda-6d2091cf452e';

update public.meals_library
set contains_tags = array['egg', 'gluten']::text[],
    diet_compatible_tags = array['vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = '93ad4bee-ef03-4fc9-8273-e31feca265b8';

update public.meals_library
set contains_tags = array['egg']::text[],
    diet_compatible_tags = array['vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = '608e11c6-f8af-4365-8f67-17a94eb1e4d7';

update public.meals_library
set contains_tags = array['egg']::text[],
    diet_compatible_tags = array['vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = 'f034247f-3862-4beb-8db3-20b1bb5f909b';

update public.meals_library
set contains_tags = array['meat']::text[],
    diet_compatible_tags = array['low-cost']::text[],
    updated_at = now()
where id = '438756b6-342f-4572-84a2-f2c159689190';

update public.meals_library
set contains_tags = array['gluten', 'meat']::text[],
    diet_compatible_tags = array['low-cost']::text[],
    updated_at = now()
where id = '19dbdd95-6d77-427e-89b6-70ee0d886aa3';

update public.meals_library
set contains_tags = array['gluten', 'lactose']::text[],
    diet_compatible_tags = array['vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = '205d7d5b-1dad-4c11-81d8-44b738768f2d';

update public.meals_library
set contains_tags = array['meat']::text[],
    diet_compatible_tags = array['low-cost']::text[],
    updated_at = now()
where id = 'ecca07a1-793c-4245-8172-7910497d70aa';

update public.meals_library
set contains_tags = array['meat']::text[],
    diet_compatible_tags = array['low-cost']::text[],
    updated_at = now()
where id = 'd87ce55c-a7ca-43b0-89b0-7d5292764154';

update public.meals_library
set contains_tags = array['egg']::text[],
    diet_compatible_tags = array['vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = '5561271b-0308-4d01-81b8-2ecd14647d8a';

update public.meals_library
set contains_tags = array['lactose', 'meat']::text[],
    diet_compatible_tags = array['low-cost']::text[],
    updated_at = now()
where id = '94cf95d5-47a0-4cc4-83c5-5da54a8ac8cb';

update public.meals_library
set contains_tags = '{}'::text[],
    diet_compatible_tags = array['vegan', 'vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = '63cfc81d-66b5-438d-8289-e56df7892d82';

update public.meals_library
set contains_tags = '{}'::text[],
    diet_compatible_tags = array['vegan', 'vegetarian', 'low-cost']::text[],
    updated_at = now()
where id = 'fbbbb4c0-28bd-4aeb-853c-3ef9ec06d996';

comment on function public.list_safe_meals() is
  'Meal engine. Blocks when contains_tags overlaps avoids_tags; enforces vegan/vegetarian diet_pattern. Tags enriched by Nutricionista.';

