-- purpose: sync clinical block rules + exercise contraindications
--   from Educador Físico catalog (conditions-catalog + seed enrichment).
-- affected: tags, tag_block_rules, exercises_library, list_safe_exercises
-- notes: generated by scripts/generate-exercise-safety-sync-sql.ts
--   fills gaps (e.g. torn-acl → high-impact / plyometrics).

insert into public.tags (slug, domain, kind, label)
values
  ('axial-load', 'movement', 'intensity', 'Carga axial'),
  ('bilateral-push-up', 'movement', 'intensity', 'Flexão bilateral'),
  ('cross-body-load', 'movement', 'intensity', 'Carga cruzando o corpo'),
  ('deep-hip-flexion', 'movement', 'intensity', 'Flexão profunda de quadril'),
  ('deep-knee-flexion', 'movement', 'intensity', 'Flexão profunda de joelho'),
  ('distance-jump', 'movement', 'intensity', 'Salto em distância'),
  ('double-hand-support', 'movement', 'intensity', 'Apoio duplo das mãos'),
  ('elbow-valgus-load', 'movement', 'intensity', 'Carga em valgo no cotovelo'),
  ('explosive-adductors', 'movement', 'intensity', 'Adutores explosivos'),
  ('floor-push', 'movement', 'intensity', 'Empurrar o chão'),
  ('forearm-plank-hard', 'movement', 'intensity', 'Prancha nos antebraços em superfície dura'),
  ('forefoot-impact', 'movement', 'intensity', 'Impacto na ponta dos pés'),
  ('hanging-traction', 'movement', 'intensity', 'Tração pendurada'),
  ('high-impact', 'movement', 'intensity', 'Alto impacto'),
  ('high-intensity', 'movement', 'intensity', 'Intensidade alta'),
  ('high-intra-abdominal-pressure', 'movement', 'intensity', 'Alta pressão intra-abdominal'),
  ('high-speed', 'movement', 'intensity', 'Alta velocidade'),
  ('inversion', 'movement', 'intensity', 'Inversão'),
  ('knee-lateral-force', 'movement', 'intensity', 'Força lateral no joelho'),
  ('lateral-raise-above-90', 'movement', 'intensity', 'Elevação lateral acima de 90'),
  ('long-lever', 'movement', 'intensity', 'Alavanca longa'),
  ('lower-body-plyometrics', 'movement', 'intensity', 'Pliometria de membros inferiores'),
  ('lumbar-impact', 'movement', 'intensity', 'Impacto lombar'),
  ('max-range-stretch', 'movement', 'intensity', 'Alongamento em amplitude máxima'),
  ('overhead-press', 'movement', 'intensity', 'Empurrar acima da cabeça'),
  ('prolonged-grip', 'movement', 'intensity', 'Preensão prolongada'),
  ('prone-position', 'movement', 'intensity', 'Decúbito ventral'),
  ('rotational-instability', 'movement', 'intensity', 'Instabilidade rotacional'),
  ('seated-only', 'movement', 'intensity', 'Apenas sentado'),
  ('side-lying-pressure', 'movement', 'intensity', 'Pressão em decúbito lateral'),
  ('spatial-travel', 'movement', 'intensity', 'Deslocamento espacial'),
  ('spin', 'movement', 'intensity', 'Giro'),
  ('spine-flexion-rotation', 'movement', 'intensity', 'Flexão com rotação da coluna'),
  ('spine-hyperextension', 'movement', 'intensity', 'Hiperextensão da coluna'),
  ('standing-required', 'movement', 'intensity', 'Exige ficar em pé'),
  ('tibial-posterior-load', 'movement', 'intensity', 'Carga tibial posterior'),
  ('unilateral-full-load', 'movement', 'intensity', 'Carga unilateral total'),
  ('unstable-base', 'movement', 'intensity', 'Base instável'),
  ('use-legs', 'movement', 'intensity', 'Uso de pernas'),
  ('wide-arm-tension', 'movement', 'intensity', 'Tensão com braços abertos'),
  ('wrist-extension-load', 'movement', 'intensity', 'Carga em extensão de punho')
on conflict (slug) do update
set domain = excluded.domain, kind = excluded.kind, label = excluded.label;

insert into public.tag_block_rules (condition_slug, blocked_content_tag)
values
  ('spinal-cord-injury-paraplegia', 'use-legs'),
  ('spinal-cord-injury-paraplegia', 'standing-required'),
  ('spinal-cord-injury-paraplegia', 'lower-body-plyometrics'),
  ('spinal-cord-injury-paraplegia', 'high-impact'),
  ('lower-limb-amputation-unilateral', 'lower-body-plyometrics'),
  ('lower-limb-amputation-unilateral', 'high-impact'),
  ('lower-limb-amputation-unilateral', 'distance-jump'),
  ('upper-limb-amputation-unilateral', 'double-hand-support'),
  ('upper-limb-amputation-unilateral', 'floor-push'),
  ('upper-limb-amputation-unilateral', 'bilateral-push-up'),
  ('hemiplegia-hemiparesis', 'high-speed'),
  ('hemiplegia-hemiparesis', 'lower-body-plyometrics'),
  ('hemiplegia-hemiparesis', 'high-impact'),
  ('hemiplegia-hemiparesis', 'spatial-travel'),
  ('cerebral-palsy-mild-moderate', 'high-speed'),
  ('cerebral-palsy-mild-moderate', 'lower-body-plyometrics'),
  ('cerebral-palsy-mild-moderate', 'high-impact'),
  ('achondroplasia', 'lumbar-impact'),
  ('achondroplasia', 'long-lever'),
  ('achondroplasia', 'high-impact'),
  ('visual-impairment', 'spatial-travel'),
  ('visual-impairment', 'distance-jump'),
  ('visual-impairment', 'high-speed'),
  ('torn-acl', 'high-impact'),
  ('torn-acl', 'lower-body-plyometrics'),
  ('torn-acl', 'rotational-instability'),
  ('torn-acl', 'spatial-travel'),
  ('torn-pcl', 'tibial-posterior-load'),
  ('torn-pcl', 'deep-knee-flexion'),
  ('torn-pcl', 'high-impact'),
  ('collateral-ligament-injury', 'knee-lateral-force'),
  ('collateral-ligament-injury', 'spatial-travel'),
  ('collateral-ligament-injury', 'lower-body-plyometrics'),
  ('chondromalacia', 'deep-knee-flexion'),
  ('chondromalacia', 'lower-body-plyometrics'),
  ('chondromalacia', 'high-impact'),
  ('patellar-tendinopathy', 'lower-body-plyometrics'),
  ('patellar-tendinopathy', 'high-impact'),
  ('patellar-tendinopathy', 'high-speed'),
  ('knee-osteoarthritis', 'high-impact'),
  ('knee-osteoarthritis', 'lower-body-plyometrics'),
  ('knee-osteoarthritis', 'unilateral-full-load'),
  ('trochanteric-bursitis', 'side-lying-pressure'),
  ('piriformis-syndrome', 'deep-hip-flexion'),
  ('femoroacetabular-impingement', 'deep-hip-flexion'),
  ('femoroacetabular-impingement', 'deep-knee-flexion'),
  ('athletic-pubalgia', 'explosive-adductors'),
  ('athletic-pubalgia', 'high-intra-abdominal-pressure'),
  ('ankle-ligament-sprain', 'unstable-base'),
  ('ankle-ligament-sprain', 'spatial-travel'),
  ('ankle-ligament-sprain', 'knee-lateral-force'),
  ('plantar-fasciitis', 'forefoot-impact'),
  ('plantar-fasciitis', 'lower-body-plyometrics'),
  ('plantar-fasciitis', 'high-impact'),
  ('rotator-cuff-injury', 'overhead-press'),
  ('rotator-cuff-injury', 'lateral-raise-above-90'),
  ('subacromial-bursitis', 'overhead-press'),
  ('subacromial-bursitis', 'lateral-raise-above-90'),
  ('slap-tear', 'hanging-traction'),
  ('shoulder-instability', 'wide-arm-tension'),
  ('shoulder-instability', 'bilateral-push-up'),
  ('ac-joint-injury', 'cross-body-load'),
  ('ac-joint-injury', 'floor-push'),
  ('epicondylitis', 'prolonged-grip'),
  ('elbow-ucl-injury', 'elbow-valgus-load'),
  ('elbow-ucl-injury', 'wide-arm-tension'),
  ('olecranon-bursitis', 'forearm-plank-hard'),
  ('carpal-tunnel-de-quervain', 'wrist-extension-load'),
  ('carpal-tunnel-de-quervain', 'floor-push'),
  ('tfcc-injury', 'wrist-extension-load'),
  ('disc-herniation', 'spine-flexion-rotation'),
  ('disc-herniation', 'high-impact'),
  ('disc-herniation', 'axial-load'),
  ('disc-herniation', 'lumbar-impact'),
  ('spondylolisthesis', 'spine-hyperextension'),
  ('spondylolisthesis', 'axial-load'),
  ('spinal-stenosis', 'spine-hyperextension'),
  ('diastasis-recti', 'high-intra-abdominal-pressure'),
  ('osteoporosis-osteopenia', 'lower-body-plyometrics'),
  ('osteoporosis-osteopenia', 'high-impact'),
  ('osteoporosis-osteopenia', 'spine-flexion-rotation'),
  ('rheumatoid-arthritis', 'high-impact'),
  ('rheumatoid-arthritis', 'wrist-extension-load'),
  ('rheumatoid-arthritis', 'prolonged-grip'),
  ('chronic-muscle-strain', 'max-range-stretch'),
  ('chronic-muscle-strain', 'high-speed'),
  ('hypertension', 'high-intensity'),
  ('hypertension', 'inversion'),
  ('labyrinthitis', 'spin'),
  ('labyrinthitis', 'inversion'),
  ('hernia', 'spine-flexion-rotation'),
  ('hernia', 'high-impact'),
  ('hernia', 'axial-load'),
  ('hernia', 'lumbar-impact'),
  ('pregnancy-trimester-1', 'high-impact'),
  ('pregnancy-trimester-1', 'lower-body-plyometrics'),
  ('pregnancy-trimester-2', 'prone-position'),
  ('pregnancy-trimester-2', 'high-impact'),
  ('pregnancy-trimester-2', 'lower-body-plyometrics'),
  ('pregnancy-trimester-3', 'prone-position'),
  ('pregnancy-trimester-3', 'high-impact'),
  ('pregnancy-trimester-3', 'lower-body-plyometrics'),
  ('pregnancy-trimester-3', 'high-intensity'),
  ('pregnancy-trimester-3', 'inversion'),
  ('postpartum', 'high-impact'),
  ('postpartum', 'lower-body-plyometrics'),
  ('postpartum', 'high-intra-abdominal-pressure')
on conflict (condition_slug, blocked_content_tag) do nothing;

update public.exercises_library
set contraindication_tags = array['chondromalacia', 'femoroacetabular-impingement', 'knee-osteoarthritis', 'torn-pcl']::text[],
    updated_at = now()
where id = 'a4529e30-5fa2-461c-855a-bdc548c927c7';

update public.exercises_library
set contraindication_tags = array['ankle-ligament-sprain', 'chondromalacia', 'chronic-muscle-strain', 'collateral-ligament-injury', 'femoroacetabular-impingement', 'knee-osteoarthritis', 'torn-acl', 'torn-pcl']::text[],
    updated_at = now()
where id = 'c7e2cd90-3a67-41cb-86bd-470023e6103d';

update public.exercises_library
set contraindication_tags = array['chondromalacia', 'femoroacetabular-impingement', 'hypertension', 'knee-osteoarthritis', 'torn-pcl']::text[],
    updated_at = now()
where id = '4d4700a1-e0bd-4c25-8e6e-ce498c9481d9';

update public.exercises_library
set contraindication_tags = array['chondromalacia', 'femoroacetabular-impingement', 'knee-osteoarthritis', 'lower-limb-amputation-unilateral', 'patellar-tendinopathy', 'torn-acl', 'torn-pcl']::text[],
    updated_at = now()
where id = '99e9323c-5ed7-4414-83ab-046d27d1213a';

update public.exercises_library
set contraindication_tags = array['ankle-ligament-sprain', 'chondromalacia', 'collateral-ligament-injury', 'femoroacetabular-impingement', 'knee-osteoarthritis', 'piriformis-syndrome', 'torn-acl', 'torn-pcl']::text[],
    updated_at = now()
where id = '174207e3-e81a-4cbf-8d37-dc2b0aa6c92c';

update public.exercises_library
set contraindication_tags = array['chondromalacia', 'femoroacetabular-impingement', 'hypertension', 'knee-osteoarthritis', 'lower-limb-amputation-unilateral', 'patellar-tendinopathy', 'pregnancy-trimester-3', 'torn-acl', 'torn-pcl']::text[],
    updated_at = now()
where id = 'df25b5ed-e826-49bc-8288-68a5cf0415c8';

update public.exercises_library
set contraindication_tags = array['chondromalacia', 'femoroacetabular-impingement', 'hypertension', 'knee-osteoarthritis', 'patellar-tendinopathy', 'pregnancy-trimester-3', 'torn-acl', 'torn-pcl']::text[],
    updated_at = now()
where id = '04020eda-4114-46b4-8a88-580f71762fb7';

update public.exercises_library
set contraindication_tags = array['chondromalacia', 'femoroacetabular-impingement', 'knee-osteoarthritis', 'piriformis-syndrome', 'torn-pcl']::text[],
    updated_at = now()
where id = '10921525-e39d-4e1f-8a58-4296addd06d6';

update public.exercises_library
set contraindication_tags = array['chondromalacia', 'femoroacetabular-impingement', 'knee-osteoarthritis', 'torn-pcl']::text[],
    updated_at = now()
where id = 'c3fc0ba1-6207-47d7-8ce4-9f2dc0889173';

update public.exercises_library
set contraindication_tags = array['achondroplasia', 'cerebral-palsy-mild-moderate', 'chondromalacia', 'collateral-ligament-injury', 'disc-herniation', 'hemiplegia-hemiparesis', 'hernia', 'hypertension', 'knee-osteoarthritis', 'labyrinthitis', 'lower-limb-amputation-unilateral', 'osteoporosis-osteopenia', 'patellar-tendinopathy', 'plantar-fasciitis', 'postpartum', 'pregnancy-trimester-1', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'rheumatoid-arthritis', 'spinal-cord-injury-paraplegia', 'torn-acl', 'torn-pcl', 'visual-impairment']::text[],
    updated_at = now()
where id = '9a24c328-5450-4dd1-8a8a-646eaa59389f';

update public.exercises_library
set contraindication_tags = array['achondroplasia', 'ankle-ligament-sprain', 'cerebral-palsy-mild-moderate', 'chondromalacia', 'collateral-ligament-injury', 'disc-herniation', 'hemiplegia-hemiparesis', 'hernia', 'hypertension', 'knee-osteoarthritis', 'labyrinthitis', 'lower-limb-amputation-unilateral', 'osteoporosis-osteopenia', 'patellar-tendinopathy', 'plantar-fasciitis', 'postpartum', 'pregnancy-trimester-1', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'rheumatoid-arthritis', 'spinal-cord-injury-paraplegia', 'torn-acl', 'torn-pcl', 'visual-impairment']::text[],
    updated_at = now()
where id = '24c5fbaa-9da0-40e9-8694-338e323c045a';

update public.exercises_library
set contraindication_tags = array['chondromalacia', 'femoroacetabular-impingement', 'knee-osteoarthritis', 'torn-pcl']::text[],
    updated_at = now()
where id = 'be9117c6-3428-4254-8713-d4ced66de3c6';

update public.exercises_library
set contraindication_tags = array['chondromalacia', 'disc-herniation', 'femoroacetabular-impingement', 'hernia', 'knee-osteoarthritis', 'osteoporosis-osteopenia', 'spondylolisthesis', 'torn-pcl']::text[],
    updated_at = now()
where id = 'ea7afbeb-a559-42d7-8714-6ad30e3cc4ea';

update public.exercises_library
set contraindication_tags = array['ankle-ligament-sprain', 'chondromalacia', 'femoroacetabular-impingement', 'knee-osteoarthritis', 'labyrinthitis', 'torn-pcl', 'visual-impairment']::text[],
    updated_at = now()
where id = '1c1a9b68-5e23-4092-8ca2-79de0e27bc2a';

update public.exercises_library
set contraindication_tags = array['chondromalacia', 'femoroacetabular-impingement', 'knee-osteoarthritis', 'lower-limb-amputation-unilateral', 'torn-pcl']::text[],
    updated_at = now()
where id = '65b6e883-c0a9-4901-8833-81f3a32b242d';

update public.exercises_library
set contraindication_tags = array['chondromalacia', 'femoroacetabular-impingement', 'knee-osteoarthritis', 'torn-pcl']::text[],
    updated_at = now()
where id = '3b1798ca-a6f6-4930-8bc4-2b547c10e7df';

update public.exercises_library
set contraindication_tags = array['ankle-ligament-sprain', 'chondromalacia', 'collateral-ligament-injury', 'femoroacetabular-impingement', 'hemiplegia-hemiparesis', 'knee-osteoarthritis', 'patellar-tendinopathy', 'torn-acl', 'torn-pcl', 'visual-impairment']::text[],
    updated_at = now()
where id = '2cd1c0ad-f67b-4cef-8fd0-4a9feacc0f47';

update public.exercises_library
set contraindication_tags = array['chondromalacia', 'femoroacetabular-impingement', 'knee-osteoarthritis', 'torn-pcl']::text[],
    updated_at = now()
where id = '35338f11-4e2c-4792-8f2c-c5e93520acce';

update public.exercises_library
set contraindication_tags = array['ankle-ligament-sprain', 'collateral-ligament-injury', 'femoroacetabular-impingement', 'hemiplegia-hemiparesis', 'piriformis-syndrome', 'torn-acl', 'visual-impairment']::text[],
    updated_at = now()
where id = '3a8188ae-38fb-4f46-86e9-7c9cf0b60ee7';

update public.exercises_library
set contraindication_tags = array['ankle-ligament-sprain', 'cerebral-palsy-mild-moderate', 'chondromalacia', 'chronic-muscle-strain', 'collateral-ligament-injury', 'femoroacetabular-impingement', 'hemiplegia-hemiparesis', 'knee-osteoarthritis', 'labyrinthitis', 'patellar-tendinopathy', 'torn-acl', 'torn-pcl', 'visual-impairment']::text[],
    updated_at = now()
where id = '614d7ec5-1d3a-4e58-84d0-27b9b52d3460';

update public.exercises_library
set contraindication_tags = array['chondromalacia', 'femoroacetabular-impingement', 'knee-osteoarthritis', 'torn-pcl']::text[],
    updated_at = now()
where id = 'b00bf0ff-7e18-4dd1-83c3-5d021e719f8c';

update public.exercises_library
set contraindication_tags = array['achondroplasia', 'ankle-ligament-sprain', 'cerebral-palsy-mild-moderate', 'chondromalacia', 'collateral-ligament-injury', 'disc-herniation', 'hemiplegia-hemiparesis', 'hernia', 'hypertension', 'knee-osteoarthritis', 'labyrinthitis', 'lower-limb-amputation-unilateral', 'osteoporosis-osteopenia', 'patellar-tendinopathy', 'plantar-fasciitis', 'postpartum', 'pregnancy-trimester-1', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'rheumatoid-arthritis', 'spinal-cord-injury-paraplegia', 'torn-acl', 'torn-pcl', 'visual-impairment']::text[],
    updated_at = now()
where id = '9ae70a56-0ae7-4b6a-83eb-a8604a2c5c57';

update public.exercises_library
set contraindication_tags = array['ankle-ligament-sprain', 'chondromalacia', 'collateral-ligament-injury', 'femoroacetabular-impingement', 'hemiplegia-hemiparesis', 'knee-osteoarthritis', 'labyrinthitis', 'torn-acl', 'torn-pcl', 'visual-impairment']::text[],
    updated_at = now()
where id = '34212438-c891-4f61-8d07-c5e3e2a40c88';

update public.exercises_library
set contraindication_tags = array['ankle-ligament-sprain', 'collateral-ligament-injury', 'femoroacetabular-impingement', 'piriformis-syndrome', 'torn-acl']::text[],
    updated_at = now()
where id = '635d6a6f-c250-4e26-846c-ec536de3c9c0';

update public.exercises_library
set contraindication_tags = '{}'::text[],
    updated_at = now()
where id = '5e7c8a73-f2fd-48e4-8085-80f1d8482657';

update public.exercises_library
set contraindication_tags = array['knee-osteoarthritis', 'lower-limb-amputation-unilateral']::text[],
    updated_at = now()
where id = 'b145eec6-2533-4870-8bd4-35626d2c258e';

update public.exercises_library
set contraindication_tags = array['disc-herniation', 'hernia', 'spinal-stenosis', 'spondylolisthesis']::text[],
    updated_at = now()
where id = '817328cc-bc72-4d84-8406-faed6a8c85d1';

update public.exercises_library
set contraindication_tags = array['femoroacetabular-impingement', 'piriformis-syndrome', 'trochanteric-bursitis']::text[],
    updated_at = now()
where id = 'eadfec12-131c-4989-8d6e-b0ed2999ce8c';

update public.exercises_library
set contraindication_tags = array['chronic-muscle-strain', 'disc-herniation', 'hernia', 'osteoporosis-osteopenia', 'spondylolisthesis']::text[],
    updated_at = now()
where id = '7dc112d3-d066-4315-8e21-ddc0597af349';

update public.exercises_library
set contraindication_tags = array['chronic-muscle-strain']::text[],
    updated_at = now()
where id = '18b4ddd5-f81e-4c77-84d8-7bc54e297835';

update public.exercises_library
set contraindication_tags = array['chronic-muscle-strain']::text[],
    updated_at = now()
where id = '3ca074f7-8f39-4b8a-810a-f5dddfe72c3c';

update public.exercises_library
set contraindication_tags = array['carpal-tunnel-de-quervain', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'rheumatoid-arthritis', 'tfcc-injury']::text[],
    updated_at = now()
where id = '43d7af7c-ae52-4e3c-807e-65c6d185465b';

update public.exercises_library
set contraindication_tags = array['carpal-tunnel-de-quervain', 'piriformis-syndrome', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'rheumatoid-arthritis', 'tfcc-injury', 'trochanteric-bursitis']::text[],
    updated_at = now()
where id = '51726f8a-becd-4158-8114-ace81abe5874';

update public.exercises_library
set contraindication_tags = array['trochanteric-bursitis']::text[],
    updated_at = now()
where id = '8555be14-76a5-4b2d-8c35-ac47e6ab0ed0';

update public.exercises_library
set contraindication_tags = array['piriformis-syndrome', 'trochanteric-bursitis']::text[],
    updated_at = now()
where id = '790a99ea-b649-4840-8511-5bb6daeb6e8e';

update public.exercises_library
set contraindication_tags = array['ankle-ligament-sprain', 'collateral-ligament-injury', 'hemiplegia-hemiparesis', 'torn-acl', 'visual-impairment']::text[],
    updated_at = now()
where id = '955add04-8118-47b9-89ae-490646a01cc1';

update public.exercises_library
set contraindication_tags = array['chronic-muscle-strain', 'disc-herniation', 'hernia', 'osteoporosis-osteopenia', 'spondylolisthesis']::text[],
    updated_at = now()
where id = '248bf262-ddf6-46f6-82da-a87a63496f9c';

update public.exercises_library
set contraindication_tags = array['chondromalacia', 'femoroacetabular-impingement', 'hypertension', 'knee-osteoarthritis', 'torn-pcl']::text[],
    updated_at = now()
where id = '06dbbcfb-d5d2-475f-84d1-1f1febd8956b';

update public.exercises_library
set contraindication_tags = array['ankle-ligament-sprain', 'chondromalacia', 'collateral-ligament-injury', 'femoroacetabular-impingement', 'hemiplegia-hemiparesis', 'hypertension', 'knee-osteoarthritis', 'labyrinthitis', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'torn-acl', 'torn-pcl', 'visual-impairment']::text[],
    updated_at = now()
where id = '8ff75a53-d59e-4a58-83d8-f7c09ff6f36f';

update public.exercises_library
set contraindication_tags = array['chondromalacia', 'knee-osteoarthritis', 'lower-limb-amputation-unilateral', 'patellar-tendinopathy', 'pregnancy-trimester-3', 'torn-acl', 'torn-pcl']::text[],
    updated_at = now()
where id = 'f0192e92-75c1-42bd-8123-401cd3e19e4a';

update public.exercises_library
set contraindication_tags = array['ankle-ligament-sprain', 'plantar-fasciitis']::text[],
    updated_at = now()
where id = '4ef78f98-8784-45c4-8b0f-f2de30d566cd';

update public.exercises_library
set contraindication_tags = array['ankle-ligament-sprain', 'knee-osteoarthritis', 'plantar-fasciitis']::text[],
    updated_at = now()
where id = '4c362df5-53d1-42a3-8cf4-ad2e8ae5c199';

update public.exercises_library
set contraindication_tags = array['plantar-fasciitis']::text[],
    updated_at = now()
where id = 'ebd3d29e-49f3-413b-843c-65a6c0360e98';

update public.exercises_library
set contraindication_tags = array['achondroplasia', 'cerebral-palsy-mild-moderate', 'chondromalacia', 'collateral-ligament-injury', 'disc-herniation', 'hemiplegia-hemiparesis', 'hernia', 'hypertension', 'knee-osteoarthritis', 'labyrinthitis', 'lower-limb-amputation-unilateral', 'osteoporosis-osteopenia', 'patellar-tendinopathy', 'plantar-fasciitis', 'postpartum', 'pregnancy-trimester-1', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'rheumatoid-arthritis', 'spinal-cord-injury-paraplegia', 'torn-acl', 'torn-pcl', 'visual-impairment']::text[],
    updated_at = now()
where id = '1e4e9256-2962-44f5-8905-6168d642aa66';

update public.exercises_library
set contraindication_tags = array['ac-joint-injury', 'carpal-tunnel-de-quervain', 'rheumatoid-arthritis', 'shoulder-instability', 'slap-tear', 'tfcc-injury', 'upper-limb-amputation-unilateral']::text[],
    updated_at = now()
where id = '43e3b176-1c4c-46e1-8fbe-ff4e1d0a7f12';

update public.exercises_library
set contraindication_tags = array['ac-joint-injury', 'carpal-tunnel-de-quervain', 'rheumatoid-arthritis', 'shoulder-instability', 'slap-tear', 'tfcc-injury', 'upper-limb-amputation-unilateral']::text[],
    updated_at = now()
where id = '04b300ac-80a6-4db9-8ab8-9c8e75739654';

update public.exercises_library
set contraindication_tags = array['ac-joint-injury', 'carpal-tunnel-de-quervain', 'elbow-ucl-injury', 'epicondylitis', 'hypertension', 'olecranon-bursitis', 'pregnancy-trimester-3', 'rheumatoid-arthritis', 'tfcc-injury', 'upper-limb-amputation-unilateral']::text[],
    updated_at = now()
where id = '22a47d33-b934-499f-8aa4-ad9762b2ac7b';

update public.exercises_library
set contraindication_tags = array['ac-joint-injury', 'carpal-tunnel-de-quervain', 'elbow-ucl-injury', 'rheumatoid-arthritis', 'shoulder-instability', 'slap-tear', 'tfcc-injury', 'upper-limb-amputation-unilateral']::text[],
    updated_at = now()
where id = 'd9c44890-7cee-4100-8a15-ecc872df8306';

update public.exercises_library
set contraindication_tags = array['ac-joint-injury', 'carpal-tunnel-de-quervain', 'hypertension', 'pregnancy-trimester-3', 'rheumatoid-arthritis', 'rotator-cuff-injury', 'shoulder-instability', 'subacromial-bursitis', 'tfcc-injury', 'upper-limb-amputation-unilateral']::text[],
    updated_at = now()
where id = '3e896eee-0134-4fa4-8035-4919eba34b26';

update public.exercises_library
set contraindication_tags = array['ac-joint-injury', 'carpal-tunnel-de-quervain', 'rheumatoid-arthritis', 'tfcc-injury', 'upper-limb-amputation-unilateral']::text[],
    updated_at = now()
where id = '1b1bac00-e0e2-44e8-8fd8-b590190c7002';

update public.exercises_library
set contraindication_tags = array['carpal-tunnel-de-quervain', 'hypertension', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'rheumatoid-arthritis', 'rotator-cuff-injury', 'shoulder-instability', 'subacromial-bursitis', 'tfcc-injury']::text[],
    updated_at = now()
where id = 'c02bc932-0be4-491a-8b43-083bd1150262';

update public.exercises_library
set contraindication_tags = array['carpal-tunnel-de-quervain', 'hypertension', 'labyrinthitis', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'rheumatoid-arthritis', 'rotator-cuff-injury', 'shoulder-instability', 'subacromial-bursitis', 'tfcc-injury']::text[],
    updated_at = now()
where id = '0cbf40c6-aae5-4361-8f40-328c61804749';

update public.exercises_library
set contraindication_tags = array['ac-joint-injury', 'carpal-tunnel-de-quervain', 'rheumatoid-arthritis', 'shoulder-instability', 'slap-tear', 'tfcc-injury', 'upper-limb-amputation-unilateral']::text[],
    updated_at = now()
where id = 'b4fbe1c1-c34e-4c17-8085-49aa488d8c61';

update public.exercises_library
set contraindication_tags = array['ac-joint-injury', 'carpal-tunnel-de-quervain', 'elbow-ucl-injury', 'hypertension', 'pregnancy-trimester-3', 'rheumatoid-arthritis', 'shoulder-instability', 'slap-tear', 'tfcc-injury', 'upper-limb-amputation-unilateral']::text[],
    updated_at = now()
where id = '09f276c3-98af-4290-87fa-ec68dcab9d44';

update public.exercises_library
set contraindication_tags = array['ac-joint-injury', 'carpal-tunnel-de-quervain', 'elbow-ucl-injury', 'hypertension', 'pregnancy-trimester-3', 'rheumatoid-arthritis', 'shoulder-instability', 'slap-tear', 'tfcc-injury', 'upper-limb-amputation-unilateral']::text[],
    updated_at = now()
where id = 'd6ebb4db-6cd3-4ace-8ab7-5bd52b625566';

update public.exercises_library
set contraindication_tags = array['ac-joint-injury', 'carpal-tunnel-de-quervain', 'femoroacetabular-impingement', 'piriformis-syndrome', 'rheumatoid-arthritis', 'tfcc-injury', 'upper-limb-amputation-unilateral']::text[],
    updated_at = now()
where id = '2e63dfdd-c187-4940-8b65-c1165cae8959';

update public.exercises_library
set contraindication_tags = array['ac-joint-injury', 'carpal-tunnel-de-quervain', 'disc-herniation', 'hernia', 'hypertension', 'pregnancy-trimester-3', 'rheumatoid-arthritis', 'rotator-cuff-injury', 'shoulder-instability', 'spinal-stenosis', 'spondylolisthesis', 'subacromial-bursitis', 'tfcc-injury', 'upper-limb-amputation-unilateral']::text[],
    updated_at = now()
where id = '1cfe53af-be71-49c2-8551-17e5885f1929';

update public.exercises_library
set contraindication_tags = array['ac-joint-injury', 'carpal-tunnel-de-quervain', 'elbow-ucl-injury', 'hypertension', 'pregnancy-trimester-3', 'rheumatoid-arthritis', 'shoulder-instability', 'slap-tear', 'tfcc-injury', 'upper-limb-amputation-unilateral']::text[],
    updated_at = now()
where id = '549d4c00-9ec2-4511-87a0-59bc6916d410';

update public.exercises_library
set contraindication_tags = array['ac-joint-injury', 'achondroplasia', 'carpal-tunnel-de-quervain', 'cerebral-palsy-mild-moderate', 'chondromalacia', 'chronic-muscle-strain', 'disc-herniation', 'hemiplegia-hemiparesis', 'hernia', 'hypertension', 'knee-osteoarthritis', 'labyrinthitis', 'lower-limb-amputation-unilateral', 'osteoporosis-osteopenia', 'patellar-tendinopathy', 'plantar-fasciitis', 'postpartum', 'pregnancy-trimester-1', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'rheumatoid-arthritis', 'shoulder-instability', 'slap-tear', 'spinal-cord-injury-paraplegia', 'tfcc-injury', 'torn-acl', 'torn-pcl', 'upper-limb-amputation-unilateral', 'visual-impairment']::text[],
    updated_at = now()
where id = '8b21c1e5-dfea-417c-8f72-619eaa1fce05';

update public.exercises_library
set contraindication_tags = array['carpal-tunnel-de-quervain', 'elbow-ucl-injury', 'epicondylitis', 'olecranon-bursitis', 'rheumatoid-arthritis', 'tfcc-injury']::text[],
    updated_at = now()
where id = '59a91f47-a120-45f3-8977-f071a39978cd';

update public.exercises_library
set contraindication_tags = array['ac-joint-injury', 'carpal-tunnel-de-quervain', 'elbow-ucl-injury', 'rheumatoid-arthritis', 'shoulder-instability', 'slap-tear', 'tfcc-injury', 'upper-limb-amputation-unilateral']::text[],
    updated_at = now()
where id = '13b2c43c-cd5f-4fbe-82a6-41b8a094d285';

update public.exercises_library
set contraindication_tags = array['ac-joint-injury', 'carpal-tunnel-de-quervain', 'disc-herniation', 'hernia', 'hypertension', 'osteoporosis-osteopenia', 'pregnancy-trimester-3', 'rheumatoid-arthritis', 'shoulder-instability', 'slap-tear', 'spondylolisthesis', 'tfcc-injury', 'upper-limb-amputation-unilateral']::text[],
    updated_at = now()
where id = '8d31f4af-e0d1-46c8-8891-51f91663e611';

update public.exercises_library
set contraindication_tags = array['ac-joint-injury', 'carpal-tunnel-de-quervain', 'rheumatoid-arthritis', 'shoulder-instability', 'slap-tear', 'tfcc-injury', 'upper-limb-amputation-unilateral']::text[],
    updated_at = now()
where id = 'ebc3eb51-e8a5-49bf-8fa8-a3af975502ac';

update public.exercises_library
set contraindication_tags = array['ac-joint-injury', 'shoulder-instability', 'slap-tear']::text[],
    updated_at = now()
where id = '6bbd511f-41b4-4ba4-867f-392ad7b9d883';

update public.exercises_library
set contraindication_tags = array['ac-joint-injury', 'elbow-ucl-injury', 'shoulder-instability', 'slap-tear']::text[],
    updated_at = now()
where id = 'b45bb731-a0b0-4302-802e-de4881e88935';

update public.exercises_library
set contraindication_tags = array['disc-herniation', 'hernia', 'spondylolisthesis']::text[],
    updated_at = now()
where id = '2f902563-38a2-4d66-84f4-d07ed117b666';

update public.exercises_library
set contraindication_tags = array['upper-limb-amputation-unilateral']::text[],
    updated_at = now()
where id = 'a32f1ab4-cac2-429c-88aa-4b4b94e50c99';

update public.exercises_library
set contraindication_tags = '{}'::text[],
    updated_at = now()
where id = '6a195661-158f-48f5-85dc-5c6fd4f0f746';

update public.exercises_library
set contraindication_tags = array['rotator-cuff-injury', 'shoulder-instability', 'slap-tear']::text[],
    updated_at = now()
where id = '84c1df51-a467-471f-804a-46bf8ee2a0cd';

update public.exercises_library
set contraindication_tags = array['pregnancy-trimester-2', 'pregnancy-trimester-3', 'rotator-cuff-injury', 'shoulder-instability', 'subacromial-bursitis']::text[],
    updated_at = now()
where id = '8b238d79-5ef6-47ca-8175-3e694a5b8632';

update public.exercises_library
set contraindication_tags = array['pregnancy-trimester-2', 'pregnancy-trimester-3']::text[],
    updated_at = now()
where id = '3b20a252-f498-4eb9-88ef-e09d196055b4';

update public.exercises_library
set contraindication_tags = array['disc-herniation', 'hernia', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'spinal-stenosis', 'spondylolisthesis']::text[],
    updated_at = now()
where id = 'f01d0b05-2a56-447c-8bf6-db674ffe96d0';

update public.exercises_library
set contraindication_tags = array['rotator-cuff-injury', 'shoulder-instability', 'slap-tear', 'subacromial-bursitis']::text[],
    updated_at = now()
where id = '7eebc5e8-08ea-423d-84ac-9861b71319b1';

update public.exercises_library
set contraindication_tags = array['rotator-cuff-injury', 'shoulder-instability', 'subacromial-bursitis']::text[],
    updated_at = now()
where id = '1f9fbfc3-8ca6-42c4-82ce-00a3f73a166d';

update public.exercises_library
set contraindication_tags = array['rotator-cuff-injury', 'shoulder-instability', 'subacromial-bursitis']::text[],
    updated_at = now()
where id = 'bfaa14af-eb1c-4798-812f-b60c0389e416';

update public.exercises_library
set contraindication_tags = array['rotator-cuff-injury', 'shoulder-instability', 'subacromial-bursitis']::text[],
    updated_at = now()
where id = '621c4d71-ee07-4b0e-8b1e-ee6f7ef34f6d';

update public.exercises_library
set contraindication_tags = array['ac-joint-injury']::text[],
    updated_at = now()
where id = 'cef854b7-86a8-497c-8f0f-6ac8d92106ca';

update public.exercises_library
set contraindication_tags = array['ac-joint-injury', 'elbow-ucl-injury', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'shoulder-instability', 'slap-tear']::text[],
    updated_at = now()
where id = '553981fd-b368-41e2-8288-372d2c55f585';

update public.exercises_library
set contraindication_tags = array['carpal-tunnel-de-quervain', 'elbow-ucl-injury', 'epicondylitis', 'olecranon-bursitis', 'rheumatoid-arthritis', 'tfcc-injury']::text[],
    updated_at = now()
where id = '2fe33432-2b8d-4b4f-84f1-b464f1620ecf';

update public.exercises_library
set contraindication_tags = array['carpal-tunnel-de-quervain', 'elbow-ucl-injury', 'epicondylitis', 'olecranon-bursitis', 'rheumatoid-arthritis', 'shoulder-instability', 'tfcc-injury']::text[],
    updated_at = now()
where id = '4beb20eb-7602-46b0-8f7d-f5bf4fe7d35e';

update public.exercises_library
set contraindication_tags = array['elbow-ucl-injury', 'epicondylitis', 'olecranon-bursitis', 'rotator-cuff-injury', 'shoulder-instability', 'subacromial-bursitis']::text[],
    updated_at = now()
where id = '7d76305b-348d-4220-8d12-2eeccec609e8';

update public.exercises_library
set contraindication_tags = array['elbow-ucl-injury', 'epicondylitis', 'olecranon-bursitis']::text[],
    updated_at = now()
where id = '25d4aa1b-e1f5-4e30-88de-5e08bb5fd94c';

update public.exercises_library
set contraindication_tags = array['elbow-ucl-injury', 'epicondylitis', 'olecranon-bursitis']::text[],
    updated_at = now()
where id = 'e7bd0351-8f56-4b9e-8cc4-5b1e3b3d54ad';

update public.exercises_library
set contraindication_tags = array['elbow-ucl-injury', 'epicondylitis', 'olecranon-bursitis', 'rheumatoid-arthritis']::text[],
    updated_at = now()
where id = '9512d49d-885d-436f-8082-e9fab95895e0';

update public.exercises_library
set contraindication_tags = array['elbow-ucl-injury', 'epicondylitis', 'olecranon-bursitis', 'rheumatoid-arthritis']::text[],
    updated_at = now()
where id = 'ab76b38f-54b7-4aa5-89a3-ab6f31d22617';

update public.exercises_library
set contraindication_tags = array['carpal-tunnel-de-quervain', 'rheumatoid-arthritis', 'tfcc-injury']::text[],
    updated_at = now()
where id = '3b6c2a7b-aa88-44cb-8a0d-77854f584fb5';

update public.exercises_library
set contraindication_tags = array['athletic-pubalgia', 'diastasis-recti', 'hypertension', 'olecranon-bursitis', 'postpartum']::text[],
    updated_at = now()
where id = 'b49602f2-ae55-4f3d-8edd-5df7197edb73';

update public.exercises_library
set contraindication_tags = array['ankle-ligament-sprain', 'athletic-pubalgia', 'diastasis-recti', 'labyrinthitis', 'postpartum']::text[],
    updated_at = now()
where id = '2f9bb67b-4a4a-4180-871b-48feca482bdd';

update public.exercises_library
set contraindication_tags = array['athletic-pubalgia', 'diastasis-recti', 'olecranon-bursitis', 'trochanteric-bursitis']::text[],
    updated_at = now()
where id = '5c1894da-9411-4df2-8358-ab70e80025ad';

update public.exercises_library
set contraindication_tags = array['athletic-pubalgia', 'diastasis-recti', 'trochanteric-bursitis']::text[],
    updated_at = now()
where id = '852db82d-6f18-4174-84ae-a61b225aaab5';

update public.exercises_library
set contraindication_tags = array['ac-joint-injury', 'athletic-pubalgia', 'carpal-tunnel-de-quervain', 'diastasis-recti', 'rheumatoid-arthritis', 'tfcc-injury', 'upper-limb-amputation-unilateral']::text[],
    updated_at = now()
where id = '3acddcaa-2888-4e15-8fb6-7420ca8d019f';

update public.exercises_library
set contraindication_tags = array['athletic-pubalgia', 'carpal-tunnel-de-quervain', 'diastasis-recti', 'elbow-ucl-injury', 'epicondylitis', 'olecranon-bursitis', 'rheumatoid-arthritis', 'tfcc-injury']::text[],
    updated_at = now()
where id = 'c504a8f8-aa8d-48d8-8f49-6edd1bd9ec6e';

update public.exercises_library
set contraindication_tags = array['athletic-pubalgia', 'cerebral-palsy-mild-moderate', 'chondromalacia', 'collateral-ligament-injury', 'diastasis-recti', 'hemiplegia-hemiparesis', 'hypertension', 'knee-osteoarthritis', 'labyrinthitis', 'lower-limb-amputation-unilateral', 'osteoporosis-osteopenia', 'patellar-tendinopathy', 'plantar-fasciitis', 'postpartum', 'pregnancy-trimester-1', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'spinal-cord-injury-paraplegia', 'torn-acl', 'visual-impairment']::text[],
    updated_at = now()
where id = '9b47264e-b98c-4082-8617-1e671bfe00a5';

update public.exercises_library
set contraindication_tags = array['achondroplasia', 'athletic-pubalgia', 'cerebral-palsy-mild-moderate', 'chondromalacia', 'collateral-ligament-injury', 'diastasis-recti', 'disc-herniation', 'hemiplegia-hemiparesis', 'hernia', 'hypertension', 'knee-osteoarthritis', 'labyrinthitis', 'lower-limb-amputation-unilateral', 'osteoporosis-osteopenia', 'patellar-tendinopathy', 'plantar-fasciitis', 'postpartum', 'pregnancy-trimester-1', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'rheumatoid-arthritis', 'spinal-cord-injury-paraplegia', 'torn-acl', 'torn-pcl', 'visual-impairment']::text[],
    updated_at = now()
where id = '2a45eba2-8788-478e-8bb3-5971fb3c8877';

update public.exercises_library
set contraindication_tags = array['carpal-tunnel-de-quervain', 'rheumatoid-arthritis', 'shoulder-instability', 'tfcc-injury']::text[],
    updated_at = now()
where id = '475045c7-965f-4f7d-8bd2-6ae14ff60ad8';

update public.exercises_library
set contraindication_tags = array['ac-joint-injury', 'athletic-pubalgia', 'carpal-tunnel-de-quervain', 'diastasis-recti', 'rheumatoid-arthritis', 'tfcc-injury', 'upper-limb-amputation-unilateral']::text[],
    updated_at = now()
where id = '0b034b83-cefe-4fe3-8758-5ee7fde7e41d';

update public.exercises_library
set contraindication_tags = array['disc-herniation', 'hernia', 'pregnancy-trimester-2', 'pregnancy-trimester-3']::text[],
    updated_at = now()
where id = 'eaeb4484-396c-41ab-8206-1d5ba6b720f4';

update public.exercises_library
set contraindication_tags = array['athletic-pubalgia', 'diastasis-recti', 'disc-herniation', 'hernia', 'pregnancy-trimester-2', 'pregnancy-trimester-3']::text[],
    updated_at = now()
where id = '3b00282c-bef9-4820-87b4-89bcf781930b';

update public.exercises_library
set contraindication_tags = array['athletic-pubalgia', 'diastasis-recti', 'disc-herniation', 'hernia', 'osteoporosis-osteopenia', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'spondylolisthesis']::text[],
    updated_at = now()
where id = '19365006-11af-441f-8061-8aa7bb913caf';

update public.exercises_library
set contraindication_tags = array['athletic-pubalgia', 'diastasis-recti', 'disc-herniation', 'femoroacetabular-impingement', 'hernia', 'piriformis-syndrome', 'postpartum']::text[],
    updated_at = now()
where id = '42f57da7-e61a-4d8a-804a-2c6d4d73da92';

update public.exercises_library
set contraindication_tags = array['disc-herniation', 'hernia', 'osteoporosis-osteopenia', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'spondylolisthesis']::text[],
    updated_at = now()
where id = '2a31cdbe-d5c5-440c-8e37-a7125caf00ce';

update public.exercises_library
set contraindication_tags = array['athletic-pubalgia', 'diastasis-recti', 'disc-herniation', 'hernia', 'hypertension', 'postpartum', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'spondylolisthesis']::text[],
    updated_at = now()
where id = '7ddbbfd5-51c8-49f9-83e7-9ff17d3dacce';

update public.exercises_library
set contraindication_tags = array['athletic-pubalgia', 'diastasis-recti', 'postpartum', 'pregnancy-trimester-2', 'pregnancy-trimester-3']::text[],
    updated_at = now()
where id = '29f4fc71-cec9-4617-8a1e-37cefeffacd1';

update public.exercises_library
set contraindication_tags = array['femoroacetabular-impingement', 'piriformis-syndrome', 'pregnancy-trimester-2', 'pregnancy-trimester-3']::text[],
    updated_at = now()
where id = '3d53c9ed-ab56-438c-8c1c-99fff818be61';

update public.exercises_library
set contraindication_tags = array['pregnancy-trimester-2', 'pregnancy-trimester-3']::text[],
    updated_at = now()
where id = 'd21934be-e4b7-4977-8289-482bf1500afb';

update public.exercises_library
set contraindication_tags = array['disc-herniation', 'hernia', 'osteoporosis-osteopenia', 'spondylolisthesis']::text[],
    updated_at = now()
where id = '5503bb24-87bc-4642-8d3c-41fef523cab7';

update public.exercises_library
set contraindication_tags = array['athletic-pubalgia', 'diastasis-recti', 'disc-herniation', 'hernia', 'spondylolisthesis']::text[],
    updated_at = now()
where id = '98976610-fc69-4565-8915-41c858450ef8';

update public.exercises_library
set contraindication_tags = array['athletic-pubalgia', 'carpal-tunnel-de-quervain', 'diastasis-recti', 'hypertension', 'postpartum', 'pregnancy-trimester-3', 'rheumatoid-arthritis', 'rotator-cuff-injury', 'shoulder-instability', 'subacromial-bursitis', 'tfcc-injury']::text[],
    updated_at = now()
where id = 'b6993d3e-9b4c-4ffe-870e-0225bfc93451';

update public.exercises_library
set contraindication_tags = array['pregnancy-trimester-3']::text[],
    updated_at = now()
where id = 'fd066298-4e12-401b-8a91-2103b60bcdef';

update public.exercises_library
set contraindication_tags = array['disc-herniation', 'hernia', 'osteoporosis-osteopenia', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'spondylolisthesis']::text[],
    updated_at = now()
where id = '73a40a70-dd29-490e-89a3-145586a8f153';

update public.exercises_library
set contraindication_tags = array['carpal-tunnel-de-quervain', 'rheumatoid-arthritis', 'tfcc-injury']::text[],
    updated_at = now()
where id = '96e2c21e-82d3-43e7-8b3c-4395fde90dfc';

update public.exercises_library
set contraindication_tags = array['athletic-pubalgia', 'diastasis-recti', 'disc-herniation', 'hernia', 'postpartum']::text[],
    updated_at = now()
where id = '23873d65-62d8-4d71-8c96-214f280e59e8';

update public.exercises_library
set contraindication_tags = array['athletic-pubalgia', 'diastasis-recti', 'disc-herniation', 'hernia', 'labyrinthitis', 'postpartum']::text[],
    updated_at = now()
where id = '8d3534d6-828b-4352-8c5b-81fd73ce1dd4';

update public.exercises_library
set contraindication_tags = '{}'::text[],
    updated_at = now()
where id = 'bc2234d8-d9ad-457e-8f50-345a12bb59cf';

update public.exercises_library
set contraindication_tags = array['athletic-pubalgia', 'diastasis-recti', 'disc-herniation', 'hernia', 'postpartum']::text[],
    updated_at = now()
where id = 'c4ff7454-d2bf-43ff-856a-055f0480799c';

update public.exercises_library
set contraindication_tags = array['athletic-pubalgia', 'diastasis-recti', 'disc-herniation', 'hernia', 'postpartum']::text[],
    updated_at = now()
where id = '6f4abaf1-884a-4dec-8567-a882eeaf0365';

update public.exercises_library
set contraindication_tags = array['athletic-pubalgia', 'diastasis-recti', 'disc-herniation', 'hernia', 'hypertension', 'osteoporosis-osteopenia', 'pregnancy-trimester-3', 'spondylolisthesis']::text[],
    updated_at = now()
where id = 'fec7aaa4-94f7-477e-82ec-c42c81866bb4';

update public.exercises_library
set contraindication_tags = array['athletic-pubalgia', 'carpal-tunnel-de-quervain', 'diastasis-recti', 'hypertension', 'postpartum', 'pregnancy-trimester-3', 'rheumatoid-arthritis', 'tfcc-injury']::text[],
    updated_at = now()
where id = '513b6fe5-4087-4f87-8b86-29be4ed9b0b8';

update public.exercises_library
set contraindication_tags = array['disc-herniation', 'hernia', 'osteoporosis-osteopenia', 'spondylolisthesis']::text[],
    updated_at = now()
where id = 'b65619c3-341e-4556-85af-df7ac2260af9';

update public.exercises_library
set contraindication_tags = '{}'::text[],
    updated_at = now()
where id = 'b47fe78f-49d0-44b2-8305-ded38adae046';

update public.exercises_library
set contraindication_tags = array['achondroplasia', 'ankle-ligament-sprain', 'cerebral-palsy-mild-moderate', 'chondromalacia', 'collateral-ligament-injury', 'disc-herniation', 'hemiplegia-hemiparesis', 'hernia', 'knee-osteoarthritis', 'labyrinthitis', 'lower-limb-amputation-unilateral', 'osteoporosis-osteopenia', 'patellar-tendinopathy', 'plantar-fasciitis', 'postpartum', 'pregnancy-trimester-1', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'rheumatoid-arthritis', 'spinal-cord-injury-paraplegia', 'torn-acl', 'torn-pcl', 'visual-impairment']::text[],
    updated_at = now()
where id = '780cdfb2-513d-4bd0-83b8-2bff0f31e07f';

update public.exercises_library
set contraindication_tags = array['achondroplasia', 'athletic-pubalgia', 'cerebral-palsy-mild-moderate', 'chondromalacia', 'chronic-muscle-strain', 'collateral-ligament-injury', 'diastasis-recti', 'disc-herniation', 'femoroacetabular-impingement', 'hemiplegia-hemiparesis', 'hernia', 'hypertension', 'knee-osteoarthritis', 'labyrinthitis', 'lower-limb-amputation-unilateral', 'osteoporosis-osteopenia', 'patellar-tendinopathy', 'piriformis-syndrome', 'plantar-fasciitis', 'postpartum', 'pregnancy-trimester-1', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'rheumatoid-arthritis', 'spinal-cord-injury-paraplegia', 'torn-acl', 'torn-pcl', 'visual-impairment']::text[],
    updated_at = now()
where id = '9c71cdef-72aa-44c2-88f1-6494e3388a42';

update public.exercises_library
set contraindication_tags = array['cerebral-palsy-mild-moderate', 'chronic-muscle-strain', 'femoroacetabular-impingement', 'hemiplegia-hemiparesis', 'knee-osteoarthritis', 'labyrinthitis', 'osteoporosis-osteopenia', 'patellar-tendinopathy', 'piriformis-syndrome', 'plantar-fasciitis', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'torn-acl', 'visual-impairment']::text[],
    updated_at = now()
where id = 'db8015bb-1ddd-454d-8691-5a1874b757d0';

update public.exercises_library
set contraindication_tags = array['athletic-pubalgia', 'carpal-tunnel-de-quervain', 'cerebral-palsy-mild-moderate', 'chronic-muscle-strain', 'diastasis-recti', 'hemiplegia-hemiparesis', 'hypertension', 'knee-osteoarthritis', 'labyrinthitis', 'osteoporosis-osteopenia', 'patellar-tendinopathy', 'plantar-fasciitis', 'postpartum', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'rheumatoid-arthritis', 'tfcc-injury', 'torn-acl', 'visual-impairment']::text[],
    updated_at = now()
where id = '98fc73d9-935c-4cd6-8c55-e33392dd808c';

update public.exercises_library
set contraindication_tags = array['carpal-tunnel-de-quervain', 'cerebral-palsy-mild-moderate', 'chronic-muscle-strain', 'disc-herniation', 'hemiplegia-hemiparesis', 'hernia', 'hypertension', 'knee-osteoarthritis', 'labyrinthitis', 'osteoporosis-osteopenia', 'patellar-tendinopathy', 'plantar-fasciitis', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'rheumatoid-arthritis', 'spondylolisthesis', 'tfcc-injury', 'torn-acl', 'visual-impairment']::text[],
    updated_at = now()
where id = 'ea6bc101-0c0f-454c-818a-f8b5dca81b76';

update public.exercises_library
set contraindication_tags = array['athletic-pubalgia', 'carpal-tunnel-de-quervain', 'diastasis-recti', 'rheumatoid-arthritis', 'tfcc-injury']::text[],
    updated_at = now()
where id = 'eccbcca3-5847-403c-8010-315ad8d17320';

update public.exercises_library
set contraindication_tags = array['cerebral-palsy-mild-moderate', 'chronic-muscle-strain', 'hemiplegia-hemiparesis', 'knee-osteoarthritis', 'labyrinthitis', 'osteoporosis-osteopenia', 'patellar-tendinopathy', 'plantar-fasciitis', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'torn-acl', 'visual-impairment']::text[],
    updated_at = now()
where id = '36a59d98-2536-4d9c-83f1-12dd6688e752';

update public.exercises_library
set contraindication_tags = array['cerebral-palsy-mild-moderate', 'chronic-muscle-strain', 'hemiplegia-hemiparesis', 'knee-osteoarthritis', 'labyrinthitis', 'osteoporosis-osteopenia', 'patellar-tendinopathy', 'plantar-fasciitis', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'torn-acl', 'visual-impairment']::text[],
    updated_at = now()
where id = '74d35fdb-ca65-4d13-8b26-19af8331fb47';

update public.exercises_library
set contraindication_tags = array['ankle-ligament-sprain', 'cerebral-palsy-mild-moderate', 'chondromalacia', 'collateral-ligament-injury', 'hemiplegia-hemiparesis', 'hypertension', 'knee-osteoarthritis', 'labyrinthitis', 'lower-limb-amputation-unilateral', 'osteoporosis-osteopenia', 'patellar-tendinopathy', 'plantar-fasciitis', 'postpartum', 'pregnancy-trimester-1', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'spinal-cord-injury-paraplegia', 'torn-acl', 'visual-impairment']::text[],
    updated_at = now()
where id = '8857383d-04c5-449b-81ec-e1534aabe201';

update public.exercises_library
set contraindication_tags = array['achondroplasia', 'cerebral-palsy-mild-moderate', 'chondromalacia', 'collateral-ligament-injury', 'disc-herniation', 'hemiplegia-hemiparesis', 'hernia', 'hypertension', 'knee-osteoarthritis', 'labyrinthitis', 'lower-limb-amputation-unilateral', 'osteoporosis-osteopenia', 'patellar-tendinopathy', 'plantar-fasciitis', 'postpartum', 'pregnancy-trimester-1', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'rheumatoid-arthritis', 'spinal-cord-injury-paraplegia', 'torn-acl', 'torn-pcl', 'visual-impairment']::text[],
    updated_at = now()
where id = 'b6d4cf96-39e4-4061-86bf-3b3ff1a82f48';

update public.exercises_library
set contraindication_tags = array['achondroplasia', 'ankle-ligament-sprain', 'cerebral-palsy-mild-moderate', 'chondromalacia', 'collateral-ligament-injury', 'disc-herniation', 'hemiplegia-hemiparesis', 'hernia', 'hypertension', 'knee-osteoarthritis', 'labyrinthitis', 'lower-limb-amputation-unilateral', 'osteoporosis-osteopenia', 'patellar-tendinopathy', 'plantar-fasciitis', 'postpartum', 'pregnancy-trimester-1', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'rheumatoid-arthritis', 'spinal-cord-injury-paraplegia', 'torn-acl', 'torn-pcl', 'visual-impairment']::text[],
    updated_at = now()
where id = '4898e041-3321-42f1-84d8-22abf6fb50b2';

update public.exercises_library
set contraindication_tags = array['achondroplasia', 'cerebral-palsy-mild-moderate', 'chondromalacia', 'collateral-ligament-injury', 'disc-herniation', 'femoroacetabular-impingement', 'hemiplegia-hemiparesis', 'hernia', 'hypertension', 'knee-osteoarthritis', 'labyrinthitis', 'lower-limb-amputation-unilateral', 'osteoporosis-osteopenia', 'patellar-tendinopathy', 'piriformis-syndrome', 'plantar-fasciitis', 'postpartum', 'pregnancy-trimester-1', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'rheumatoid-arthritis', 'spinal-cord-injury-paraplegia', 'torn-acl', 'torn-pcl', 'visual-impairment']::text[],
    updated_at = now()
where id = 'dc1ba2de-7ab6-47d6-8f9b-c000af4b8dbc';

update public.exercises_library
set contraindication_tags = array['carpal-tunnel-de-quervain', 'chronic-muscle-strain', 'labyrinthitis', 'rheumatoid-arthritis', 'tfcc-injury']::text[],
    updated_at = now()
where id = '0adcb8ff-1b40-473a-8850-e93376694927';

update public.exercises_library
set contraindication_tags = array['ankle-ligament-sprain', 'carpal-tunnel-de-quervain', 'collateral-ligament-injury', 'hemiplegia-hemiparesis', 'pregnancy-trimester-3', 'rheumatoid-arthritis', 'tfcc-injury', 'torn-acl', 'visual-impairment']::text[],
    updated_at = now()
where id = '866d6867-839f-494b-8fe2-02cd49308ad7';

update public.exercises_library
set contraindication_tags = array['ankle-ligament-sprain', 'carpal-tunnel-de-quervain', 'collateral-ligament-injury', 'hemiplegia-hemiparesis', 'rheumatoid-arthritis', 'shoulder-instability', 'tfcc-injury', 'torn-acl', 'visual-impairment']::text[],
    updated_at = now()
where id = '052bc64e-f484-44c0-8985-dae34df8b942';

update public.exercises_library
set contraindication_tags = array['carpal-tunnel-de-quervain', 'disc-herniation', 'hernia', 'osteoporosis-osteopenia', 'rheumatoid-arthritis', 'spondylolisthesis', 'tfcc-injury']::text[],
    updated_at = now()
where id = 'ed4dd230-b3e0-4421-8631-30dad340f3cf';

update public.exercises_library
set contraindication_tags = array['disc-herniation', 'femoroacetabular-impingement', 'hernia', 'piriformis-syndrome', 'pregnancy-trimester-2', 'pregnancy-trimester-3', 'spinal-stenosis', 'spondylolisthesis']::text[],
    updated_at = now()
where id = '407dc114-6a52-40ca-8c42-49a13def5af8';

update public.exercises_library
set contraindication_tags = array['ac-joint-injury', 'elbow-ucl-injury', 'rotator-cuff-injury', 'shoulder-instability', 'slap-tear']::text[],
    updated_at = now()
where id = 'e7a37ed1-3b62-482b-8bc1-579a7b98b6f2';

update public.exercises_library
set contraindication_tags = '{}'::text[],
    updated_at = now()
where id = '955dfadf-6f1c-4332-826e-e81c83973b67';

update public.exercises_library
set contraindication_tags = '{}'::text[],
    updated_at = now()
where id = '5cb286fa-bbb3-47d5-8653-a4f79bcec509';

update public.exercises_library
set contraindication_tags = array['disc-herniation', 'hernia', 'osteoporosis-osteopenia', 'spondylolisthesis']::text[],
    updated_at = now()
where id = 'b06fa5f0-4863-4539-8f2a-45cf240ca01a';

update public.exercises_library
set contraindication_tags = array['chondromalacia', 'femoroacetabular-impingement', 'knee-osteoarthritis', 'torn-pcl']::text[],
    updated_at = now()
where id = 'e80774b4-c526-4af2-8e53-d9e3102a1c32';

update public.exercises_library
set contraindication_tags = array['athletic-pubalgia', 'diastasis-recti', 'olecranon-bursitis', 'postpartum']::text[],
    updated_at = now()
where id = 'b57e7cef-6995-48ee-8fd3-38eefe967fb7';

update public.exercises_library
set contraindication_tags = array['rotator-cuff-injury', 'shoulder-instability', 'subacromial-bursitis']::text[],
    updated_at = now()
where id = '92d42749-bf9a-4066-8726-9f428e9f69d2';

update public.exercises_library
set contraindication_tags = array['rotator-cuff-injury', 'subacromial-bursitis']::text[],
    updated_at = now()
where id = 'a0c0aec6-e80e-4df4-8bdb-9f982f9b4b43';

update public.exercises_library
set contraindication_tags = '{}'::text[],
    updated_at = now()
where id = 'b3eca6ef-68a4-4a54-8b39-cc095b7a48b7';

create or replace function public.list_safe_exercises()
returns setof public.exercises_library
language plpgsql
stable
security invoker
set search_path = ''
as $$
declare
  v_conditions text[] := '{}';
  v_capabilities text[] := '{}';
  v_equipment text[] := array['bodyweight']::text[];
  v_phases text[] := '{}';
  v_union text[] := '{}';
begin
  if not public.has_accepted_consent('health_personalization') then
    return;
  end if;

  select
    coalesce(clinical.condition_tags, '{}'),
    coalesce(clinical.capability_tags, '{}'),
    coalesce(clinical.available_equipment_tags, array['bodyweight']::text[])
  into v_conditions, v_capabilities, v_equipment
  from public.user_clinical_conditions as clinical
  where clinical.user_id = (select auth.uid());

  if not found then
    return;
  end if;

  if not ('bodyweight' = any (v_equipment)) then
    v_equipment := array_append(v_equipment, 'bodyweight');
  end if;

  select coalesce(cycle.phase_tags, '{}')
  into v_phases
  from public.user_cycle_profiles as cycle
  where cycle.user_id = (select auth.uid());

  if not found then
    v_phases := '{}';
  end if;

  v_union := v_conditions || v_phases;

  -- legacy alias: hernia ↔ disc-herniation
  if 'hernia' = any (v_union) and not ('disc-herniation' = any (v_union)) then
    v_union := array_append(v_union, 'disc-herniation');
  end if;
  if 'disc-herniation' = any (v_union) and not ('hernia' = any (v_union)) then
    v_union := array_append(v_union, 'hernia');
  end if;

  return query
  select exercise.*
  from public.exercises_library as exercise
  where exercise.is_published = true
    and not (exercise.contraindication_tags && v_union)
    -- posture tags (standing|seated|lying) are OR; other capabilities are AND
    and (
      coalesce((
        select array_agg(tag order by tag)
        from unnest(exercise.required_capability_tags) as tag
        where tag not in ('standing', 'seated', 'lying')
      ), '{}'::text[]) <@ v_capabilities
      and (
        not exists (
          select 1
          from unnest(exercise.required_capability_tags) as tag
          where tag in ('standing', 'seated', 'lying')
        )
        or exists (
          select 1
          from unnest(exercise.required_capability_tags) as tag
          where tag in ('standing', 'seated', 'lying')
            and tag = any (v_capabilities)
        )
      )
    )
    and (
      coalesce(cardinality(exercise.equipment_tags), 0) = 0
      or (
        not (
          'resistance-band' = any (exercise.equipment_tags)
          and not ('resistance-band' = any (v_equipment))
        )
        and not (
          'dumbbells' = any (exercise.equipment_tags)
          and not ('dumbbells' = any (v_equipment))
        )
        and exercise.equipment_tags && v_equipment
      )
    )
    and not exists (
      select 1
      from public.tag_block_rules as block_rule
      where block_rule.condition_slug = any (v_union)
        and block_rule.blocked_content_tag = any (exercise.intensity_tags)
    )
  order by exercise.title;
end;
$$;

comment on function public.list_safe_exercises() is
  'Motor de treino. Bloqueia contraindicações, capabilities (postura OR), specialty equipment e tag_block_rules. Normaliza hernia/disc-herniation.';

revoke all on function public.list_safe_exercises() from public;
revoke all on function public.list_safe_exercises() from anon;
grant execute on function public.list_safe_exercises() to authenticated;

